// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: routeiq/v1/control/escalation.proto

package controlv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EscalationUrgency int32

const (
	EscalationUrgency_ESCALATION_URGENCY_UNSPECIFIED EscalationUrgency = 0
	EscalationUrgency_LOW                            EscalationUrgency = 1
	EscalationUrgency_MEDIUM                         EscalationUrgency = 2
	EscalationUrgency_HIGH                           EscalationUrgency = 3
	EscalationUrgency_CRITICAL                       EscalationUrgency = 4
)

// Enum value maps for EscalationUrgency.
var (
	EscalationUrgency_name = map[int32]string{
		0: "ESCALATION_URGENCY_UNSPECIFIED",
		1: "LOW",
		2: "MEDIUM",
		3: "HIGH",
		4: "CRITICAL",
	}
	EscalationUrgency_value = map[string]int32{
		"ESCALATION_URGENCY_UNSPECIFIED": 0,
		"LOW":                            1,
		"MEDIUM":                         2,
		"HIGH":                           3,
		"CRITICAL":                       4,
	}
)

func (x EscalationUrgency) Enum() *EscalationUrgency {
	p := new(EscalationUrgency)
	*p = x
	return p
}

func (x EscalationUrgency) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EscalationUrgency) Descriptor() protoreflect.EnumDescriptor {
	return file_routeiq_v1_control_escalation_proto_enumTypes[0].Descriptor()
}

func (EscalationUrgency) Type() protoreflect.EnumType {
	return &file_routeiq_v1_control_escalation_proto_enumTypes[0]
}

func (x EscalationUrgency) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EscalationUrgency.Descriptor instead.
func (EscalationUrgency) EnumDescriptor() ([]byte, []int) {
	return file_routeiq_v1_control_escalation_proto_rawDescGZIP(), []int{0}
}

type EscalationState int32

const (
	EscalationState_ESCALATION_STATE_UNSPECIFIED EscalationState = 0
	EscalationState_OPEN                         EscalationState = 1
	EscalationState_ACKNOWLEDGED                 EscalationState = 2
	EscalationState_RESOLVED                     EscalationState = 3
	EscalationState_TIMED_OUT                    EscalationState = 4
)

// Enum value maps for EscalationState.
var (
	EscalationState_name = map[int32]string{
		0: "ESCALATION_STATE_UNSPECIFIED",
		1: "OPEN",
		2: "ACKNOWLEDGED",
		3: "RESOLVED",
		4: "TIMED_OUT",
	}
	EscalationState_value = map[string]int32{
		"ESCALATION_STATE_UNSPECIFIED": 0,
		"OPEN":                         1,
		"ACKNOWLEDGED":                 2,
		"RESOLVED":                     3,
		"TIMED_OUT":                    4,
	}
)

func (x EscalationState) Enum() *EscalationState {
	p := new(EscalationState)
	*p = x
	return p
}

func (x EscalationState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EscalationState) Descriptor() protoreflect.EnumDescriptor {
	return file_routeiq_v1_control_escalation_proto_enumTypes[1].Descriptor()
}

func (EscalationState) Type() protoreflect.EnumType {
	return &file_routeiq_v1_control_escalation_proto_enumTypes[1]
}

func (x EscalationState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EscalationState.Descriptor instead.
func (EscalationState) EnumDescriptor() ([]byte, []int) {
	return file_routeiq_v1_control_escalation_proto_rawDescGZIP(), []int{1}
}

type EscalateRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Reason         string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	ContextSummary string                 `protobuf:"bytes,3,opt,name=context_summary,json=contextSummary,proto3" json:"context_summary,omitempty"`
	Urgency        EscalationUrgency      `protobuf:"varint,4,opt,name=urgency,proto3,enum=routeiq.v1.control.EscalationUrgency" json:"urgency,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EscalateRequest) Reset() {
	*x = EscalateRequest{}
	mi := &file_routeiq_v1_control_escalation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EscalateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EscalateRequest) ProtoMessage() {}

func (x *EscalateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_control_escalation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EscalateRequest.ProtoReflect.Descriptor instead.
func (*EscalateRequest) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_control_escalation_proto_rawDescGZIP(), []int{0}
}

func (x *EscalateRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *EscalateRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *EscalateRequest) GetContextSummary() string {
	if x != nil {
		return x.ContextSummary
	}
	return ""
}

func (x *EscalateRequest) GetUrgency() EscalationUrgency {
	if x != nil {
		return x.Urgency
	}
	return EscalationUrgency_ESCALATION_URGENCY_UNSPECIFIED
}

type EscalateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EscalationId  string                 `protobuf:"bytes,1,opt,name=escalation_id,json=escalationId,proto3" json:"escalation_id,omitempty"`
	State         EscalationState        `protobuf:"varint,2,opt,name=state,proto3,enum=routeiq.v1.control.EscalationState" json:"state,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EscalateResponse) Reset() {
	*x = EscalateResponse{}
	mi := &file_routeiq_v1_control_escalation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EscalateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EscalateResponse) ProtoMessage() {}

func (x *EscalateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_control_escalation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EscalateResponse.ProtoReflect.Descriptor instead.
func (*EscalateResponse) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_control_escalation_proto_rawDescGZIP(), []int{1}
}

func (x *EscalateResponse) GetEscalationId() string {
	if x != nil {
		return x.EscalationId
	}
	return ""
}

func (x *EscalateResponse) GetState() EscalationState {
	if x != nil {
		return x.State
	}
	return EscalationState_ESCALATION_STATE_UNSPECIFIED
}

func (x *EscalateResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ResolveEscalationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EscalationId  string                 `protobuf:"bytes,1,opt,name=escalation_id,json=escalationId,proto3" json:"escalation_id,omitempty"`
	Resolution    string                 `protobuf:"bytes,2,opt,name=resolution,proto3" json:"resolution,omitempty"`
	Approved      bool                   `protobuf:"varint,3,opt,name=approved,proto3" json:"approved,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveEscalationRequest) Reset() {
	*x = ResolveEscalationRequest{}
	mi := &file_routeiq_v1_control_escalation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveEscalationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveEscalationRequest) ProtoMessage() {}

func (x *ResolveEscalationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_control_escalation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveEscalationRequest.ProtoReflect.Descriptor instead.
func (*ResolveEscalationRequest) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_control_escalation_proto_rawDescGZIP(), []int{2}
}

func (x *ResolveEscalationRequest) GetEscalationId() string {
	if x != nil {
		return x.EscalationId
	}
	return ""
}

func (x *ResolveEscalationRequest) GetResolution() string {
	if x != nil {
		return x.Resolution
	}
	return ""
}

func (x *ResolveEscalationRequest) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

type ResolveEscalationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveEscalationResponse) Reset() {
	*x = ResolveEscalationResponse{}
	mi := &file_routeiq_v1_control_escalation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveEscalationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveEscalationResponse) ProtoMessage() {}

func (x *ResolveEscalationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_control_escalation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveEscalationResponse.ProtoReflect.Descriptor instead.
func (*ResolveEscalationResponse) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_control_escalation_proto_rawDescGZIP(), []int{3}
}

func (x *ResolveEscalationResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

var File_routeiq_v1_control_escalation_proto protoreflect.FileDescriptor

const file_routeiq_v1_control_escalation_proto_rawDesc = "" +
	"\n" +
	"#routeiq/v1/control/escalation.proto\x12\x12routeiq.v1.control\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb2\x01\n" +
	"\x0fEscalateRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12'\n" +
	"\x0fcontext_summary\x18\x03 \x01(\tR\x0econtextSummary\x12?\n" +
	"\aurgency\x18\x04 \x01(\x0e2%.routeiq.v1.control.EscalationUrgencyR\aurgency\"\xad\x01\n" +
	"\x10EscalateResponse\x12#\n" +
	"\rescalation_id\x18\x01 \x01(\tR\fescalationId\x129\n" +
	"\x05state\x18\x02 \x01(\x0e2#.routeiq.v1.control.EscalationStateR\x05state\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"{\n" +
	"\x18ResolveEscalationRequest\x12#\n" +
	"\rescalation_id\x18\x01 \x01(\tR\fescalationId\x12\x1e\n" +
	"\n" +
	"resolution\x18\x02 \x01(\tR\n" +
	"resolution\x12\x1a\n" +
	"\bapproved\x18\x03 \x01(\bR\bapproved\"7\n" +
	"\x19ResolveEscalationResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted*d\n" +
	"\x11EscalationUrgency\x12\"\n" +
	"\x1eESCALATION_URGENCY_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03LOW\x10\x01\x12\n" +
	"\n" +
	"\x06MEDIUM\x10\x02\x12\b\n" +
	"\x04HIGH\x10\x03\x12\f\n" +
	"\bCRITICAL\x10\x04*l\n" +
	"\x0fEscalationState\x12 \n" +
	"\x1cESCALATION_STATE_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04OPEN\x10\x01\x12\x10\n" +
	"\fACKNOWLEDGED\x10\x02\x12\f\n" +
	"\bRESOLVED\x10\x03\x12\r\n" +
	"\tTIMED_OUT\x10\x042\xdc\x01\n" +
	"\x11EscalationService\x12U\n" +
	"\bEscalate\x12#.routeiq.v1.control.EscalateRequest\x1a$.routeiq.v1.control.EscalateResponse\x12p\n" +
	"\x11ResolveEscalation\x12,.routeiq.v1.control.ResolveEscalationRequest\x1a-.routeiq.v1.control.ResolveEscalationResponseB\x95\x01\n" +
	"0build.buf.gen.ssforge.routeiq.routeiq.v1.controlB\x0fEscalationProtoZPbuf.build/gen/go/ssforge/routeiq/protocolbuffers/go/routeiq/v1/control;controlv1b\x06proto3"

var (
	file_routeiq_v1_control_escalation_proto_rawDescOnce sync.Once
	file_routeiq_v1_control_escalation_proto_rawDescData []byte
)

func file_routeiq_v1_control_escalation_proto_rawDescGZIP() []byte {
	file_routeiq_v1_control_escalation_proto_rawDescOnce.Do(func() {
		file_routeiq_v1_control_escalation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_routeiq_v1_control_escalation_proto_rawDesc), len(file_routeiq_v1_control_escalation_proto_rawDesc)))
	})
	return file_routeiq_v1_control_escalation_proto_rawDescData
}

var file_routeiq_v1_control_escalation_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_routeiq_v1_control_escalation_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_routeiq_v1_control_escalation_proto_goTypes = []any{
	(EscalationUrgency)(0),            // 0: routeiq.v1.control.EscalationUrgency
	(EscalationState)(0),              // 1: routeiq.v1.control.EscalationState
	(*EscalateRequest)(nil),           // 2: routeiq.v1.control.EscalateRequest
	(*EscalateResponse)(nil),          // 3: routeiq.v1.control.EscalateResponse
	(*ResolveEscalationRequest)(nil),  // 4: routeiq.v1.control.ResolveEscalationRequest
	(*ResolveEscalationResponse)(nil), // 5: routeiq.v1.control.ResolveEscalationResponse
	(*timestamppb.Timestamp)(nil),     // 6: google.protobuf.Timestamp
}
var file_routeiq_v1_control_escalation_proto_depIdxs = []int32{
	0, // 0: routeiq.v1.control.EscalateRequest.urgency:type_name -> routeiq.v1.control.EscalationUrgency
	1, // 1: routeiq.v1.control.EscalateResponse.state:type_name -> routeiq.v1.control.EscalationState
	6, // 2: routeiq.v1.control.EscalateResponse.created_at:type_name -> google.protobuf.Timestamp
	2, // 3: routeiq.v1.control.EscalationService.Escalate:input_type -> routeiq.v1.control.EscalateRequest
	4, // 4: routeiq.v1.control.EscalationService.ResolveEscalation:input_type -> routeiq.v1.control.ResolveEscalationRequest
	3, // 5: routeiq.v1.control.EscalationService.Escalate:output_type -> routeiq.v1.control.EscalateResponse
	5, // 6: routeiq.v1.control.EscalationService.ResolveEscalation:output_type -> routeiq.v1.control.ResolveEscalationResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_routeiq_v1_control_escalation_proto_init() }
func file_routeiq_v1_control_escalation_proto_init() {
	if File_routeiq_v1_control_escalation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_routeiq_v1_control_escalation_proto_rawDesc), len(file_routeiq_v1_control_escalation_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_routeiq_v1_control_escalation_proto_goTypes,
		DependencyIndexes: file_routeiq_v1_control_escalation_proto_depIdxs,
		EnumInfos:         file_routeiq_v1_control_escalation_proto_enumTypes,
		MessageInfos:      file_routeiq_v1_control_escalation_proto_msgTypes,
	}.Build()
	File_routeiq_v1_control_escalation_proto = out.File
	file_routeiq_v1_control_escalation_proto_goTypes = nil
	file_routeiq_v1_control_escalation_proto_depIdxs = nil
}
