// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: routeiq/v1/control/guardrail.proto

package controlv1

import (
	telemetry "buf.build/gen/go/ssforge/routeiq/protocolbuffers/go/routeiq/v1/telemetry"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GuardrailVerdict int32

const (
	GuardrailVerdict_GUARDRAIL_VERDICT_UNSPECIFIED GuardrailVerdict = 0
	GuardrailVerdict_ALLOW                         GuardrailVerdict = 1
	GuardrailVerdict_BLOCK                         GuardrailVerdict = 2
	GuardrailVerdict_REQUIRE_APPROVAL              GuardrailVerdict = 3
)

// Enum value maps for GuardrailVerdict.
var (
	GuardrailVerdict_name = map[int32]string{
		0: "GUARDRAIL_VERDICT_UNSPECIFIED",
		1: "ALLOW",
		2: "BLOCK",
		3: "REQUIRE_APPROVAL",
	}
	GuardrailVerdict_value = map[string]int32{
		"GUARDRAIL_VERDICT_UNSPECIFIED": 0,
		"ALLOW":                         1,
		"BLOCK":                         2,
		"REQUIRE_APPROVAL":              3,
	}
)

func (x GuardrailVerdict) Enum() *GuardrailVerdict {
	p := new(GuardrailVerdict)
	*p = x
	return p
}

func (x GuardrailVerdict) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GuardrailVerdict) Descriptor() protoreflect.EnumDescriptor {
	return file_routeiq_v1_control_guardrail_proto_enumTypes[0].Descriptor()
}

func (GuardrailVerdict) Type() protoreflect.EnumType {
	return &file_routeiq_v1_control_guardrail_proto_enumTypes[0]
}

func (x GuardrailVerdict) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GuardrailVerdict.Descriptor instead.
func (GuardrailVerdict) EnumDescriptor() ([]byte, []int) {
	return file_routeiq_v1_control_guardrail_proto_rawDescGZIP(), []int{0}
}

type CheckGuardrailRequest struct {
	state           protoimpl.MessageState    `protogen:"open.v1"`
	SessionId       string                    `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ProposedAction  string                    `protobuf:"bytes,2,opt,name=proposed_action,json=proposedAction,proto3" json:"proposed_action,omitempty"`
	PermissionLevel telemetry.PermissionLevel `protobuf:"varint,3,opt,name=permission_level,json=permissionLevel,proto3,enum=routeiq.v1.telemetry.PermissionLevel" json:"permission_level,omitempty"`
	RiskContext     string                    `protobuf:"bytes,4,opt,name=risk_context,json=riskContext,proto3" json:"risk_context,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CheckGuardrailRequest) Reset() {
	*x = CheckGuardrailRequest{}
	mi := &file_routeiq_v1_control_guardrail_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckGuardrailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckGuardrailRequest) ProtoMessage() {}

func (x *CheckGuardrailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_control_guardrail_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckGuardrailRequest.ProtoReflect.Descriptor instead.
func (*CheckGuardrailRequest) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_control_guardrail_proto_rawDescGZIP(), []int{0}
}

func (x *CheckGuardrailRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CheckGuardrailRequest) GetProposedAction() string {
	if x != nil {
		return x.ProposedAction
	}
	return ""
}

func (x *CheckGuardrailRequest) GetPermissionLevel() telemetry.PermissionLevel {
	if x != nil {
		return x.PermissionLevel
	}
	return telemetry.PermissionLevel(0)
}

func (x *CheckGuardrailRequest) GetRiskContext() string {
	if x != nil {
		return x.RiskContext
	}
	return ""
}

type CheckGuardrailResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Verdict            GuardrailVerdict       `protobuf:"varint,1,opt,name=verdict,proto3,enum=routeiq.v1.control.GuardrailVerdict" json:"verdict,omitempty"`
	Reason             string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	PolicyIdsTriggered []string               `protobuf:"bytes,3,rep,name=policy_ids_triggered,json=policyIdsTriggered,proto3" json:"policy_ids_triggered,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CheckGuardrailResponse) Reset() {
	*x = CheckGuardrailResponse{}
	mi := &file_routeiq_v1_control_guardrail_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckGuardrailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckGuardrailResponse) ProtoMessage() {}

func (x *CheckGuardrailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_control_guardrail_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckGuardrailResponse.ProtoReflect.Descriptor instead.
func (*CheckGuardrailResponse) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_control_guardrail_proto_rawDescGZIP(), []int{1}
}

func (x *CheckGuardrailResponse) GetVerdict() GuardrailVerdict {
	if x != nil {
		return x.Verdict
	}
	return GuardrailVerdict_GUARDRAIL_VERDICT_UNSPECIFIED
}

func (x *CheckGuardrailResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CheckGuardrailResponse) GetPolicyIdsTriggered() []string {
	if x != nil {
		return x.PolicyIdsTriggered
	}
	return nil
}

type RegisterPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PolicyId      string                 `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	BundleVersion string                 `protobuf:"bytes,2,opt,name=bundle_version,json=bundleVersion,proto3" json:"bundle_version,omitempty"`
	PolicyContent []byte                 `protobuf:"bytes,3,opt,name=policy_content,json=policyContent,proto3" json:"policy_content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterPolicyRequest) Reset() {
	*x = RegisterPolicyRequest{}
	mi := &file_routeiq_v1_control_guardrail_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPolicyRequest) ProtoMessage() {}

func (x *RegisterPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_control_guardrail_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterPolicyRequest.ProtoReflect.Descriptor instead.
func (*RegisterPolicyRequest) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_control_guardrail_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterPolicyRequest) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *RegisterPolicyRequest) GetBundleVersion() string {
	if x != nil {
		return x.BundleVersion
	}
	return ""
}

func (x *RegisterPolicyRequest) GetPolicyContent() []byte {
	if x != nil {
		return x.PolicyContent
	}
	return nil
}

type RegisterPolicyResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Accepted         bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	EffectiveVersion string                 `protobuf:"bytes,2,opt,name=effective_version,json=effectiveVersion,proto3" json:"effective_version,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegisterPolicyResponse) Reset() {
	*x = RegisterPolicyResponse{}
	mi := &file_routeiq_v1_control_guardrail_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPolicyResponse) ProtoMessage() {}

func (x *RegisterPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_control_guardrail_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterPolicyResponse.ProtoReflect.Descriptor instead.
func (*RegisterPolicyResponse) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_control_guardrail_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterPolicyResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RegisterPolicyResponse) GetEffectiveVersion() string {
	if x != nil {
		return x.EffectiveVersion
	}
	return ""
}

var File_routeiq_v1_control_guardrail_proto protoreflect.FileDescriptor

const file_routeiq_v1_control_guardrail_proto_rawDesc = "" +
	"\n" +
	"\"routeiq/v1/control/guardrail.proto\x12\x12routeiq.v1.control\x1a#routeiq/v1/telemetry/entities.proto\"\xd4\x01\n" +
	"\x15CheckGuardrailRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12'\n" +
	"\x0fproposed_action\x18\x02 \x01(\tR\x0eproposedAction\x12P\n" +
	"\x10permission_level\x18\x03 \x01(\x0e2%.routeiq.v1.telemetry.PermissionLevelR\x0fpermissionLevel\x12!\n" +
	"\frisk_context\x18\x04 \x01(\tR\vriskContext\"\xa2\x01\n" +
	"\x16CheckGuardrailResponse\x12>\n" +
	"\averdict\x18\x01 \x01(\x0e2$.routeiq.v1.control.GuardrailVerdictR\averdict\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x120\n" +
	"\x14policy_ids_triggered\x18\x03 \x03(\tR\x12policyIdsTriggered\"\x82\x01\n" +
	"\x15RegisterPolicyRequest\x12\x1b\n" +
	"\tpolicy_id\x18\x01 \x01(\tR\bpolicyId\x12%\n" +
	"\x0ebundle_version\x18\x02 \x01(\tR\rbundleVersion\x12%\n" +
	"\x0epolicy_content\x18\x03 \x01(\fR\rpolicyContent\"a\n" +
	"\x16RegisterPolicyResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12+\n" +
	"\x11effective_version\x18\x02 \x01(\tR\x10effectiveVersion*a\n" +
	"\x10GuardrailVerdict\x12!\n" +
	"\x1dGUARDRAIL_VERDICT_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05ALLOW\x10\x01\x12\t\n" +
	"\x05BLOCK\x10\x02\x12\x14\n" +
	"\x10REQUIRE_APPROVAL\x10\x032\xe4\x01\n" +
	"\x10GuardrailService\x12g\n" +
	"\x0eCheckGuardrail\x12).routeiq.v1.control.CheckGuardrailRequest\x1a*.routeiq.v1.control.CheckGuardrailResponse\x12g\n" +
	"\x0eRegisterPolicy\x12).routeiq.v1.control.RegisterPolicyRequest\x1a*.routeiq.v1.control.RegisterPolicyResponseB\x94\x01\n" +
	"0build.buf.gen.ssforge.routeiq.routeiq.v1.controlB\x0eGuardrailProtoZPbuf.build/gen/go/ssforge/routeiq/protocolbuffers/go/routeiq/v1/control;controlv1b\x06proto3"

var (
	file_routeiq_v1_control_guardrail_proto_rawDescOnce sync.Once
	file_routeiq_v1_control_guardrail_proto_rawDescData []byte
)

func file_routeiq_v1_control_guardrail_proto_rawDescGZIP() []byte {
	file_routeiq_v1_control_guardrail_proto_rawDescOnce.Do(func() {
		file_routeiq_v1_control_guardrail_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_routeiq_v1_control_guardrail_proto_rawDesc), len(file_routeiq_v1_control_guardrail_proto_rawDesc)))
	})
	return file_routeiq_v1_control_guardrail_proto_rawDescData
}

var file_routeiq_v1_control_guardrail_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_routeiq_v1_control_guardrail_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_routeiq_v1_control_guardrail_proto_goTypes = []any{
	(GuardrailVerdict)(0),          // 0: routeiq.v1.control.GuardrailVerdict
	(*CheckGuardrailRequest)(nil),  // 1: routeiq.v1.control.CheckGuardrailRequest
	(*CheckGuardrailResponse)(nil), // 2: routeiq.v1.control.CheckGuardrailResponse
	(*RegisterPolicyRequest)(nil),  // 3: routeiq.v1.control.RegisterPolicyRequest
	(*RegisterPolicyResponse)(nil), // 4: routeiq.v1.control.RegisterPolicyResponse
	(telemetry.PermissionLevel)(0), // 5: routeiq.v1.telemetry.PermissionLevel
}
var file_routeiq_v1_control_guardrail_proto_depIdxs = []int32{
	5, // 0: routeiq.v1.control.CheckGuardrailRequest.permission_level:type_name -> routeiq.v1.telemetry.PermissionLevel
	0, // 1: routeiq.v1.control.CheckGuardrailResponse.verdict:type_name -> routeiq.v1.control.GuardrailVerdict
	1, // 2: routeiq.v1.control.GuardrailService.CheckGuardrail:input_type -> routeiq.v1.control.CheckGuardrailRequest
	3, // 3: routeiq.v1.control.GuardrailService.RegisterPolicy:input_type -> routeiq.v1.control.RegisterPolicyRequest
	2, // 4: routeiq.v1.control.GuardrailService.CheckGuardrail:output_type -> routeiq.v1.control.CheckGuardrailResponse
	4, // 5: routeiq.v1.control.GuardrailService.RegisterPolicy:output_type -> routeiq.v1.control.RegisterPolicyResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_routeiq_v1_control_guardrail_proto_init() }
func file_routeiq_v1_control_guardrail_proto_init() {
	if File_routeiq_v1_control_guardrail_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_routeiq_v1_control_guardrail_proto_rawDesc), len(file_routeiq_v1_control_guardrail_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_routeiq_v1_control_guardrail_proto_goTypes,
		DependencyIndexes: file_routeiq_v1_control_guardrail_proto_depIdxs,
		EnumInfos:         file_routeiq_v1_control_guardrail_proto_enumTypes,
		MessageInfos:      file_routeiq_v1_control_guardrail_proto_msgTypes,
	}.Build()
	File_routeiq_v1_control_guardrail_proto = out.File
	file_routeiq_v1_control_guardrail_proto_goTypes = nil
	file_routeiq_v1_control_guardrail_proto_depIdxs = nil
}
