// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: routeiq/v1/control/intervention.proto

package controlv1

import (
	telemetry "buf.build/gen/go/ssforge/routeiq/protocolbuffers/go/routeiq/v1/telemetry"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InterventionKind int32

const (
	InterventionKind_INTERVENTION_KIND_UNSPECIFIED InterventionKind = 0
	InterventionKind_CIRCUIT_BREAK                 InterventionKind = 1
	InterventionKind_ROLLBACK                      InterventionKind = 2
	InterventionKind_AUTONOMY_DOWNGRADE            InterventionKind = 3
	InterventionKind_MODEL_SWAP                    InterventionKind = 4
	InterventionKind_HARD_STOP                     InterventionKind = 5
)

// Enum value maps for InterventionKind.
var (
	InterventionKind_name = map[int32]string{
		0: "INTERVENTION_KIND_UNSPECIFIED",
		1: "CIRCUIT_BREAK",
		2: "ROLLBACK",
		3: "AUTONOMY_DOWNGRADE",
		4: "MODEL_SWAP",
		5: "HARD_STOP",
	}
	InterventionKind_value = map[string]int32{
		"INTERVENTION_KIND_UNSPECIFIED": 0,
		"CIRCUIT_BREAK":                 1,
		"ROLLBACK":                      2,
		"AUTONOMY_DOWNGRADE":            3,
		"MODEL_SWAP":                    4,
		"HARD_STOP":                     5,
	}
)

func (x InterventionKind) Enum() *InterventionKind {
	p := new(InterventionKind)
	*p = x
	return p
}

func (x InterventionKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InterventionKind) Descriptor() protoreflect.EnumDescriptor {
	return file_routeiq_v1_control_intervention_proto_enumTypes[0].Descriptor()
}

func (InterventionKind) Type() protoreflect.EnumType {
	return &file_routeiq_v1_control_intervention_proto_enumTypes[0]
}

func (x InterventionKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InterventionKind.Descriptor instead.
func (InterventionKind) EnumDescriptor() ([]byte, []int) {
	return file_routeiq_v1_control_intervention_proto_rawDescGZIP(), []int{0}
}

type TriggerInterventionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Kind          InterventionKind       `protobuf:"varint,2,opt,name=kind,proto3,enum=routeiq.v1.control.InterventionKind" json:"kind,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	DowngradeTo   telemetry.AutonomyMode `protobuf:"varint,4,opt,name=downgrade_to,json=downgradeTo,proto3,enum=routeiq.v1.telemetry.AutonomyMode" json:"downgrade_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerInterventionRequest) Reset() {
	*x = TriggerInterventionRequest{}
	mi := &file_routeiq_v1_control_intervention_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerInterventionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerInterventionRequest) ProtoMessage() {}

func (x *TriggerInterventionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_control_intervention_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerInterventionRequest.ProtoReflect.Descriptor instead.
func (*TriggerInterventionRequest) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_control_intervention_proto_rawDescGZIP(), []int{0}
}

func (x *TriggerInterventionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TriggerInterventionRequest) GetKind() InterventionKind {
	if x != nil {
		return x.Kind
	}
	return InterventionKind_INTERVENTION_KIND_UNSPECIFIED
}

func (x *TriggerInterventionRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *TriggerInterventionRequest) GetDowngradeTo() telemetry.AutonomyMode {
	if x != nil {
		return x.DowngradeTo
	}
	return telemetry.AutonomyMode(0)
}

type TriggerInterventionResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InterventionId string                 `protobuf:"bytes,1,opt,name=intervention_id,json=interventionId,proto3" json:"intervention_id,omitempty"`
	Applied        bool                   `protobuf:"varint,2,opt,name=applied,proto3" json:"applied,omitempty"`
	AppliedAt      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=applied_at,json=appliedAt,proto3" json:"applied_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TriggerInterventionResponse) Reset() {
	*x = TriggerInterventionResponse{}
	mi := &file_routeiq_v1_control_intervention_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerInterventionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerInterventionResponse) ProtoMessage() {}

func (x *TriggerInterventionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_control_intervention_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerInterventionResponse.ProtoReflect.Descriptor instead.
func (*TriggerInterventionResponse) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_control_intervention_proto_rawDescGZIP(), []int{1}
}

func (x *TriggerInterventionResponse) GetInterventionId() string {
	if x != nil {
		return x.InterventionId
	}
	return ""
}

func (x *TriggerInterventionResponse) GetApplied() bool {
	if x != nil {
		return x.Applied
	}
	return false
}

func (x *TriggerInterventionResponse) GetAppliedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AppliedAt
	}
	return nil
}

type GetInterventionStatusRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InterventionId string                 `protobuf:"bytes,1,opt,name=intervention_id,json=interventionId,proto3" json:"intervention_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetInterventionStatusRequest) Reset() {
	*x = GetInterventionStatusRequest{}
	mi := &file_routeiq_v1_control_intervention_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInterventionStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInterventionStatusRequest) ProtoMessage() {}

func (x *GetInterventionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_control_intervention_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInterventionStatusRequest.ProtoReflect.Descriptor instead.
func (*GetInterventionStatusRequest) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_control_intervention_proto_rawDescGZIP(), []int{2}
}

func (x *GetInterventionStatusRequest) GetInterventionId() string {
	if x != nil {
		return x.InterventionId
	}
	return ""
}

type GetInterventionStatusResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InterventionId string                 `protobuf:"bytes,1,opt,name=intervention_id,json=interventionId,proto3" json:"intervention_id,omitempty"`
	Kind           InterventionKind       `protobuf:"varint,2,opt,name=kind,proto3,enum=routeiq.v1.control.InterventionKind" json:"kind,omitempty"`
	Active         bool                   `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetInterventionStatusResponse) Reset() {
	*x = GetInterventionStatusResponse{}
	mi := &file_routeiq_v1_control_intervention_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInterventionStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInterventionStatusResponse) ProtoMessage() {}

func (x *GetInterventionStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_control_intervention_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInterventionStatusResponse.ProtoReflect.Descriptor instead.
func (*GetInterventionStatusResponse) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_control_intervention_proto_rawDescGZIP(), []int{3}
}

func (x *GetInterventionStatusResponse) GetInterventionId() string {
	if x != nil {
		return x.InterventionId
	}
	return ""
}

func (x *GetInterventionStatusResponse) GetKind() InterventionKind {
	if x != nil {
		return x.Kind
	}
	return InterventionKind_INTERVENTION_KIND_UNSPECIFIED
}

func (x *GetInterventionStatusResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

var File_routeiq_v1_control_intervention_proto protoreflect.FileDescriptor

const file_routeiq_v1_control_intervention_proto_rawDesc = "" +
	"\n" +
	"%routeiq/v1/control/intervention.proto\x12\x12routeiq.v1.control\x1a\x1fgoogle/protobuf/timestamp.proto\x1a#routeiq/v1/telemetry/entities.proto\"\xd4\x01\n" +
	"\x1aTriggerInterventionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x128\n" +
	"\x04kind\x18\x02 \x01(\x0e2$.routeiq.v1.control.InterventionKindR\x04kind\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12E\n" +
	"\fdowngrade_to\x18\x04 \x01(\x0e2\".routeiq.v1.telemetry.AutonomyModeR\vdowngradeTo\"\x9b\x01\n" +
	"\x1bTriggerInterventionResponse\x12'\n" +
	"\x0fintervention_id\x18\x01 \x01(\tR\x0einterventionId\x12\x18\n" +
	"\aapplied\x18\x02 \x01(\bR\aapplied\x129\n" +
	"\n" +
	"applied_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tappliedAt\"G\n" +
	"\x1cGetInterventionStatusRequest\x12'\n" +
	"\x0fintervention_id\x18\x01 \x01(\tR\x0einterventionId\"\x9a\x01\n" +
	"\x1dGetInterventionStatusResponse\x12'\n" +
	"\x0fintervention_id\x18\x01 \x01(\tR\x0einterventionId\x128\n" +
	"\x04kind\x18\x02 \x01(\x0e2$.routeiq.v1.control.InterventionKindR\x04kind\x12\x16\n" +
	"\x06active\x18\x03 \x01(\bR\x06active*\x8d\x01\n" +
	"\x10InterventionKind\x12!\n" +
	"\x1dINTERVENTION_KIND_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rCIRCUIT_BREAK\x10\x01\x12\f\n" +
	"\bROLLBACK\x10\x02\x12\x16\n" +
	"\x12AUTONOMY_DOWNGRADE\x10\x03\x12\x0e\n" +
	"\n" +
	"MODEL_SWAP\x10\x04\x12\r\n" +
	"\tHARD_STOP\x10\x052\x8b\x02\n" +
	"\x13InterventionService\x12v\n" +
	"\x13TriggerIntervention\x12..routeiq.v1.control.TriggerInterventionRequest\x1a/.routeiq.v1.control.TriggerInterventionResponse\x12|\n" +
	"\x15GetInterventionStatus\x120.routeiq.v1.control.GetInterventionStatusRequest\x1a1.routeiq.v1.control.GetInterventionStatusResponseB\x97\x01\n" +
	"0build.buf.gen.ssforge.routeiq.routeiq.v1.controlB\x11InterventionProtoZPbuf.build/gen/go/ssforge/routeiq/protocolbuffers/go/routeiq/v1/control;controlv1b\x06proto3"

var (
	file_routeiq_v1_control_intervention_proto_rawDescOnce sync.Once
	file_routeiq_v1_control_intervention_proto_rawDescData []byte
)

func file_routeiq_v1_control_intervention_proto_rawDescGZIP() []byte {
	file_routeiq_v1_control_intervention_proto_rawDescOnce.Do(func() {
		file_routeiq_v1_control_intervention_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_routeiq_v1_control_intervention_proto_rawDesc), len(file_routeiq_v1_control_intervention_proto_rawDesc)))
	})
	return file_routeiq_v1_control_intervention_proto_rawDescData
}

var file_routeiq_v1_control_intervention_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_routeiq_v1_control_intervention_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_routeiq_v1_control_intervention_proto_goTypes = []any{
	(InterventionKind)(0),                 // 0: routeiq.v1.control.InterventionKind
	(*TriggerInterventionRequest)(nil),    // 1: routeiq.v1.control.TriggerInterventionRequest
	(*TriggerInterventionResponse)(nil),   // 2: routeiq.v1.control.TriggerInterventionResponse
	(*GetInterventionStatusRequest)(nil),  // 3: routeiq.v1.control.GetInterventionStatusRequest
	(*GetInterventionStatusResponse)(nil), // 4: routeiq.v1.control.GetInterventionStatusResponse
	(telemetry.AutonomyMode)(0),           // 5: routeiq.v1.telemetry.AutonomyMode
	(*timestamppb.Timestamp)(nil),         // 6: google.protobuf.Timestamp
}
var file_routeiq_v1_control_intervention_proto_depIdxs = []int32{
	0, // 0: routeiq.v1.control.TriggerInterventionRequest.kind:type_name -> routeiq.v1.control.InterventionKind
	5, // 1: routeiq.v1.control.TriggerInterventionRequest.downgrade_to:type_name -> routeiq.v1.telemetry.AutonomyMode
	6, // 2: routeiq.v1.control.TriggerInterventionResponse.applied_at:type_name -> google.protobuf.Timestamp
	0, // 3: routeiq.v1.control.GetInterventionStatusResponse.kind:type_name -> routeiq.v1.control.InterventionKind
	1, // 4: routeiq.v1.control.InterventionService.TriggerIntervention:input_type -> routeiq.v1.control.TriggerInterventionRequest
	3, // 5: routeiq.v1.control.InterventionService.GetInterventionStatus:input_type -> routeiq.v1.control.GetInterventionStatusRequest
	2, // 6: routeiq.v1.control.InterventionService.TriggerIntervention:output_type -> routeiq.v1.control.TriggerInterventionResponse
	4, // 7: routeiq.v1.control.InterventionService.GetInterventionStatus:output_type -> routeiq.v1.control.GetInterventionStatusResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_routeiq_v1_control_intervention_proto_init() }
func file_routeiq_v1_control_intervention_proto_init() {
	if File_routeiq_v1_control_intervention_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_routeiq_v1_control_intervention_proto_rawDesc), len(file_routeiq_v1_control_intervention_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_routeiq_v1_control_intervention_proto_goTypes,
		DependencyIndexes: file_routeiq_v1_control_intervention_proto_depIdxs,
		EnumInfos:         file_routeiq_v1_control_intervention_proto_enumTypes,
		MessageInfos:      file_routeiq_v1_control_intervention_proto_msgTypes,
	}.Build()
	File_routeiq_v1_control_intervention_proto = out.File
	file_routeiq_v1_control_intervention_proto_goTypes = nil
	file_routeiq_v1_control_intervention_proto_depIdxs = nil
}
