// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: routeiq/v1/control/session.proto

package controlv1

import (
	telemetry "buf.build/gen/go/ssforge/routeiq/protocolbuffers/go/routeiq/v1/telemetry"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Environment   string                 `protobuf:"bytes,4,opt,name=environment,proto3" json:"environment,omitempty"`
	AutonomyMode  telemetry.AutonomyMode `protobuf:"varint,5,opt,name=autonomy_mode,json=autonomyMode,proto3,enum=routeiq.v1.telemetry.AutonomyMode" json:"autonomy_mode,omitempty"`
	RiskTier      telemetry.RiskTier     `protobuf:"varint,6,opt,name=risk_tier,json=riskTier,proto3,enum=routeiq.v1.telemetry.RiskTier" json:"risk_tier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSessionRequest) Reset() {
	*x = StartSessionRequest{}
	mi := &file_routeiq_v1_control_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSessionRequest) ProtoMessage() {}

func (x *StartSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_control_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSessionRequest.ProtoReflect.Descriptor instead.
func (*StartSessionRequest) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_control_session_proto_rawDescGZIP(), []int{0}
}

func (x *StartSessionRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *StartSessionRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *StartSessionRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *StartSessionRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *StartSessionRequest) GetAutonomyMode() telemetry.AutonomyMode {
	if x != nil {
		return x.AutonomyMode
	}
	return telemetry.AutonomyMode(0)
}

func (x *StartSessionRequest) GetRiskTier() telemetry.RiskTier {
	if x != nil {
		return x.RiskTier
	}
	return telemetry.RiskTier(0)
}

type StartSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSessionResponse) Reset() {
	*x = StartSessionResponse{}
	mi := &file_routeiq_v1_control_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSessionResponse) ProtoMessage() {}

func (x *StartSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_control_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSessionResponse.ProtoReflect.Descriptor instead.
func (*StartSessionResponse) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_control_session_proto_rawDescGZIP(), []int{1}
}

func (x *StartSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StartSessionResponse) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

type EndSessionRequest struct {
	state            protoimpl.MessageState     `protogen:"open.v1"`
	SessionId        string                     `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	CompletionStatus telemetry.CompletionStatus `protobuf:"varint,2,opt,name=completion_status,json=completionStatus,proto3,enum=routeiq.v1.telemetry.CompletionStatus" json:"completion_status,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EndSessionRequest) Reset() {
	*x = EndSessionRequest{}
	mi := &file_routeiq_v1_control_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndSessionRequest) ProtoMessage() {}

func (x *EndSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_control_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndSessionRequest.ProtoReflect.Descriptor instead.
func (*EndSessionRequest) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_control_session_proto_rawDescGZIP(), []int{2}
}

func (x *EndSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *EndSessionRequest) GetCompletionStatus() telemetry.CompletionStatus {
	if x != nil {
		return x.CompletionStatus
	}
	return telemetry.CompletionStatus(0)
}

type EndSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndSessionResponse) Reset() {
	*x = EndSessionResponse{}
	mi := &file_routeiq_v1_control_session_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndSessionResponse) ProtoMessage() {}

func (x *EndSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_control_session_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndSessionResponse.ProtoReflect.Descriptor instead.
func (*EndSessionResponse) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_control_session_proto_rawDescGZIP(), []int{3}
}

func (x *EndSessionResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type UpdateStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	StateKey      string                 `protobuf:"bytes,2,opt,name=state_key,json=stateKey,proto3" json:"state_key,omitempty"`
	StateValue    []byte                 `protobuf:"bytes,3,opt,name=state_value,json=stateValue,proto3" json:"state_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStateRequest) Reset() {
	*x = UpdateStateRequest{}
	mi := &file_routeiq_v1_control_session_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStateRequest) ProtoMessage() {}

func (x *UpdateStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_control_session_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStateRequest.ProtoReflect.Descriptor instead.
func (*UpdateStateRequest) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_control_session_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateStateRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *UpdateStateRequest) GetStateKey() string {
	if x != nil {
		return x.StateKey
	}
	return ""
}

func (x *UpdateStateRequest) GetStateValue() []byte {
	if x != nil {
		return x.StateValue
	}
	return nil
}

type UpdateStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	StateVersion  string                 `protobuf:"bytes,2,opt,name=state_version,json=stateVersion,proto3" json:"state_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStateResponse) Reset() {
	*x = UpdateStateResponse{}
	mi := &file_routeiq_v1_control_session_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStateResponse) ProtoMessage() {}

func (x *UpdateStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_control_session_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStateResponse.ProtoReflect.Descriptor instead.
func (*UpdateStateResponse) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_control_session_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateStateResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *UpdateStateResponse) GetStateVersion() string {
	if x != nil {
		return x.StateVersion
	}
	return ""
}

var File_routeiq_v1_control_session_proto protoreflect.FileDescriptor

const file_routeiq_v1_control_session_proto_rawDesc = "" +
	"\n" +
	" routeiq/v1/control/session.proto\x12\x12routeiq.v1.control\x1a\x1fgoogle/protobuf/timestamp.proto\x1a#routeiq/v1/telemetry/entities.proto\"\x8e\x02\n" +
	"\x13StartSessionRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12 \n" +
	"\venvironment\x18\x04 \x01(\tR\venvironment\x12G\n" +
	"\rautonomy_mode\x18\x05 \x01(\x0e2\".routeiq.v1.telemetry.AutonomyModeR\fautonomyMode\x12;\n" +
	"\trisk_tier\x18\x06 \x01(\x0e2\x1e.routeiq.v1.telemetry.RiskTierR\briskTier\"p\n" +
	"\x14StartSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x129\n" +
	"\n" +
	"started_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\"\x87\x01\n" +
	"\x11EndSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12S\n" +
	"\x11completion_status\x18\x02 \x01(\x0e2&.routeiq.v1.telemetry.CompletionStatusR\x10completionStatus\"0\n" +
	"\x12EndSessionResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"q\n" +
	"\x12UpdateStateRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tstate_key\x18\x02 \x01(\tR\bstateKey\x12\x1f\n" +
	"\vstate_value\x18\x03 \x01(\fR\n" +
	"stateValue\"V\n" +
	"\x13UpdateStateResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12#\n" +
	"\rstate_version\x18\x02 \x01(\tR\fstateVersion2\xb0\x02\n" +
	"\x0eSessionService\x12a\n" +
	"\fStartSession\x12'.routeiq.v1.control.StartSessionRequest\x1a(.routeiq.v1.control.StartSessionResponse\x12[\n" +
	"\n" +
	"EndSession\x12%.routeiq.v1.control.EndSessionRequest\x1a&.routeiq.v1.control.EndSessionResponse\x12^\n" +
	"\vUpdateState\x12&.routeiq.v1.control.UpdateStateRequest\x1a'.routeiq.v1.control.UpdateStateResponseB\x92\x01\n" +
	"0build.buf.gen.ssforge.routeiq.routeiq.v1.controlB\fSessionProtoZPbuf.build/gen/go/ssforge/routeiq/protocolbuffers/go/routeiq/v1/control;controlv1b\x06proto3"

var (
	file_routeiq_v1_control_session_proto_rawDescOnce sync.Once
	file_routeiq_v1_control_session_proto_rawDescData []byte
)

func file_routeiq_v1_control_session_proto_rawDescGZIP() []byte {
	file_routeiq_v1_control_session_proto_rawDescOnce.Do(func() {
		file_routeiq_v1_control_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_routeiq_v1_control_session_proto_rawDesc), len(file_routeiq_v1_control_session_proto_rawDesc)))
	})
	return file_routeiq_v1_control_session_proto_rawDescData
}

var file_routeiq_v1_control_session_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_routeiq_v1_control_session_proto_goTypes = []any{
	(*StartSessionRequest)(nil),     // 0: routeiq.v1.control.StartSessionRequest
	(*StartSessionResponse)(nil),    // 1: routeiq.v1.control.StartSessionResponse
	(*EndSessionRequest)(nil),       // 2: routeiq.v1.control.EndSessionRequest
	(*EndSessionResponse)(nil),      // 3: routeiq.v1.control.EndSessionResponse
	(*UpdateStateRequest)(nil),      // 4: routeiq.v1.control.UpdateStateRequest
	(*UpdateStateResponse)(nil),     // 5: routeiq.v1.control.UpdateStateResponse
	(telemetry.AutonomyMode)(0),     // 6: routeiq.v1.telemetry.AutonomyMode
	(telemetry.RiskTier)(0),         // 7: routeiq.v1.telemetry.RiskTier
	(*timestamppb.Timestamp)(nil),   // 8: google.protobuf.Timestamp
	(telemetry.CompletionStatus)(0), // 9: routeiq.v1.telemetry.CompletionStatus
}
var file_routeiq_v1_control_session_proto_depIdxs = []int32{
	6, // 0: routeiq.v1.control.StartSessionRequest.autonomy_mode:type_name -> routeiq.v1.telemetry.AutonomyMode
	7, // 1: routeiq.v1.control.StartSessionRequest.risk_tier:type_name -> routeiq.v1.telemetry.RiskTier
	8, // 2: routeiq.v1.control.StartSessionResponse.started_at:type_name -> google.protobuf.Timestamp
	9, // 3: routeiq.v1.control.EndSessionRequest.completion_status:type_name -> routeiq.v1.telemetry.CompletionStatus
	0, // 4: routeiq.v1.control.SessionService.StartSession:input_type -> routeiq.v1.control.StartSessionRequest
	2, // 5: routeiq.v1.control.SessionService.EndSession:input_type -> routeiq.v1.control.EndSessionRequest
	4, // 6: routeiq.v1.control.SessionService.UpdateState:input_type -> routeiq.v1.control.UpdateStateRequest
	1, // 7: routeiq.v1.control.SessionService.StartSession:output_type -> routeiq.v1.control.StartSessionResponse
	3, // 8: routeiq.v1.control.SessionService.EndSession:output_type -> routeiq.v1.control.EndSessionResponse
	5, // 9: routeiq.v1.control.SessionService.UpdateState:output_type -> routeiq.v1.control.UpdateStateResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_routeiq_v1_control_session_proto_init() }
func file_routeiq_v1_control_session_proto_init() {
	if File_routeiq_v1_control_session_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_routeiq_v1_control_session_proto_rawDesc), len(file_routeiq_v1_control_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_routeiq_v1_control_session_proto_goTypes,
		DependencyIndexes: file_routeiq_v1_control_session_proto_depIdxs,
		MessageInfos:      file_routeiq_v1_control_session_proto_msgTypes,
	}.Build()
	File_routeiq_v1_control_session_proto = out.File
	file_routeiq_v1_control_session_proto_goTypes = nil
	file_routeiq_v1_control_session_proto_depIdxs = nil
}
