// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: routeiq/v1/admin/billing.proto

package adminv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UsageSummary struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId     string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	PeriodStart        *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=period_start,json=periodStart,proto3" json:"period_start,omitempty"`
	PeriodEnd          *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=period_end,json=periodEnd,proto3" json:"period_end,omitempty"`
	EventsIngested     int64                  `protobuf:"varint,4,opt,name=events_ingested,json=eventsIngested,proto3" json:"events_ingested,omitempty"`
	MetricsEvaluated   int64                  `protobuf:"varint,5,opt,name=metrics_evaluated,json=metricsEvaluated,proto3" json:"metrics_evaluated,omitempty"`
	FrontierJudgeCalls int64                  `protobuf:"varint,6,opt,name=frontier_judge_calls,json=frontierJudgeCalls,proto3" json:"frontier_judge_calls,omitempty"`
	TotalCostUsd       float64                `protobuf:"fixed64,7,opt,name=total_cost_usd,json=totalCostUsd,proto3" json:"total_cost_usd,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UsageSummary) Reset() {
	*x = UsageSummary{}
	mi := &file_routeiq_v1_admin_billing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageSummary) ProtoMessage() {}

func (x *UsageSummary) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_admin_billing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageSummary.ProtoReflect.Descriptor instead.
func (*UsageSummary) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_admin_billing_proto_rawDescGZIP(), []int{0}
}

func (x *UsageSummary) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *UsageSummary) GetPeriodStart() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodStart
	}
	return nil
}

func (x *UsageSummary) GetPeriodEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodEnd
	}
	return nil
}

func (x *UsageSummary) GetEventsIngested() int64 {
	if x != nil {
		return x.EventsIngested
	}
	return 0
}

func (x *UsageSummary) GetMetricsEvaluated() int64 {
	if x != nil {
		return x.MetricsEvaluated
	}
	return 0
}

func (x *UsageSummary) GetFrontierJudgeCalls() int64 {
	if x != nil {
		return x.FrontierJudgeCalls
	}
	return 0
}

func (x *UsageSummary) GetTotalCostUsd() float64 {
	if x != nil {
		return x.TotalCostUsd
	}
	return 0
}

type Quota struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId        string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Tier                  Tier                   `protobuf:"varint,2,opt,name=tier,proto3,enum=routeiq.v1.admin.Tier" json:"tier,omitempty"`
	EventsPerMonth        int64                  `protobuf:"varint,3,opt,name=events_per_month,json=eventsPerMonth,proto3" json:"events_per_month,omitempty"`
	FrontierCallsPerMonth int64                  `protobuf:"varint,4,opt,name=frontier_calls_per_month,json=frontierCallsPerMonth,proto3" json:"frontier_calls_per_month,omitempty"`
	RetentionDays         int64                  `protobuf:"varint,5,opt,name=retention_days,json=retentionDays,proto3" json:"retention_days,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Quota) Reset() {
	*x = Quota{}
	mi := &file_routeiq_v1_admin_billing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Quota) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quota) ProtoMessage() {}

func (x *Quota) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_admin_billing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quota.ProtoReflect.Descriptor instead.
func (*Quota) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_admin_billing_proto_rawDescGZIP(), []int{1}
}

func (x *Quota) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *Quota) GetTier() Tier {
	if x != nil {
		return x.Tier
	}
	return Tier_TIER_UNSPECIFIED
}

func (x *Quota) GetEventsPerMonth() int64 {
	if x != nil {
		return x.EventsPerMonth
	}
	return 0
}

func (x *Quota) GetFrontierCallsPerMonth() int64 {
	if x != nil {
		return x.FrontierCallsPerMonth
	}
	return 0
}

func (x *Quota) GetRetentionDays() int64 {
	if x != nil {
		return x.RetentionDays
	}
	return 0
}

type GetUsageRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	PeriodStart    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=period_start,json=periodStart,proto3" json:"period_start,omitempty"`
	PeriodEnd      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=period_end,json=periodEnd,proto3" json:"period_end,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetUsageRequest) Reset() {
	*x = GetUsageRequest{}
	mi := &file_routeiq_v1_admin_billing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsageRequest) ProtoMessage() {}

func (x *GetUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_admin_billing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsageRequest.ProtoReflect.Descriptor instead.
func (*GetUsageRequest) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_admin_billing_proto_rawDescGZIP(), []int{2}
}

func (x *GetUsageRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *GetUsageRequest) GetPeriodStart() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodStart
	}
	return nil
}

func (x *GetUsageRequest) GetPeriodEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodEnd
	}
	return nil
}

type GetQuotaRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetQuotaRequest) Reset() {
	*x = GetQuotaRequest{}
	mi := &file_routeiq_v1_admin_billing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuotaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuotaRequest) ProtoMessage() {}

func (x *GetQuotaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_admin_billing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuotaRequest.ProtoReflect.Descriptor instead.
func (*GetQuotaRequest) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_admin_billing_proto_rawDescGZIP(), []int{3}
}

func (x *GetQuotaRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

var File_routeiq_v1_admin_billing_proto protoreflect.FileDescriptor

const file_routeiq_v1_admin_billing_proto_rawDesc = "" +
	"\n" +
	"\x1erouteiq/v1/admin/billing.proto\x12\x10routeiq.v1.admin\x1a\x1fgoogle/protobuf/timestamp.proto\x1a#routeiq/v1/admin/organization.proto\"\xdf\x02\n" +
	"\fUsageSummary\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12=\n" +
	"\fperiod_start\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vperiodStart\x129\n" +
	"\n" +
	"period_end\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tperiodEnd\x12'\n" +
	"\x0fevents_ingested\x18\x04 \x01(\x03R\x0eeventsIngested\x12+\n" +
	"\x11metrics_evaluated\x18\x05 \x01(\x03R\x10metricsEvaluated\x120\n" +
	"\x14frontier_judge_calls\x18\x06 \x01(\x03R\x12frontierJudgeCalls\x12$\n" +
	"\x0etotal_cost_usd\x18\a \x01(\x01R\ftotalCostUsd\"\xe6\x01\n" +
	"\x05Quota\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12*\n" +
	"\x04tier\x18\x02 \x01(\x0e2\x16.routeiq.v1.admin.TierR\x04tier\x12(\n" +
	"\x10events_per_month\x18\x03 \x01(\x03R\x0eeventsPerMonth\x127\n" +
	"\x18frontier_calls_per_month\x18\x04 \x01(\x03R\x15frontierCallsPerMonth\x12%\n" +
	"\x0eretention_days\x18\x05 \x01(\x03R\rretentionDays\"\xb4\x01\n" +
	"\x0fGetUsageRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12=\n" +
	"\fperiod_start\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vperiodStart\x129\n" +
	"\n" +
	"period_end\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tperiodEnd\":\n" +
	"\x0fGetQuotaRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId2\xa7\x01\n" +
	"\x0eBillingService\x12M\n" +
	"\bGetUsage\x12!.routeiq.v1.admin.GetUsageRequest\x1a\x1e.routeiq.v1.admin.UsageSummary\x12F\n" +
	"\bGetQuota\x12!.routeiq.v1.admin.GetQuotaRequest\x1a\x17.routeiq.v1.admin.QuotaB\x8c\x01\n" +
	".build.buf.gen.ssforge.routeiq.routeiq.v1.adminB\fBillingProtoZLbuf.build/gen/go/ssforge/routeiq/protocolbuffers/go/routeiq/v1/admin;adminv1b\x06proto3"

var (
	file_routeiq_v1_admin_billing_proto_rawDescOnce sync.Once
	file_routeiq_v1_admin_billing_proto_rawDescData []byte
)

func file_routeiq_v1_admin_billing_proto_rawDescGZIP() []byte {
	file_routeiq_v1_admin_billing_proto_rawDescOnce.Do(func() {
		file_routeiq_v1_admin_billing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_routeiq_v1_admin_billing_proto_rawDesc), len(file_routeiq_v1_admin_billing_proto_rawDesc)))
	})
	return file_routeiq_v1_admin_billing_proto_rawDescData
}

var file_routeiq_v1_admin_billing_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_routeiq_v1_admin_billing_proto_goTypes = []any{
	(*UsageSummary)(nil),          // 0: routeiq.v1.admin.UsageSummary
	(*Quota)(nil),                 // 1: routeiq.v1.admin.Quota
	(*GetUsageRequest)(nil),       // 2: routeiq.v1.admin.GetUsageRequest
	(*GetQuotaRequest)(nil),       // 3: routeiq.v1.admin.GetQuotaRequest
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
	(Tier)(0),                     // 5: routeiq.v1.admin.Tier
}
var file_routeiq_v1_admin_billing_proto_depIdxs = []int32{
	4, // 0: routeiq.v1.admin.UsageSummary.period_start:type_name -> google.protobuf.Timestamp
	4, // 1: routeiq.v1.admin.UsageSummary.period_end:type_name -> google.protobuf.Timestamp
	5, // 2: routeiq.v1.admin.Quota.tier:type_name -> routeiq.v1.admin.Tier
	4, // 3: routeiq.v1.admin.GetUsageRequest.period_start:type_name -> google.protobuf.Timestamp
	4, // 4: routeiq.v1.admin.GetUsageRequest.period_end:type_name -> google.protobuf.Timestamp
	2, // 5: routeiq.v1.admin.BillingService.GetUsage:input_type -> routeiq.v1.admin.GetUsageRequest
	3, // 6: routeiq.v1.admin.BillingService.GetQuota:input_type -> routeiq.v1.admin.GetQuotaRequest
	0, // 7: routeiq.v1.admin.BillingService.GetUsage:output_type -> routeiq.v1.admin.UsageSummary
	1, // 8: routeiq.v1.admin.BillingService.GetQuota:output_type -> routeiq.v1.admin.Quota
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_routeiq_v1_admin_billing_proto_init() }
func file_routeiq_v1_admin_billing_proto_init() {
	if File_routeiq_v1_admin_billing_proto != nil {
		return
	}
	file_routeiq_v1_admin_organization_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_routeiq_v1_admin_billing_proto_rawDesc), len(file_routeiq_v1_admin_billing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_routeiq_v1_admin_billing_proto_goTypes,
		DependencyIndexes: file_routeiq_v1_admin_billing_proto_depIdxs,
		MessageInfos:      file_routeiq_v1_admin_billing_proto_msgTypes,
	}.Build()
	File_routeiq_v1_admin_billing_proto = out.File
	file_routeiq_v1_admin_billing_proto_goTypes = nil
	file_routeiq_v1_admin_billing_proto_depIdxs = nil
}
