// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: routeiq/v1/admin/identity.proto

package adminv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Role int32

const (
	Role_ROLE_UNSPECIFIED Role = 0
	Role_VIEWER           Role = 1
	Role_ANALYST          Role = 2
	Role_ADMIN            Role = 3
	Role_OWNER            Role = 4
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "ROLE_UNSPECIFIED",
		1: "VIEWER",
		2: "ANALYST",
		3: "ADMIN",
		4: "OWNER",
	}
	Role_value = map[string]int32{
		"ROLE_UNSPECIFIED": 0,
		"VIEWER":           1,
		"ANALYST":          2,
		"ADMIN":            3,
		"OWNER":            4,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_routeiq_v1_admin_identity_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_routeiq_v1_admin_identity_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_routeiq_v1_admin_identity_proto_rawDescGZIP(), []int{0}
}

type AuthProvider int32

const (
	AuthProvider_AUTH_PROVIDER_UNSPECIFIED AuthProvider = 0
	AuthProvider_GOOGLE                    AuthProvider = 1
	AuthProvider_GITHUB                    AuthProvider = 2
	AuthProvider_SAML                      AuthProvider = 3
)

// Enum value maps for AuthProvider.
var (
	AuthProvider_name = map[int32]string{
		0: "AUTH_PROVIDER_UNSPECIFIED",
		1: "GOOGLE",
		2: "GITHUB",
		3: "SAML",
	}
	AuthProvider_value = map[string]int32{
		"AUTH_PROVIDER_UNSPECIFIED": 0,
		"GOOGLE":                    1,
		"GITHUB":                    2,
		"SAML":                      3,
	}
)

func (x AuthProvider) Enum() *AuthProvider {
	p := new(AuthProvider)
	*p = x
	return p
}

func (x AuthProvider) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthProvider) Descriptor() protoreflect.EnumDescriptor {
	return file_routeiq_v1_admin_identity_proto_enumTypes[1].Descriptor()
}

func (AuthProvider) Type() protoreflect.EnumType {
	return &file_routeiq_v1_admin_identity_proto_enumTypes[1]
}

func (x AuthProvider) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthProvider.Descriptor instead.
func (AuthProvider) EnumDescriptor() ([]byte, []int) {
	return file_routeiq_v1_admin_identity_proto_rawDescGZIP(), []int{1}
}

type ApiKeyScope int32

const (
	ApiKeyScope_API_KEY_SCOPE_UNSPECIFIED ApiKeyScope = 0
	ApiKeyScope_INGEST_ONLY               ApiKeyScope = 1
	ApiKeyScope_INGEST_AND_CONTROL        ApiKeyScope = 2
	ApiKeyScope_ADMIN_SCOPE               ApiKeyScope = 3
)

// Enum value maps for ApiKeyScope.
var (
	ApiKeyScope_name = map[int32]string{
		0: "API_KEY_SCOPE_UNSPECIFIED",
		1: "INGEST_ONLY",
		2: "INGEST_AND_CONTROL",
		3: "ADMIN_SCOPE",
	}
	ApiKeyScope_value = map[string]int32{
		"API_KEY_SCOPE_UNSPECIFIED": 0,
		"INGEST_ONLY":               1,
		"INGEST_AND_CONTROL":        2,
		"ADMIN_SCOPE":               3,
	}
)

func (x ApiKeyScope) Enum() *ApiKeyScope {
	p := new(ApiKeyScope)
	*p = x
	return p
}

func (x ApiKeyScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApiKeyScope) Descriptor() protoreflect.EnumDescriptor {
	return file_routeiq_v1_admin_identity_proto_enumTypes[2].Descriptor()
}

func (ApiKeyScope) Type() protoreflect.EnumType {
	return &file_routeiq_v1_admin_identity_proto_enumTypes[2]
}

func (x ApiKeyScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApiKeyScope.Descriptor instead.
func (ApiKeyScope) EnumDescriptor() ([]byte, []int) {
	return file_routeiq_v1_admin_identity_proto_rawDescGZIP(), []int{2}
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	AuthProvider  AuthProvider           `protobuf:"varint,4,opt,name=auth_provider,json=authProvider,proto3,enum=routeiq.v1.admin.AuthProvider" json:"auth_provider,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_routeiq_v1_admin_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_admin_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_admin_identity_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *User) GetAuthProvider() AuthProvider {
	if x != nil {
		return x.AuthProvider
	}
	return AuthProvider_AUTH_PROVIDER_UNSPECIFIED
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type RoleAssignment struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Role           Role                   `protobuf:"varint,3,opt,name=role,proto3,enum=routeiq.v1.admin.Role" json:"role,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RoleAssignment) Reset() {
	*x = RoleAssignment{}
	mi := &file_routeiq_v1_admin_identity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleAssignment) ProtoMessage() {}

func (x *RoleAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_admin_identity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleAssignment.ProtoReflect.Descriptor instead.
func (*RoleAssignment) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_admin_identity_proto_rawDescGZIP(), []int{1}
}

func (x *RoleAssignment) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RoleAssignment) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *RoleAssignment) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_UNSPECIFIED
}

type ApiKey struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	WorkspaceId    string                 `protobuf:"bytes,3,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Prefix         string                 `protobuf:"bytes,4,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Scope          ApiKeyScope            `protobuf:"varint,5,opt,name=scope,proto3,enum=routeiq.v1.admin.ApiKeyScope" json:"scope,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ApiKey) Reset() {
	*x = ApiKey{}
	mi := &file_routeiq_v1_admin_identity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiKey) ProtoMessage() {}

func (x *ApiKey) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_admin_identity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiKey.ProtoReflect.Descriptor instead.
func (*ApiKey) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_admin_identity_proto_rawDescGZIP(), []int{2}
}

func (x *ApiKey) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ApiKey) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *ApiKey) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *ApiKey) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *ApiKey) GetScope() ApiKeyScope {
	if x != nil {
		return x.Scope
	}
	return ApiKeyScope_API_KEY_SCOPE_UNSPECIFIED
}

func (x *ApiKey) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ApiKey) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type InviteUserRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Email          string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Role           Role                   `protobuf:"varint,3,opt,name=role,proto3,enum=routeiq.v1.admin.Role" json:"role,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InviteUserRequest) Reset() {
	*x = InviteUserRequest{}
	mi := &file_routeiq_v1_admin_identity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteUserRequest) ProtoMessage() {}

func (x *InviteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_admin_identity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteUserRequest.ProtoReflect.Descriptor instead.
func (*InviteUserRequest) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_admin_identity_proto_rawDescGZIP(), []int{3}
}

func (x *InviteUserRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *InviteUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *InviteUserRequest) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_UNSPECIFIED
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_routeiq_v1_admin_identity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_admin_identity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_admin_identity_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AssignRoleRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Role           Role                   `protobuf:"varint,3,opt,name=role,proto3,enum=routeiq.v1.admin.Role" json:"role,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AssignRoleRequest) Reset() {
	*x = AssignRoleRequest{}
	mi := &file_routeiq_v1_admin_identity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRoleRequest) ProtoMessage() {}

func (x *AssignRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_admin_identity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRoleRequest.ProtoReflect.Descriptor instead.
func (*AssignRoleRequest) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_admin_identity_proto_rawDescGZIP(), []int{5}
}

func (x *AssignRoleRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AssignRoleRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *AssignRoleRequest) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_UNSPECIFIED
}

type CreateApiKeyRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	WorkspaceId    string                 `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Scope          ApiKeyScope            `protobuf:"varint,3,opt,name=scope,proto3,enum=routeiq.v1.admin.ApiKeyScope" json:"scope,omitempty"`
	ExpiresAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateApiKeyRequest) Reset() {
	*x = CreateApiKeyRequest{}
	mi := &file_routeiq_v1_admin_identity_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateApiKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateApiKeyRequest) ProtoMessage() {}

func (x *CreateApiKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_admin_identity_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateApiKeyRequest.ProtoReflect.Descriptor instead.
func (*CreateApiKeyRequest) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_admin_identity_proto_rawDescGZIP(), []int{6}
}

func (x *CreateApiKeyRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *CreateApiKeyRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *CreateApiKeyRequest) GetScope() ApiKeyScope {
	if x != nil {
		return x.Scope
	}
	return ApiKeyScope_API_KEY_SCOPE_UNSPECIFIED
}

func (x *CreateApiKeyRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type RevokeApiKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeApiKeyRequest) Reset() {
	*x = RevokeApiKeyRequest{}
	mi := &file_routeiq_v1_admin_identity_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeApiKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeApiKeyRequest) ProtoMessage() {}

func (x *RevokeApiKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_admin_identity_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeApiKeyRequest.ProtoReflect.Descriptor instead.
func (*RevokeApiKeyRequest) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_admin_identity_proto_rawDescGZIP(), []int{7}
}

func (x *RevokeApiKeyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListApiKeysRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	WorkspaceId    string                 `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListApiKeysRequest) Reset() {
	*x = ListApiKeysRequest{}
	mi := &file_routeiq_v1_admin_identity_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListApiKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListApiKeysRequest) ProtoMessage() {}

func (x *ListApiKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_admin_identity_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListApiKeysRequest.ProtoReflect.Descriptor instead.
func (*ListApiKeysRequest) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_admin_identity_proto_rawDescGZIP(), []int{8}
}

func (x *ListApiKeysRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *ListApiKeysRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

type ListApiKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKeys       []*ApiKey              `protobuf:"bytes,1,rep,name=api_keys,json=apiKeys,proto3" json:"api_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListApiKeysResponse) Reset() {
	*x = ListApiKeysResponse{}
	mi := &file_routeiq_v1_admin_identity_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListApiKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListApiKeysResponse) ProtoMessage() {}

func (x *ListApiKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_admin_identity_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListApiKeysResponse.ProtoReflect.Descriptor instead.
func (*ListApiKeysResponse) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_admin_identity_proto_rawDescGZIP(), []int{9}
}

func (x *ListApiKeysResponse) GetApiKeys() []*ApiKey {
	if x != nil {
		return x.ApiKeys
	}
	return nil
}

var File_routeiq_v1_admin_identity_proto protoreflect.FileDescriptor

const file_routeiq_v1_admin_identity_proto_rawDesc = "" +
	"\n" +
	"\x1frouteiq/v1/admin/identity.proto\x12\x10routeiq.v1.admin\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcf\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12C\n" +
	"\rauth_provider\x18\x04 \x01(\x0e2\x1e.routeiq.v1.admin.AuthProviderR\fauthProvider\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"~\n" +
	"\x0eRoleAssignment\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12*\n" +
	"\x04role\x18\x03 \x01(\x0e2\x16.routeiq.v1.admin.RoleR\x04role\"\xa7\x02\n" +
	"\x06ApiKey\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12!\n" +
	"\fworkspace_id\x18\x03 \x01(\tR\vworkspaceId\x12\x16\n" +
	"\x06prefix\x18\x04 \x01(\tR\x06prefix\x123\n" +
	"\x05scope\x18\x05 \x01(\x0e2\x1d.routeiq.v1.admin.ApiKeyScopeR\x05scope\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"expires_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"~\n" +
	"\x11InviteUserRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12*\n" +
	"\x04role\x18\x03 \x01(\x0e2\x16.routeiq.v1.admin.RoleR\x04role\" \n" +
	"\x0eGetUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x81\x01\n" +
	"\x11AssignRoleRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12*\n" +
	"\x04role\x18\x03 \x01(\x0e2\x16.routeiq.v1.admin.RoleR\x04role\"\xd1\x01\n" +
	"\x13CreateApiKeyRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12!\n" +
	"\fworkspace_id\x18\x02 \x01(\tR\vworkspaceId\x123\n" +
	"\x05scope\x18\x03 \x01(\x0e2\x1d.routeiq.v1.admin.ApiKeyScopeR\x05scope\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"%\n" +
	"\x13RevokeApiKeyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"`\n" +
	"\x12ListApiKeysRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12!\n" +
	"\fworkspace_id\x18\x02 \x01(\tR\vworkspaceId\"J\n" +
	"\x13ListApiKeysResponse\x123\n" +
	"\bapi_keys\x18\x01 \x03(\v2\x18.routeiq.v1.admin.ApiKeyR\aapiKeys*K\n" +
	"\x04Role\x12\x14\n" +
	"\x10ROLE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06VIEWER\x10\x01\x12\v\n" +
	"\aANALYST\x10\x02\x12\t\n" +
	"\x05ADMIN\x10\x03\x12\t\n" +
	"\x05OWNER\x10\x04*O\n" +
	"\fAuthProvider\x12\x1d\n" +
	"\x19AUTH_PROVIDER_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06GOOGLE\x10\x01\x12\n" +
	"\n" +
	"\x06GITHUB\x10\x02\x12\b\n" +
	"\x04SAML\x10\x03*f\n" +
	"\vApiKeyScope\x12\x1d\n" +
	"\x19API_KEY_SCOPE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vINGEST_ONLY\x10\x01\x12\x16\n" +
	"\x12INGEST_AND_CONTROL\x10\x02\x12\x0f\n" +
	"\vADMIN_SCOPE\x10\x032\xf2\x03\n" +
	"\x0fIdentityService\x12I\n" +
	"\n" +
	"InviteUser\x12#.routeiq.v1.admin.InviteUserRequest\x1a\x16.routeiq.v1.admin.User\x12C\n" +
	"\aGetUser\x12 .routeiq.v1.admin.GetUserRequest\x1a\x16.routeiq.v1.admin.User\x12S\n" +
	"\n" +
	"AssignRole\x12#.routeiq.v1.admin.AssignRoleRequest\x1a .routeiq.v1.admin.RoleAssignment\x12O\n" +
	"\fCreateApiKey\x12%.routeiq.v1.admin.CreateApiKeyRequest\x1a\x18.routeiq.v1.admin.ApiKey\x12M\n" +
	"\fRevokeApiKey\x12%.routeiq.v1.admin.RevokeApiKeyRequest\x1a\x16.google.protobuf.Empty\x12Z\n" +
	"\vListApiKeys\x12$.routeiq.v1.admin.ListApiKeysRequest\x1a%.routeiq.v1.admin.ListApiKeysResponseB\x8d\x01\n" +
	".build.buf.gen.ssforge.routeiq.routeiq.v1.adminB\rIdentityProtoZLbuf.build/gen/go/ssforge/routeiq/protocolbuffers/go/routeiq/v1/admin;adminv1b\x06proto3"

var (
	file_routeiq_v1_admin_identity_proto_rawDescOnce sync.Once
	file_routeiq_v1_admin_identity_proto_rawDescData []byte
)

func file_routeiq_v1_admin_identity_proto_rawDescGZIP() []byte {
	file_routeiq_v1_admin_identity_proto_rawDescOnce.Do(func() {
		file_routeiq_v1_admin_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_routeiq_v1_admin_identity_proto_rawDesc), len(file_routeiq_v1_admin_identity_proto_rawDesc)))
	})
	return file_routeiq_v1_admin_identity_proto_rawDescData
}

var file_routeiq_v1_admin_identity_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_routeiq_v1_admin_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_routeiq_v1_admin_identity_proto_goTypes = []any{
	(Role)(0),                     // 0: routeiq.v1.admin.Role
	(AuthProvider)(0),             // 1: routeiq.v1.admin.AuthProvider
	(ApiKeyScope)(0),              // 2: routeiq.v1.admin.ApiKeyScope
	(*User)(nil),                  // 3: routeiq.v1.admin.User
	(*RoleAssignment)(nil),        // 4: routeiq.v1.admin.RoleAssignment
	(*ApiKey)(nil),                // 5: routeiq.v1.admin.ApiKey
	(*InviteUserRequest)(nil),     // 6: routeiq.v1.admin.InviteUserRequest
	(*GetUserRequest)(nil),        // 7: routeiq.v1.admin.GetUserRequest
	(*AssignRoleRequest)(nil),     // 8: routeiq.v1.admin.AssignRoleRequest
	(*CreateApiKeyRequest)(nil),   // 9: routeiq.v1.admin.CreateApiKeyRequest
	(*RevokeApiKeyRequest)(nil),   // 10: routeiq.v1.admin.RevokeApiKeyRequest
	(*ListApiKeysRequest)(nil),    // 11: routeiq.v1.admin.ListApiKeysRequest
	(*ListApiKeysResponse)(nil),   // 12: routeiq.v1.admin.ListApiKeysResponse
	(*timestamppb.Timestamp)(nil), // 13: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 14: google.protobuf.Empty
}
var file_routeiq_v1_admin_identity_proto_depIdxs = []int32{
	1,  // 0: routeiq.v1.admin.User.auth_provider:type_name -> routeiq.v1.admin.AuthProvider
	13, // 1: routeiq.v1.admin.User.created_at:type_name -> google.protobuf.Timestamp
	0,  // 2: routeiq.v1.admin.RoleAssignment.role:type_name -> routeiq.v1.admin.Role
	2,  // 3: routeiq.v1.admin.ApiKey.scope:type_name -> routeiq.v1.admin.ApiKeyScope
	13, // 4: routeiq.v1.admin.ApiKey.created_at:type_name -> google.protobuf.Timestamp
	13, // 5: routeiq.v1.admin.ApiKey.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 6: routeiq.v1.admin.InviteUserRequest.role:type_name -> routeiq.v1.admin.Role
	0,  // 7: routeiq.v1.admin.AssignRoleRequest.role:type_name -> routeiq.v1.admin.Role
	2,  // 8: routeiq.v1.admin.CreateApiKeyRequest.scope:type_name -> routeiq.v1.admin.ApiKeyScope
	13, // 9: routeiq.v1.admin.CreateApiKeyRequest.expires_at:type_name -> google.protobuf.Timestamp
	5,  // 10: routeiq.v1.admin.ListApiKeysResponse.api_keys:type_name -> routeiq.v1.admin.ApiKey
	6,  // 11: routeiq.v1.admin.IdentityService.InviteUser:input_type -> routeiq.v1.admin.InviteUserRequest
	7,  // 12: routeiq.v1.admin.IdentityService.GetUser:input_type -> routeiq.v1.admin.GetUserRequest
	8,  // 13: routeiq.v1.admin.IdentityService.AssignRole:input_type -> routeiq.v1.admin.AssignRoleRequest
	9,  // 14: routeiq.v1.admin.IdentityService.CreateApiKey:input_type -> routeiq.v1.admin.CreateApiKeyRequest
	10, // 15: routeiq.v1.admin.IdentityService.RevokeApiKey:input_type -> routeiq.v1.admin.RevokeApiKeyRequest
	11, // 16: routeiq.v1.admin.IdentityService.ListApiKeys:input_type -> routeiq.v1.admin.ListApiKeysRequest
	3,  // 17: routeiq.v1.admin.IdentityService.InviteUser:output_type -> routeiq.v1.admin.User
	3,  // 18: routeiq.v1.admin.IdentityService.GetUser:output_type -> routeiq.v1.admin.User
	4,  // 19: routeiq.v1.admin.IdentityService.AssignRole:output_type -> routeiq.v1.admin.RoleAssignment
	5,  // 20: routeiq.v1.admin.IdentityService.CreateApiKey:output_type -> routeiq.v1.admin.ApiKey
	14, // 21: routeiq.v1.admin.IdentityService.RevokeApiKey:output_type -> google.protobuf.Empty
	12, // 22: routeiq.v1.admin.IdentityService.ListApiKeys:output_type -> routeiq.v1.admin.ListApiKeysResponse
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_routeiq_v1_admin_identity_proto_init() }
func file_routeiq_v1_admin_identity_proto_init() {
	if File_routeiq_v1_admin_identity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_routeiq_v1_admin_identity_proto_rawDesc), len(file_routeiq_v1_admin_identity_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_routeiq_v1_admin_identity_proto_goTypes,
		DependencyIndexes: file_routeiq_v1_admin_identity_proto_depIdxs,
		EnumInfos:         file_routeiq_v1_admin_identity_proto_enumTypes,
		MessageInfos:      file_routeiq_v1_admin_identity_proto_msgTypes,
	}.Build()
	File_routeiq_v1_admin_identity_proto = out.File
	file_routeiq_v1_admin_identity_proto_goTypes = nil
	file_routeiq_v1_admin_identity_proto_depIdxs = nil
}
