// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: routeiq/v1/admin/organization.proto

package adminv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tier int32

const (
	Tier_TIER_UNSPECIFIED Tier = 0
	Tier_FREE             Tier = 1
	Tier_GROWTH           Tier = 2
	Tier_PRO              Tier = 3
	Tier_ENTERPRISE       Tier = 4
)

// Enum value maps for Tier.
var (
	Tier_name = map[int32]string{
		0: "TIER_UNSPECIFIED",
		1: "FREE",
		2: "GROWTH",
		3: "PRO",
		4: "ENTERPRISE",
	}
	Tier_value = map[string]int32{
		"TIER_UNSPECIFIED": 0,
		"FREE":             1,
		"GROWTH":           2,
		"PRO":              3,
		"ENTERPRISE":       4,
	}
)

func (x Tier) Enum() *Tier {
	p := new(Tier)
	*p = x
	return p
}

func (x Tier) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Tier) Descriptor() protoreflect.EnumDescriptor {
	return file_routeiq_v1_admin_organization_proto_enumTypes[0].Descriptor()
}

func (Tier) Type() protoreflect.EnumType {
	return &file_routeiq_v1_admin_organization_proto_enumTypes[0]
}

func (x Tier) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Tier.Descriptor instead.
func (Tier) EnumDescriptor() ([]byte, []int) {
	return file_routeiq_v1_admin_organization_proto_rawDescGZIP(), []int{0}
}

type Region int32

const (
	Region_REGION_UNSPECIFIED Region = 0
	Region_US_EAST_1          Region = 1
	Region_US_WEST_2          Region = 2
	Region_EU_WEST_1          Region = 3
	Region_AP_SOUTHEAST_1     Region = 4
)

// Enum value maps for Region.
var (
	Region_name = map[int32]string{
		0: "REGION_UNSPECIFIED",
		1: "US_EAST_1",
		2: "US_WEST_2",
		3: "EU_WEST_1",
		4: "AP_SOUTHEAST_1",
	}
	Region_value = map[string]int32{
		"REGION_UNSPECIFIED": 0,
		"US_EAST_1":          1,
		"US_WEST_2":          2,
		"EU_WEST_1":          3,
		"AP_SOUTHEAST_1":     4,
	}
)

func (x Region) Enum() *Region {
	p := new(Region)
	*p = x
	return p
}

func (x Region) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Region) Descriptor() protoreflect.EnumDescriptor {
	return file_routeiq_v1_admin_organization_proto_enumTypes[1].Descriptor()
}

func (Region) Type() protoreflect.EnumType {
	return &file_routeiq_v1_admin_organization_proto_enumTypes[1]
}

func (x Region) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Region.Descriptor instead.
func (Region) EnumDescriptor() ([]byte, []int) {
	return file_routeiq_v1_admin_organization_proto_rawDescGZIP(), []int{1}
}

type Organization struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Tier          Tier                   `protobuf:"varint,3,opt,name=tier,proto3,enum=routeiq.v1.admin.Tier" json:"tier,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Workspaces    []*Workspace           `protobuf:"bytes,5,rep,name=workspaces,proto3" json:"workspaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Organization) Reset() {
	*x = Organization{}
	mi := &file_routeiq_v1_admin_organization_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Organization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Organization) ProtoMessage() {}

func (x *Organization) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_admin_organization_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Organization.ProtoReflect.Descriptor instead.
func (*Organization) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_admin_organization_proto_rawDescGZIP(), []int{0}
}

func (x *Organization) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Organization) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Organization) GetTier() Tier {
	if x != nil {
		return x.Tier
	}
	return Tier_TIER_UNSPECIFIED
}

func (x *Organization) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Organization) GetWorkspaces() []*Workspace {
	if x != nil {
		return x.Workspaces
	}
	return nil
}

type Workspace struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Environment    string                 `protobuf:"bytes,4,opt,name=environment,proto3" json:"environment,omitempty"`
	Region         Region                 `protobuf:"varint,5,opt,name=region,proto3,enum=routeiq.v1.admin.Region" json:"region,omitempty"`
	Retention      *RetentionConfig       `protobuf:"bytes,6,opt,name=retention,proto3" json:"retention,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Workspace) Reset() {
	*x = Workspace{}
	mi := &file_routeiq_v1_admin_organization_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workspace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workspace) ProtoMessage() {}

func (x *Workspace) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_admin_organization_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workspace.ProtoReflect.Descriptor instead.
func (*Workspace) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_admin_organization_proto_rawDescGZIP(), []int{1}
}

func (x *Workspace) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Workspace) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *Workspace) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Workspace) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *Workspace) GetRegion() Region {
	if x != nil {
		return x.Region
	}
	return Region_REGION_UNSPECIFIED
}

func (x *Workspace) GetRetention() *RetentionConfig {
	if x != nil {
		return x.Retention
	}
	return nil
}

type RetentionConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HotDays       int32                  `protobuf:"varint,1,opt,name=hot_days,json=hotDays,proto3" json:"hot_days,omitempty"`
	WarmDays      int32                  `protobuf:"varint,2,opt,name=warm_days,json=warmDays,proto3" json:"warm_days,omitempty"`
	ColdDays      int32                  `protobuf:"varint,3,opt,name=cold_days,json=coldDays,proto3" json:"cold_days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetentionConfig) Reset() {
	*x = RetentionConfig{}
	mi := &file_routeiq_v1_admin_organization_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetentionConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetentionConfig) ProtoMessage() {}

func (x *RetentionConfig) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_admin_organization_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetentionConfig.ProtoReflect.Descriptor instead.
func (*RetentionConfig) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_admin_organization_proto_rawDescGZIP(), []int{2}
}

func (x *RetentionConfig) GetHotDays() int32 {
	if x != nil {
		return x.HotDays
	}
	return 0
}

func (x *RetentionConfig) GetWarmDays() int32 {
	if x != nil {
		return x.WarmDays
	}
	return 0
}

func (x *RetentionConfig) GetColdDays() int32 {
	if x != nil {
		return x.ColdDays
	}
	return 0
}

type CreateOrganizationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Tier          Tier                   `protobuf:"varint,2,opt,name=tier,proto3,enum=routeiq.v1.admin.Tier" json:"tier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrganizationRequest) Reset() {
	*x = CreateOrganizationRequest{}
	mi := &file_routeiq_v1_admin_organization_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrganizationRequest) ProtoMessage() {}

func (x *CreateOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_admin_organization_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrganizationRequest.ProtoReflect.Descriptor instead.
func (*CreateOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_admin_organization_proto_rawDescGZIP(), []int{3}
}

func (x *CreateOrganizationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateOrganizationRequest) GetTier() Tier {
	if x != nil {
		return x.Tier
	}
	return Tier_TIER_UNSPECIFIED
}

type GetOrganizationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrganizationRequest) Reset() {
	*x = GetOrganizationRequest{}
	mi := &file_routeiq_v1_admin_organization_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrganizationRequest) ProtoMessage() {}

func (x *GetOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_admin_organization_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrganizationRequest.ProtoReflect.Descriptor instead.
func (*GetOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_admin_organization_proto_rawDescGZIP(), []int{4}
}

func (x *GetOrganizationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListOrganizationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrganizationsRequest) Reset() {
	*x = ListOrganizationsRequest{}
	mi := &file_routeiq_v1_admin_organization_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrganizationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrganizationsRequest) ProtoMessage() {}

func (x *ListOrganizationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_admin_organization_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrganizationsRequest.ProtoReflect.Descriptor instead.
func (*ListOrganizationsRequest) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_admin_organization_proto_rawDescGZIP(), []int{5}
}

func (x *ListOrganizationsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListOrganizationsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListOrganizationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Organizations []*Organization        `protobuf:"bytes,1,rep,name=organizations,proto3" json:"organizations,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrganizationsResponse) Reset() {
	*x = ListOrganizationsResponse{}
	mi := &file_routeiq_v1_admin_organization_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrganizationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrganizationsResponse) ProtoMessage() {}

func (x *ListOrganizationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_admin_organization_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrganizationsResponse.ProtoReflect.Descriptor instead.
func (*ListOrganizationsResponse) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_admin_organization_proto_rawDescGZIP(), []int{6}
}

func (x *ListOrganizationsResponse) GetOrganizations() []*Organization {
	if x != nil {
		return x.Organizations
	}
	return nil
}

func (x *ListOrganizationsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type UpdateOrganizationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Tier          Tier                   `protobuf:"varint,3,opt,name=tier,proto3,enum=routeiq.v1.admin.Tier" json:"tier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrganizationRequest) Reset() {
	*x = UpdateOrganizationRequest{}
	mi := &file_routeiq_v1_admin_organization_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrganizationRequest) ProtoMessage() {}

func (x *UpdateOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_admin_organization_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrganizationRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_admin_organization_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateOrganizationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateOrganizationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateOrganizationRequest) GetTier() Tier {
	if x != nil {
		return x.Tier
	}
	return Tier_TIER_UNSPECIFIED
}

type DeleteOrganizationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOrganizationRequest) Reset() {
	*x = DeleteOrganizationRequest{}
	mi := &file_routeiq_v1_admin_organization_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOrganizationRequest) ProtoMessage() {}

func (x *DeleteOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_admin_organization_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOrganizationRequest.ProtoReflect.Descriptor instead.
func (*DeleteOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_admin_organization_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteOrganizationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateWorkspaceRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Environment    string                 `protobuf:"bytes,3,opt,name=environment,proto3" json:"environment,omitempty"`
	Region         Region                 `protobuf:"varint,4,opt,name=region,proto3,enum=routeiq.v1.admin.Region" json:"region,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateWorkspaceRequest) Reset() {
	*x = CreateWorkspaceRequest{}
	mi := &file_routeiq_v1_admin_organization_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkspaceRequest) ProtoMessage() {}

func (x *CreateWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_admin_organization_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*CreateWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_admin_organization_proto_rawDescGZIP(), []int{9}
}

func (x *CreateWorkspaceRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *CreateWorkspaceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateWorkspaceRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *CreateWorkspaceRequest) GetRegion() Region {
	if x != nil {
		return x.Region
	}
	return Region_REGION_UNSPECIFIED
}

type ListWorkspacesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	PageSize       int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken      string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListWorkspacesRequest) Reset() {
	*x = ListWorkspacesRequest{}
	mi := &file_routeiq_v1_admin_organization_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkspacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkspacesRequest) ProtoMessage() {}

func (x *ListWorkspacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_admin_organization_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkspacesRequest.ProtoReflect.Descriptor instead.
func (*ListWorkspacesRequest) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_admin_organization_proto_rawDescGZIP(), []int{10}
}

func (x *ListWorkspacesRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *ListWorkspacesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListWorkspacesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListWorkspacesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspaces    []*Workspace           `protobuf:"bytes,1,rep,name=workspaces,proto3" json:"workspaces,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkspacesResponse) Reset() {
	*x = ListWorkspacesResponse{}
	mi := &file_routeiq_v1_admin_organization_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkspacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkspacesResponse) ProtoMessage() {}

func (x *ListWorkspacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_admin_organization_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkspacesResponse.ProtoReflect.Descriptor instead.
func (*ListWorkspacesResponse) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_admin_organization_proto_rawDescGZIP(), []int{11}
}

func (x *ListWorkspacesResponse) GetWorkspaces() []*Workspace {
	if x != nil {
		return x.Workspaces
	}
	return nil
}

func (x *ListWorkspacesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type UpdateWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Retention     *RetentionConfig       `protobuf:"bytes,3,opt,name=retention,proto3" json:"retention,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWorkspaceRequest) Reset() {
	*x = UpdateWorkspaceRequest{}
	mi := &file_routeiq_v1_admin_organization_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWorkspaceRequest) ProtoMessage() {}

func (x *UpdateWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_admin_organization_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*UpdateWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_admin_organization_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateWorkspaceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateWorkspaceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateWorkspaceRequest) GetRetention() *RetentionConfig {
	if x != nil {
		return x.Retention
	}
	return nil
}

var File_routeiq_v1_admin_organization_proto protoreflect.FileDescriptor

const file_routeiq_v1_admin_organization_proto_rawDesc = "" +
	"\n" +
	"#routeiq/v1/admin/organization.proto\x12\x10routeiq.v1.admin\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd6\x01\n" +
	"\fOrganization\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12*\n" +
	"\x04tier\x18\x03 \x01(\x0e2\x16.routeiq.v1.admin.TierR\x04tier\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12;\n" +
	"\n" +
	"workspaces\x18\x05 \x03(\v2\x1b.routeiq.v1.admin.WorkspaceR\n" +
	"workspaces\"\xed\x01\n" +
	"\tWorkspace\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\venvironment\x18\x04 \x01(\tR\venvironment\x120\n" +
	"\x06region\x18\x05 \x01(\x0e2\x18.routeiq.v1.admin.RegionR\x06region\x12?\n" +
	"\tretention\x18\x06 \x01(\v2!.routeiq.v1.admin.RetentionConfigR\tretention\"f\n" +
	"\x0fRetentionConfig\x12\x19\n" +
	"\bhot_days\x18\x01 \x01(\x05R\ahotDays\x12\x1b\n" +
	"\twarm_days\x18\x02 \x01(\x05R\bwarmDays\x12\x1b\n" +
	"\tcold_days\x18\x03 \x01(\x05R\bcoldDays\"[\n" +
	"\x19CreateOrganizationRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12*\n" +
	"\x04tier\x18\x02 \x01(\x0e2\x16.routeiq.v1.admin.TierR\x04tier\"(\n" +
	"\x16GetOrganizationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"V\n" +
	"\x18ListOrganizationsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"\x89\x01\n" +
	"\x19ListOrganizationsResponse\x12D\n" +
	"\rorganizations\x18\x01 \x03(\v2\x1e.routeiq.v1.admin.OrganizationR\rorganizations\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"k\n" +
	"\x19UpdateOrganizationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12*\n" +
	"\x04tier\x18\x03 \x01(\x0e2\x16.routeiq.v1.admin.TierR\x04tier\"+\n" +
	"\x19DeleteOrganizationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xa9\x01\n" +
	"\x16CreateWorkspaceRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\venvironment\x18\x03 \x01(\tR\venvironment\x120\n" +
	"\x06region\x18\x04 \x01(\x0e2\x18.routeiq.v1.admin.RegionR\x06region\"|\n" +
	"\x15ListWorkspacesRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"}\n" +
	"\x16ListWorkspacesResponse\x12;\n" +
	"\n" +
	"workspaces\x18\x01 \x03(\v2\x1b.routeiq.v1.admin.WorkspaceR\n" +
	"workspaces\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"}\n" +
	"\x16UpdateWorkspaceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12?\n" +
	"\tretention\x18\x03 \x01(\v2!.routeiq.v1.admin.RetentionConfigR\tretention*K\n" +
	"\x04Tier\x12\x14\n" +
	"\x10TIER_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04FREE\x10\x01\x12\n" +
	"\n" +
	"\x06GROWTH\x10\x02\x12\a\n" +
	"\x03PRO\x10\x03\x12\x0e\n" +
	"\n" +
	"ENTERPRISE\x10\x04*a\n" +
	"\x06Region\x12\x16\n" +
	"\x12REGION_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tUS_EAST_1\x10\x01\x12\r\n" +
	"\tUS_WEST_2\x10\x02\x12\r\n" +
	"\tEU_WEST_1\x10\x03\x12\x12\n" +
	"\x0eAP_SOUTHEAST_1\x10\x042\x9a\x06\n" +
	"\x13OrganizationService\x12a\n" +
	"\x12CreateOrganization\x12+.routeiq.v1.admin.CreateOrganizationRequest\x1a\x1e.routeiq.v1.admin.Organization\x12[\n" +
	"\x0fGetOrganization\x12(.routeiq.v1.admin.GetOrganizationRequest\x1a\x1e.routeiq.v1.admin.Organization\x12l\n" +
	"\x11ListOrganizations\x12*.routeiq.v1.admin.ListOrganizationsRequest\x1a+.routeiq.v1.admin.ListOrganizationsResponse\x12a\n" +
	"\x12UpdateOrganization\x12+.routeiq.v1.admin.UpdateOrganizationRequest\x1a\x1e.routeiq.v1.admin.Organization\x12Y\n" +
	"\x12DeleteOrganization\x12+.routeiq.v1.admin.DeleteOrganizationRequest\x1a\x16.google.protobuf.Empty\x12X\n" +
	"\x0fCreateWorkspace\x12(.routeiq.v1.admin.CreateWorkspaceRequest\x1a\x1b.routeiq.v1.admin.Workspace\x12c\n" +
	"\x0eListWorkspaces\x12'.routeiq.v1.admin.ListWorkspacesRequest\x1a(.routeiq.v1.admin.ListWorkspacesResponse\x12X\n" +
	"\x0fUpdateWorkspace\x12(.routeiq.v1.admin.UpdateWorkspaceRequest\x1a\x1b.routeiq.v1.admin.WorkspaceB\x91\x01\n" +
	".build.buf.gen.ssforge.routeiq.routeiq.v1.adminB\x11OrganizationProtoZLbuf.build/gen/go/ssforge/routeiq/protocolbuffers/go/routeiq/v1/admin;adminv1b\x06proto3"

var (
	file_routeiq_v1_admin_organization_proto_rawDescOnce sync.Once
	file_routeiq_v1_admin_organization_proto_rawDescData []byte
)

func file_routeiq_v1_admin_organization_proto_rawDescGZIP() []byte {
	file_routeiq_v1_admin_organization_proto_rawDescOnce.Do(func() {
		file_routeiq_v1_admin_organization_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_routeiq_v1_admin_organization_proto_rawDesc), len(file_routeiq_v1_admin_organization_proto_rawDesc)))
	})
	return file_routeiq_v1_admin_organization_proto_rawDescData
}

var file_routeiq_v1_admin_organization_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_routeiq_v1_admin_organization_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_routeiq_v1_admin_organization_proto_goTypes = []any{
	(Tier)(0),                         // 0: routeiq.v1.admin.Tier
	(Region)(0),                       // 1: routeiq.v1.admin.Region
	(*Organization)(nil),              // 2: routeiq.v1.admin.Organization
	(*Workspace)(nil),                 // 3: routeiq.v1.admin.Workspace
	(*RetentionConfig)(nil),           // 4: routeiq.v1.admin.RetentionConfig
	(*CreateOrganizationRequest)(nil), // 5: routeiq.v1.admin.CreateOrganizationRequest
	(*GetOrganizationRequest)(nil),    // 6: routeiq.v1.admin.GetOrganizationRequest
	(*ListOrganizationsRequest)(nil),  // 7: routeiq.v1.admin.ListOrganizationsRequest
	(*ListOrganizationsResponse)(nil), // 8: routeiq.v1.admin.ListOrganizationsResponse
	(*UpdateOrganizationRequest)(nil), // 9: routeiq.v1.admin.UpdateOrganizationRequest
	(*DeleteOrganizationRequest)(nil), // 10: routeiq.v1.admin.DeleteOrganizationRequest
	(*CreateWorkspaceRequest)(nil),    // 11: routeiq.v1.admin.CreateWorkspaceRequest
	(*ListWorkspacesRequest)(nil),     // 12: routeiq.v1.admin.ListWorkspacesRequest
	(*ListWorkspacesResponse)(nil),    // 13: routeiq.v1.admin.ListWorkspacesResponse
	(*UpdateWorkspaceRequest)(nil),    // 14: routeiq.v1.admin.UpdateWorkspaceRequest
	(*timestamppb.Timestamp)(nil),     // 15: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),             // 16: google.protobuf.Empty
}
var file_routeiq_v1_admin_organization_proto_depIdxs = []int32{
	0,  // 0: routeiq.v1.admin.Organization.tier:type_name -> routeiq.v1.admin.Tier
	15, // 1: routeiq.v1.admin.Organization.created_at:type_name -> google.protobuf.Timestamp
	3,  // 2: routeiq.v1.admin.Organization.workspaces:type_name -> routeiq.v1.admin.Workspace
	1,  // 3: routeiq.v1.admin.Workspace.region:type_name -> routeiq.v1.admin.Region
	4,  // 4: routeiq.v1.admin.Workspace.retention:type_name -> routeiq.v1.admin.RetentionConfig
	0,  // 5: routeiq.v1.admin.CreateOrganizationRequest.tier:type_name -> routeiq.v1.admin.Tier
	2,  // 6: routeiq.v1.admin.ListOrganizationsResponse.organizations:type_name -> routeiq.v1.admin.Organization
	0,  // 7: routeiq.v1.admin.UpdateOrganizationRequest.tier:type_name -> routeiq.v1.admin.Tier
	1,  // 8: routeiq.v1.admin.CreateWorkspaceRequest.region:type_name -> routeiq.v1.admin.Region
	3,  // 9: routeiq.v1.admin.ListWorkspacesResponse.workspaces:type_name -> routeiq.v1.admin.Workspace
	4,  // 10: routeiq.v1.admin.UpdateWorkspaceRequest.retention:type_name -> routeiq.v1.admin.RetentionConfig
	5,  // 11: routeiq.v1.admin.OrganizationService.CreateOrganization:input_type -> routeiq.v1.admin.CreateOrganizationRequest
	6,  // 12: routeiq.v1.admin.OrganizationService.GetOrganization:input_type -> routeiq.v1.admin.GetOrganizationRequest
	7,  // 13: routeiq.v1.admin.OrganizationService.ListOrganizations:input_type -> routeiq.v1.admin.ListOrganizationsRequest
	9,  // 14: routeiq.v1.admin.OrganizationService.UpdateOrganization:input_type -> routeiq.v1.admin.UpdateOrganizationRequest
	10, // 15: routeiq.v1.admin.OrganizationService.DeleteOrganization:input_type -> routeiq.v1.admin.DeleteOrganizationRequest
	11, // 16: routeiq.v1.admin.OrganizationService.CreateWorkspace:input_type -> routeiq.v1.admin.CreateWorkspaceRequest
	12, // 17: routeiq.v1.admin.OrganizationService.ListWorkspaces:input_type -> routeiq.v1.admin.ListWorkspacesRequest
	14, // 18: routeiq.v1.admin.OrganizationService.UpdateWorkspace:input_type -> routeiq.v1.admin.UpdateWorkspaceRequest
	2,  // 19: routeiq.v1.admin.OrganizationService.CreateOrganization:output_type -> routeiq.v1.admin.Organization
	2,  // 20: routeiq.v1.admin.OrganizationService.GetOrganization:output_type -> routeiq.v1.admin.Organization
	8,  // 21: routeiq.v1.admin.OrganizationService.ListOrganizations:output_type -> routeiq.v1.admin.ListOrganizationsResponse
	2,  // 22: routeiq.v1.admin.OrganizationService.UpdateOrganization:output_type -> routeiq.v1.admin.Organization
	16, // 23: routeiq.v1.admin.OrganizationService.DeleteOrganization:output_type -> google.protobuf.Empty
	3,  // 24: routeiq.v1.admin.OrganizationService.CreateWorkspace:output_type -> routeiq.v1.admin.Workspace
	13, // 25: routeiq.v1.admin.OrganizationService.ListWorkspaces:output_type -> routeiq.v1.admin.ListWorkspacesResponse
	3,  // 26: routeiq.v1.admin.OrganizationService.UpdateWorkspace:output_type -> routeiq.v1.admin.Workspace
	19, // [19:27] is the sub-list for method output_type
	11, // [11:19] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_routeiq_v1_admin_organization_proto_init() }
func file_routeiq_v1_admin_organization_proto_init() {
	if File_routeiq_v1_admin_organization_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_routeiq_v1_admin_organization_proto_rawDesc), len(file_routeiq_v1_admin_organization_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_routeiq_v1_admin_organization_proto_goTypes,
		DependencyIndexes: file_routeiq_v1_admin_organization_proto_depIdxs,
		EnumInfos:         file_routeiq_v1_admin_organization_proto_enumTypes,
		MessageInfos:      file_routeiq_v1_admin_organization_proto_msgTypes,
	}.Build()
	File_routeiq_v1_admin_organization_proto = out.File
	file_routeiq_v1_admin_organization_proto_goTypes = nil
	file_routeiq_v1_admin_organization_proto_depIdxs = nil
}
