// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: routeiq/v1/admin/policy.proto

package adminv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PolicyBundle struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	WorkspaceId    string                 `protobuf:"bytes,3,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Version        string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Content        []byte                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Active         bool                   `protobuf:"varint,6,opt,name=active,proto3" json:"active,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PolicyBundle) Reset() {
	*x = PolicyBundle{}
	mi := &file_routeiq_v1_admin_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyBundle) ProtoMessage() {}

func (x *PolicyBundle) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_admin_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyBundle.ProtoReflect.Descriptor instead.
func (*PolicyBundle) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_admin_policy_proto_rawDescGZIP(), []int{0}
}

func (x *PolicyBundle) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PolicyBundle) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *PolicyBundle) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *PolicyBundle) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PolicyBundle) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *PolicyBundle) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *PolicyBundle) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreatePolicyBundleRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	WorkspaceId    string                 `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Content        []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreatePolicyBundleRequest) Reset() {
	*x = CreatePolicyBundleRequest{}
	mi := &file_routeiq_v1_admin_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePolicyBundleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePolicyBundleRequest) ProtoMessage() {}

func (x *CreatePolicyBundleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_admin_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePolicyBundleRequest.ProtoReflect.Descriptor instead.
func (*CreatePolicyBundleRequest) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_admin_policy_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePolicyBundleRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *CreatePolicyBundleRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *CreatePolicyBundleRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type GetPolicyBundleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPolicyBundleRequest) Reset() {
	*x = GetPolicyBundleRequest{}
	mi := &file_routeiq_v1_admin_policy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPolicyBundleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPolicyBundleRequest) ProtoMessage() {}

func (x *GetPolicyBundleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_admin_policy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPolicyBundleRequest.ProtoReflect.Descriptor instead.
func (*GetPolicyBundleRequest) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_admin_policy_proto_rawDescGZIP(), []int{2}
}

func (x *GetPolicyBundleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListPolicyBundlesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	ActiveOnly    bool                   `protobuf:"varint,2,opt,name=active_only,json=activeOnly,proto3" json:"active_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPolicyBundlesRequest) Reset() {
	*x = ListPolicyBundlesRequest{}
	mi := &file_routeiq_v1_admin_policy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPolicyBundlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPolicyBundlesRequest) ProtoMessage() {}

func (x *ListPolicyBundlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_admin_policy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPolicyBundlesRequest.ProtoReflect.Descriptor instead.
func (*ListPolicyBundlesRequest) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_admin_policy_proto_rawDescGZIP(), []int{3}
}

func (x *ListPolicyBundlesRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *ListPolicyBundlesRequest) GetActiveOnly() bool {
	if x != nil {
		return x.ActiveOnly
	}
	return false
}

type ListPolicyBundlesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bundles       []*PolicyBundle        `protobuf:"bytes,1,rep,name=bundles,proto3" json:"bundles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPolicyBundlesResponse) Reset() {
	*x = ListPolicyBundlesResponse{}
	mi := &file_routeiq_v1_admin_policy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPolicyBundlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPolicyBundlesResponse) ProtoMessage() {}

func (x *ListPolicyBundlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_admin_policy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPolicyBundlesResponse.ProtoReflect.Descriptor instead.
func (*ListPolicyBundlesResponse) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_admin_policy_proto_rawDescGZIP(), []int{4}
}

func (x *ListPolicyBundlesResponse) GetBundles() []*PolicyBundle {
	if x != nil {
		return x.Bundles
	}
	return nil
}

type ActivatePolicyBundleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivatePolicyBundleRequest) Reset() {
	*x = ActivatePolicyBundleRequest{}
	mi := &file_routeiq_v1_admin_policy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivatePolicyBundleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivatePolicyBundleRequest) ProtoMessage() {}

func (x *ActivatePolicyBundleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_admin_policy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivatePolicyBundleRequest.ProtoReflect.Descriptor instead.
func (*ActivatePolicyBundleRequest) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_admin_policy_proto_rawDescGZIP(), []int{5}
}

func (x *ActivatePolicyBundleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeletePolicyBundleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePolicyBundleRequest) Reset() {
	*x = DeletePolicyBundleRequest{}
	mi := &file_routeiq_v1_admin_policy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePolicyBundleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePolicyBundleRequest) ProtoMessage() {}

func (x *DeletePolicyBundleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_admin_policy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePolicyBundleRequest.ProtoReflect.Descriptor instead.
func (*DeletePolicyBundleRequest) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_admin_policy_proto_rawDescGZIP(), []int{6}
}

func (x *DeletePolicyBundleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_routeiq_v1_admin_policy_proto protoreflect.FileDescriptor

const file_routeiq_v1_admin_policy_proto_rawDesc = "" +
	"\n" +
	"\x1drouteiq/v1/admin/policy.proto\x12\x10routeiq.v1.admin\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf1\x01\n" +
	"\fPolicyBundle\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12!\n" +
	"\fworkspace_id\x18\x03 \x01(\tR\vworkspaceId\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x18\n" +
	"\acontent\x18\x05 \x01(\fR\acontent\x12\x16\n" +
	"\x06active\x18\x06 \x01(\bR\x06active\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x81\x01\n" +
	"\x19CreatePolicyBundleRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12!\n" +
	"\fworkspace_id\x18\x02 \x01(\tR\vworkspaceId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\"(\n" +
	"\x16GetPolicyBundleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"^\n" +
	"\x18ListPolicyBundlesRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x1f\n" +
	"\vactive_only\x18\x02 \x01(\bR\n" +
	"activeOnly\"U\n" +
	"\x19ListPolicyBundlesResponse\x128\n" +
	"\abundles\x18\x01 \x03(\v2\x1e.routeiq.v1.admin.PolicyBundleR\abundles\"-\n" +
	"\x1bActivatePolicyBundleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"+\n" +
	"\x19DeletePolicyBundleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2\xff\x03\n" +
	"\rPolicyService\x12a\n" +
	"\x12CreatePolicyBundle\x12+.routeiq.v1.admin.CreatePolicyBundleRequest\x1a\x1e.routeiq.v1.admin.PolicyBundle\x12[\n" +
	"\x0fGetPolicyBundle\x12(.routeiq.v1.admin.GetPolicyBundleRequest\x1a\x1e.routeiq.v1.admin.PolicyBundle\x12l\n" +
	"\x11ListPolicyBundles\x12*.routeiq.v1.admin.ListPolicyBundlesRequest\x1a+.routeiq.v1.admin.ListPolicyBundlesResponse\x12e\n" +
	"\x14ActivatePolicyBundle\x12-.routeiq.v1.admin.ActivatePolicyBundleRequest\x1a\x1e.routeiq.v1.admin.PolicyBundle\x12Y\n" +
	"\x12DeletePolicyBundle\x12+.routeiq.v1.admin.DeletePolicyBundleRequest\x1a\x16.google.protobuf.EmptyB\x8b\x01\n" +
	".build.buf.gen.ssforge.routeiq.routeiq.v1.adminB\vPolicyProtoZLbuf.build/gen/go/ssforge/routeiq/protocolbuffers/go/routeiq/v1/admin;adminv1b\x06proto3"

var (
	file_routeiq_v1_admin_policy_proto_rawDescOnce sync.Once
	file_routeiq_v1_admin_policy_proto_rawDescData []byte
)

func file_routeiq_v1_admin_policy_proto_rawDescGZIP() []byte {
	file_routeiq_v1_admin_policy_proto_rawDescOnce.Do(func() {
		file_routeiq_v1_admin_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_routeiq_v1_admin_policy_proto_rawDesc), len(file_routeiq_v1_admin_policy_proto_rawDesc)))
	})
	return file_routeiq_v1_admin_policy_proto_rawDescData
}

var file_routeiq_v1_admin_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_routeiq_v1_admin_policy_proto_goTypes = []any{
	(*PolicyBundle)(nil),                // 0: routeiq.v1.admin.PolicyBundle
	(*CreatePolicyBundleRequest)(nil),   // 1: routeiq.v1.admin.CreatePolicyBundleRequest
	(*GetPolicyBundleRequest)(nil),      // 2: routeiq.v1.admin.GetPolicyBundleRequest
	(*ListPolicyBundlesRequest)(nil),    // 3: routeiq.v1.admin.ListPolicyBundlesRequest
	(*ListPolicyBundlesResponse)(nil),   // 4: routeiq.v1.admin.ListPolicyBundlesResponse
	(*ActivatePolicyBundleRequest)(nil), // 5: routeiq.v1.admin.ActivatePolicyBundleRequest
	(*DeletePolicyBundleRequest)(nil),   // 6: routeiq.v1.admin.DeletePolicyBundleRequest
	(*timestamppb.Timestamp)(nil),       // 7: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),               // 8: google.protobuf.Empty
}
var file_routeiq_v1_admin_policy_proto_depIdxs = []int32{
	7, // 0: routeiq.v1.admin.PolicyBundle.created_at:type_name -> google.protobuf.Timestamp
	0, // 1: routeiq.v1.admin.ListPolicyBundlesResponse.bundles:type_name -> routeiq.v1.admin.PolicyBundle
	1, // 2: routeiq.v1.admin.PolicyService.CreatePolicyBundle:input_type -> routeiq.v1.admin.CreatePolicyBundleRequest
	2, // 3: routeiq.v1.admin.PolicyService.GetPolicyBundle:input_type -> routeiq.v1.admin.GetPolicyBundleRequest
	3, // 4: routeiq.v1.admin.PolicyService.ListPolicyBundles:input_type -> routeiq.v1.admin.ListPolicyBundlesRequest
	5, // 5: routeiq.v1.admin.PolicyService.ActivatePolicyBundle:input_type -> routeiq.v1.admin.ActivatePolicyBundleRequest
	6, // 6: routeiq.v1.admin.PolicyService.DeletePolicyBundle:input_type -> routeiq.v1.admin.DeletePolicyBundleRequest
	0, // 7: routeiq.v1.admin.PolicyService.CreatePolicyBundle:output_type -> routeiq.v1.admin.PolicyBundle
	0, // 8: routeiq.v1.admin.PolicyService.GetPolicyBundle:output_type -> routeiq.v1.admin.PolicyBundle
	4, // 9: routeiq.v1.admin.PolicyService.ListPolicyBundles:output_type -> routeiq.v1.admin.ListPolicyBundlesResponse
	0, // 10: routeiq.v1.admin.PolicyService.ActivatePolicyBundle:output_type -> routeiq.v1.admin.PolicyBundle
	8, // 11: routeiq.v1.admin.PolicyService.DeletePolicyBundle:output_type -> google.protobuf.Empty
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_routeiq_v1_admin_policy_proto_init() }
func file_routeiq_v1_admin_policy_proto_init() {
	if File_routeiq_v1_admin_policy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_routeiq_v1_admin_policy_proto_rawDesc), len(file_routeiq_v1_admin_policy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_routeiq_v1_admin_policy_proto_goTypes,
		DependencyIndexes: file_routeiq_v1_admin_policy_proto_depIdxs,
		MessageInfos:      file_routeiq_v1_admin_policy_proto_msgTypes,
	}.Build()
	File_routeiq_v1_admin_policy_proto = out.File
	file_routeiq_v1_admin_policy_proto_goTypes = nil
	file_routeiq_v1_admin_policy_proto_depIdxs = nil
}
