// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: routeiq/v1/admin/slo_config.proto

package adminv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SloOverride struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MetricId         string                 `protobuf:"bytes,1,opt,name=metric_id,json=metricId,proto3" json:"metric_id,omitempty"`
	WorkspaceId      string                 `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Tier             string                 `protobuf:"bytes,3,opt,name=tier,proto3" json:"tier,omitempty"`
	TargetExpression string                 `protobuf:"bytes,4,opt,name=target_expression,json=targetExpression,proto3" json:"target_expression,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SloOverride) Reset() {
	*x = SloOverride{}
	mi := &file_routeiq_v1_admin_slo_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SloOverride) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SloOverride) ProtoMessage() {}

func (x *SloOverride) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_admin_slo_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SloOverride.ProtoReflect.Descriptor instead.
func (*SloOverride) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_admin_slo_config_proto_rawDescGZIP(), []int{0}
}

func (x *SloOverride) GetMetricId() string {
	if x != nil {
		return x.MetricId
	}
	return ""
}

func (x *SloOverride) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *SloOverride) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

func (x *SloOverride) GetTargetExpression() string {
	if x != nil {
		return x.TargetExpression
	}
	return ""
}

type SloOverrides struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Overrides     []*SloOverride         `protobuf:"bytes,2,rep,name=overrides,proto3" json:"overrides,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SloOverrides) Reset() {
	*x = SloOverrides{}
	mi := &file_routeiq_v1_admin_slo_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SloOverrides) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SloOverrides) ProtoMessage() {}

func (x *SloOverrides) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_admin_slo_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SloOverrides.ProtoReflect.Descriptor instead.
func (*SloOverrides) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_admin_slo_config_proto_rawDescGZIP(), []int{1}
}

func (x *SloOverrides) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *SloOverrides) GetOverrides() []*SloOverride {
	if x != nil {
		return x.Overrides
	}
	return nil
}

type GetSloOverridesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSloOverridesRequest) Reset() {
	*x = GetSloOverridesRequest{}
	mi := &file_routeiq_v1_admin_slo_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSloOverridesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSloOverridesRequest) ProtoMessage() {}

func (x *GetSloOverridesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_admin_slo_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSloOverridesRequest.ProtoReflect.Descriptor instead.
func (*GetSloOverridesRequest) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_admin_slo_config_proto_rawDescGZIP(), []int{2}
}

func (x *GetSloOverridesRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

type SetSloOverrideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Override      *SloOverride           `protobuf:"bytes,1,opt,name=override,proto3" json:"override,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSloOverrideRequest) Reset() {
	*x = SetSloOverrideRequest{}
	mi := &file_routeiq_v1_admin_slo_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSloOverrideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSloOverrideRequest) ProtoMessage() {}

func (x *SetSloOverrideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_admin_slo_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSloOverrideRequest.ProtoReflect.Descriptor instead.
func (*SetSloOverrideRequest) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_admin_slo_config_proto_rawDescGZIP(), []int{3}
}

func (x *SetSloOverrideRequest) GetOverride() *SloOverride {
	if x != nil {
		return x.Override
	}
	return nil
}

type DeleteSloOverrideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MetricId      string                 `protobuf:"bytes,1,opt,name=metric_id,json=metricId,proto3" json:"metric_id,omitempty"`
	WorkspaceId   string                 `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Tier          string                 `protobuf:"bytes,3,opt,name=tier,proto3" json:"tier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSloOverrideRequest) Reset() {
	*x = DeleteSloOverrideRequest{}
	mi := &file_routeiq_v1_admin_slo_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSloOverrideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSloOverrideRequest) ProtoMessage() {}

func (x *DeleteSloOverrideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_admin_slo_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSloOverrideRequest.ProtoReflect.Descriptor instead.
func (*DeleteSloOverrideRequest) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_admin_slo_config_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteSloOverrideRequest) GetMetricId() string {
	if x != nil {
		return x.MetricId
	}
	return ""
}

func (x *DeleteSloOverrideRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *DeleteSloOverrideRequest) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

var File_routeiq_v1_admin_slo_config_proto protoreflect.FileDescriptor

const file_routeiq_v1_admin_slo_config_proto_rawDesc = "" +
	"\n" +
	"!routeiq/v1/admin/slo_config.proto\x12\x10routeiq.v1.admin\"\x8e\x01\n" +
	"\vSloOverride\x12\x1b\n" +
	"\tmetric_id\x18\x01 \x01(\tR\bmetricId\x12!\n" +
	"\fworkspace_id\x18\x02 \x01(\tR\vworkspaceId\x12\x12\n" +
	"\x04tier\x18\x03 \x01(\tR\x04tier\x12+\n" +
	"\x11target_expression\x18\x04 \x01(\tR\x10targetExpression\"n\n" +
	"\fSloOverrides\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12;\n" +
	"\toverrides\x18\x02 \x03(\v2\x1d.routeiq.v1.admin.SloOverrideR\toverrides\";\n" +
	"\x16GetSloOverridesRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\"R\n" +
	"\x15SetSloOverrideRequest\x129\n" +
	"\boverride\x18\x01 \x01(\v2\x1d.routeiq.v1.admin.SloOverrideR\boverride\"n\n" +
	"\x18DeleteSloOverrideRequest\x12\x1b\n" +
	"\tmetric_id\x18\x01 \x01(\tR\bmetricId\x12!\n" +
	"\fworkspace_id\x18\x02 \x01(\tR\vworkspaceId\x12\x12\n" +
	"\x04tier\x18\x03 \x01(\tR\x04tier2\xaa\x02\n" +
	"\x10SloConfigService\x12[\n" +
	"\x0fGetSloOverrides\x12(.routeiq.v1.admin.GetSloOverridesRequest\x1a\x1e.routeiq.v1.admin.SloOverrides\x12X\n" +
	"\x0eSetSloOverride\x12'.routeiq.v1.admin.SetSloOverrideRequest\x1a\x1d.routeiq.v1.admin.SloOverride\x12_\n" +
	"\x11DeleteSloOverride\x12*.routeiq.v1.admin.DeleteSloOverrideRequest\x1a\x1e.routeiq.v1.admin.SloOverridesB\x8e\x01\n" +
	".build.buf.gen.ssforge.routeiq.routeiq.v1.adminB\x0eSloConfigProtoZLbuf.build/gen/go/ssforge/routeiq/protocolbuffers/go/routeiq/v1/admin;adminv1b\x06proto3"

var (
	file_routeiq_v1_admin_slo_config_proto_rawDescOnce sync.Once
	file_routeiq_v1_admin_slo_config_proto_rawDescData []byte
)

func file_routeiq_v1_admin_slo_config_proto_rawDescGZIP() []byte {
	file_routeiq_v1_admin_slo_config_proto_rawDescOnce.Do(func() {
		file_routeiq_v1_admin_slo_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_routeiq_v1_admin_slo_config_proto_rawDesc), len(file_routeiq_v1_admin_slo_config_proto_rawDesc)))
	})
	return file_routeiq_v1_admin_slo_config_proto_rawDescData
}

var file_routeiq_v1_admin_slo_config_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_routeiq_v1_admin_slo_config_proto_goTypes = []any{
	(*SloOverride)(nil),              // 0: routeiq.v1.admin.SloOverride
	(*SloOverrides)(nil),             // 1: routeiq.v1.admin.SloOverrides
	(*GetSloOverridesRequest)(nil),   // 2: routeiq.v1.admin.GetSloOverridesRequest
	(*SetSloOverrideRequest)(nil),    // 3: routeiq.v1.admin.SetSloOverrideRequest
	(*DeleteSloOverrideRequest)(nil), // 4: routeiq.v1.admin.DeleteSloOverrideRequest
}
var file_routeiq_v1_admin_slo_config_proto_depIdxs = []int32{
	0, // 0: routeiq.v1.admin.SloOverrides.overrides:type_name -> routeiq.v1.admin.SloOverride
	0, // 1: routeiq.v1.admin.SetSloOverrideRequest.override:type_name -> routeiq.v1.admin.SloOverride
	2, // 2: routeiq.v1.admin.SloConfigService.GetSloOverrides:input_type -> routeiq.v1.admin.GetSloOverridesRequest
	3, // 3: routeiq.v1.admin.SloConfigService.SetSloOverride:input_type -> routeiq.v1.admin.SetSloOverrideRequest
	4, // 4: routeiq.v1.admin.SloConfigService.DeleteSloOverride:input_type -> routeiq.v1.admin.DeleteSloOverrideRequest
	1, // 5: routeiq.v1.admin.SloConfigService.GetSloOverrides:output_type -> routeiq.v1.admin.SloOverrides
	0, // 6: routeiq.v1.admin.SloConfigService.SetSloOverride:output_type -> routeiq.v1.admin.SloOverride
	1, // 7: routeiq.v1.admin.SloConfigService.DeleteSloOverride:output_type -> routeiq.v1.admin.SloOverrides
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_routeiq_v1_admin_slo_config_proto_init() }
func file_routeiq_v1_admin_slo_config_proto_init() {
	if File_routeiq_v1_admin_slo_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_routeiq_v1_admin_slo_config_proto_rawDesc), len(file_routeiq_v1_admin_slo_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_routeiq_v1_admin_slo_config_proto_goTypes,
		DependencyIndexes: file_routeiq_v1_admin_slo_config_proto_depIdxs,
		MessageInfos:      file_routeiq_v1_admin_slo_config_proto_msgTypes,
	}.Build()
	File_routeiq_v1_admin_slo_config_proto = out.File
	file_routeiq_v1_admin_slo_config_proto_goTypes = nil
	file_routeiq_v1_admin_slo_config_proto_depIdxs = nil
}
