// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: routeiq/v1/admin/billing.proto

package adminv1connect

import (
	admin "buf.build/gen/go/ssforge/routeiq/protocolbuffers/go/routeiq/v1/admin"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// BillingServiceName is the fully-qualified name of the BillingService service.
	BillingServiceName = "routeiq.v1.admin.BillingService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// BillingServiceGetUsageProcedure is the fully-qualified name of the BillingService's GetUsage RPC.
	BillingServiceGetUsageProcedure = "/routeiq.v1.admin.BillingService/GetUsage"
	// BillingServiceGetQuotaProcedure is the fully-qualified name of the BillingService's GetQuota RPC.
	BillingServiceGetQuotaProcedure = "/routeiq.v1.admin.BillingService/GetQuota"
)

// BillingServiceClient is a client for the routeiq.v1.admin.BillingService service.
type BillingServiceClient interface {
	GetUsage(context.Context, *connect.Request[admin.GetUsageRequest]) (*connect.Response[admin.UsageSummary], error)
	GetQuota(context.Context, *connect.Request[admin.GetQuotaRequest]) (*connect.Response[admin.Quota], error)
}

// NewBillingServiceClient constructs a client for the routeiq.v1.admin.BillingService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewBillingServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) BillingServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	billingServiceMethods := admin.File_routeiq_v1_admin_billing_proto.Services().ByName("BillingService").Methods()
	return &billingServiceClient{
		getUsage: connect.NewClient[admin.GetUsageRequest, admin.UsageSummary](
			httpClient,
			baseURL+BillingServiceGetUsageProcedure,
			connect.WithSchema(billingServiceMethods.ByName("GetUsage")),
			connect.WithClientOptions(opts...),
		),
		getQuota: connect.NewClient[admin.GetQuotaRequest, admin.Quota](
			httpClient,
			baseURL+BillingServiceGetQuotaProcedure,
			connect.WithSchema(billingServiceMethods.ByName("GetQuota")),
			connect.WithClientOptions(opts...),
		),
	}
}

// billingServiceClient implements BillingServiceClient.
type billingServiceClient struct {
	getUsage *connect.Client[admin.GetUsageRequest, admin.UsageSummary]
	getQuota *connect.Client[admin.GetQuotaRequest, admin.Quota]
}

// GetUsage calls routeiq.v1.admin.BillingService.GetUsage.
func (c *billingServiceClient) GetUsage(ctx context.Context, req *connect.Request[admin.GetUsageRequest]) (*connect.Response[admin.UsageSummary], error) {
	return c.getUsage.CallUnary(ctx, req)
}

// GetQuota calls routeiq.v1.admin.BillingService.GetQuota.
func (c *billingServiceClient) GetQuota(ctx context.Context, req *connect.Request[admin.GetQuotaRequest]) (*connect.Response[admin.Quota], error) {
	return c.getQuota.CallUnary(ctx, req)
}

// BillingServiceHandler is an implementation of the routeiq.v1.admin.BillingService service.
type BillingServiceHandler interface {
	GetUsage(context.Context, *connect.Request[admin.GetUsageRequest]) (*connect.Response[admin.UsageSummary], error)
	GetQuota(context.Context, *connect.Request[admin.GetQuotaRequest]) (*connect.Response[admin.Quota], error)
}

// NewBillingServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewBillingServiceHandler(svc BillingServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	billingServiceMethods := admin.File_routeiq_v1_admin_billing_proto.Services().ByName("BillingService").Methods()
	billingServiceGetUsageHandler := connect.NewUnaryHandler(
		BillingServiceGetUsageProcedure,
		svc.GetUsage,
		connect.WithSchema(billingServiceMethods.ByName("GetUsage")),
		connect.WithHandlerOptions(opts...),
	)
	billingServiceGetQuotaHandler := connect.NewUnaryHandler(
		BillingServiceGetQuotaProcedure,
		svc.GetQuota,
		connect.WithSchema(billingServiceMethods.ByName("GetQuota")),
		connect.WithHandlerOptions(opts...),
	)
	return "/routeiq.v1.admin.BillingService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case BillingServiceGetUsageProcedure:
			billingServiceGetUsageHandler.ServeHTTP(w, r)
		case BillingServiceGetQuotaProcedure:
			billingServiceGetQuotaHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedBillingServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedBillingServiceHandler struct{}

func (UnimplementedBillingServiceHandler) GetUsage(context.Context, *connect.Request[admin.GetUsageRequest]) (*connect.Response[admin.UsageSummary], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("routeiq.v1.admin.BillingService.GetUsage is not implemented"))
}

func (UnimplementedBillingServiceHandler) GetQuota(context.Context, *connect.Request[admin.GetQuotaRequest]) (*connect.Response[admin.Quota], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("routeiq.v1.admin.BillingService.GetQuota is not implemented"))
}
