// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: routeiq/v1/admin/identity.proto

package adminv1connect

import (
	admin "buf.build/gen/go/ssforge/routeiq/protocolbuffers/go/routeiq/v1/admin"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// IdentityServiceName is the fully-qualified name of the IdentityService service.
	IdentityServiceName = "routeiq.v1.admin.IdentityService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// IdentityServiceInviteUserProcedure is the fully-qualified name of the IdentityService's
	// InviteUser RPC.
	IdentityServiceInviteUserProcedure = "/routeiq.v1.admin.IdentityService/InviteUser"
	// IdentityServiceGetUserProcedure is the fully-qualified name of the IdentityService's GetUser RPC.
	IdentityServiceGetUserProcedure = "/routeiq.v1.admin.IdentityService/GetUser"
	// IdentityServiceAssignRoleProcedure is the fully-qualified name of the IdentityService's
	// AssignRole RPC.
	IdentityServiceAssignRoleProcedure = "/routeiq.v1.admin.IdentityService/AssignRole"
	// IdentityServiceCreateApiKeyProcedure is the fully-qualified name of the IdentityService's
	// CreateApiKey RPC.
	IdentityServiceCreateApiKeyProcedure = "/routeiq.v1.admin.IdentityService/CreateApiKey"
	// IdentityServiceRevokeApiKeyProcedure is the fully-qualified name of the IdentityService's
	// RevokeApiKey RPC.
	IdentityServiceRevokeApiKeyProcedure = "/routeiq.v1.admin.IdentityService/RevokeApiKey"
	// IdentityServiceListApiKeysProcedure is the fully-qualified name of the IdentityService's
	// ListApiKeys RPC.
	IdentityServiceListApiKeysProcedure = "/routeiq.v1.admin.IdentityService/ListApiKeys"
)

// IdentityServiceClient is a client for the routeiq.v1.admin.IdentityService service.
type IdentityServiceClient interface {
	InviteUser(context.Context, *connect.Request[admin.InviteUserRequest]) (*connect.Response[admin.User], error)
	GetUser(context.Context, *connect.Request[admin.GetUserRequest]) (*connect.Response[admin.User], error)
	AssignRole(context.Context, *connect.Request[admin.AssignRoleRequest]) (*connect.Response[admin.RoleAssignment], error)
	CreateApiKey(context.Context, *connect.Request[admin.CreateApiKeyRequest]) (*connect.Response[admin.ApiKey], error)
	RevokeApiKey(context.Context, *connect.Request[admin.RevokeApiKeyRequest]) (*connect.Response[emptypb.Empty], error)
	ListApiKeys(context.Context, *connect.Request[admin.ListApiKeysRequest]) (*connect.Response[admin.ListApiKeysResponse], error)
}

// NewIdentityServiceClient constructs a client for the routeiq.v1.admin.IdentityService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewIdentityServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) IdentityServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	identityServiceMethods := admin.File_routeiq_v1_admin_identity_proto.Services().ByName("IdentityService").Methods()
	return &identityServiceClient{
		inviteUser: connect.NewClient[admin.InviteUserRequest, admin.User](
			httpClient,
			baseURL+IdentityServiceInviteUserProcedure,
			connect.WithSchema(identityServiceMethods.ByName("InviteUser")),
			connect.WithClientOptions(opts...),
		),
		getUser: connect.NewClient[admin.GetUserRequest, admin.User](
			httpClient,
			baseURL+IdentityServiceGetUserProcedure,
			connect.WithSchema(identityServiceMethods.ByName("GetUser")),
			connect.WithClientOptions(opts...),
		),
		assignRole: connect.NewClient[admin.AssignRoleRequest, admin.RoleAssignment](
			httpClient,
			baseURL+IdentityServiceAssignRoleProcedure,
			connect.WithSchema(identityServiceMethods.ByName("AssignRole")),
			connect.WithClientOptions(opts...),
		),
		createApiKey: connect.NewClient[admin.CreateApiKeyRequest, admin.ApiKey](
			httpClient,
			baseURL+IdentityServiceCreateApiKeyProcedure,
			connect.WithSchema(identityServiceMethods.ByName("CreateApiKey")),
			connect.WithClientOptions(opts...),
		),
		revokeApiKey: connect.NewClient[admin.RevokeApiKeyRequest, emptypb.Empty](
			httpClient,
			baseURL+IdentityServiceRevokeApiKeyProcedure,
			connect.WithSchema(identityServiceMethods.ByName("RevokeApiKey")),
			connect.WithClientOptions(opts...),
		),
		listApiKeys: connect.NewClient[admin.ListApiKeysRequest, admin.ListApiKeysResponse](
			httpClient,
			baseURL+IdentityServiceListApiKeysProcedure,
			connect.WithSchema(identityServiceMethods.ByName("ListApiKeys")),
			connect.WithClientOptions(opts...),
		),
	}
}

// identityServiceClient implements IdentityServiceClient.
type identityServiceClient struct {
	inviteUser   *connect.Client[admin.InviteUserRequest, admin.User]
	getUser      *connect.Client[admin.GetUserRequest, admin.User]
	assignRole   *connect.Client[admin.AssignRoleRequest, admin.RoleAssignment]
	createApiKey *connect.Client[admin.CreateApiKeyRequest, admin.ApiKey]
	revokeApiKey *connect.Client[admin.RevokeApiKeyRequest, emptypb.Empty]
	listApiKeys  *connect.Client[admin.ListApiKeysRequest, admin.ListApiKeysResponse]
}

// InviteUser calls routeiq.v1.admin.IdentityService.InviteUser.
func (c *identityServiceClient) InviteUser(ctx context.Context, req *connect.Request[admin.InviteUserRequest]) (*connect.Response[admin.User], error) {
	return c.inviteUser.CallUnary(ctx, req)
}

// GetUser calls routeiq.v1.admin.IdentityService.GetUser.
func (c *identityServiceClient) GetUser(ctx context.Context, req *connect.Request[admin.GetUserRequest]) (*connect.Response[admin.User], error) {
	return c.getUser.CallUnary(ctx, req)
}

// AssignRole calls routeiq.v1.admin.IdentityService.AssignRole.
func (c *identityServiceClient) AssignRole(ctx context.Context, req *connect.Request[admin.AssignRoleRequest]) (*connect.Response[admin.RoleAssignment], error) {
	return c.assignRole.CallUnary(ctx, req)
}

// CreateApiKey calls routeiq.v1.admin.IdentityService.CreateApiKey.
func (c *identityServiceClient) CreateApiKey(ctx context.Context, req *connect.Request[admin.CreateApiKeyRequest]) (*connect.Response[admin.ApiKey], error) {
	return c.createApiKey.CallUnary(ctx, req)
}

// RevokeApiKey calls routeiq.v1.admin.IdentityService.RevokeApiKey.
func (c *identityServiceClient) RevokeApiKey(ctx context.Context, req *connect.Request[admin.RevokeApiKeyRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.revokeApiKey.CallUnary(ctx, req)
}

// ListApiKeys calls routeiq.v1.admin.IdentityService.ListApiKeys.
func (c *identityServiceClient) ListApiKeys(ctx context.Context, req *connect.Request[admin.ListApiKeysRequest]) (*connect.Response[admin.ListApiKeysResponse], error) {
	return c.listApiKeys.CallUnary(ctx, req)
}

// IdentityServiceHandler is an implementation of the routeiq.v1.admin.IdentityService service.
type IdentityServiceHandler interface {
	InviteUser(context.Context, *connect.Request[admin.InviteUserRequest]) (*connect.Response[admin.User], error)
	GetUser(context.Context, *connect.Request[admin.GetUserRequest]) (*connect.Response[admin.User], error)
	AssignRole(context.Context, *connect.Request[admin.AssignRoleRequest]) (*connect.Response[admin.RoleAssignment], error)
	CreateApiKey(context.Context, *connect.Request[admin.CreateApiKeyRequest]) (*connect.Response[admin.ApiKey], error)
	RevokeApiKey(context.Context, *connect.Request[admin.RevokeApiKeyRequest]) (*connect.Response[emptypb.Empty], error)
	ListApiKeys(context.Context, *connect.Request[admin.ListApiKeysRequest]) (*connect.Response[admin.ListApiKeysResponse], error)
}

// NewIdentityServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewIdentityServiceHandler(svc IdentityServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	identityServiceMethods := admin.File_routeiq_v1_admin_identity_proto.Services().ByName("IdentityService").Methods()
	identityServiceInviteUserHandler := connect.NewUnaryHandler(
		IdentityServiceInviteUserProcedure,
		svc.InviteUser,
		connect.WithSchema(identityServiceMethods.ByName("InviteUser")),
		connect.WithHandlerOptions(opts...),
	)
	identityServiceGetUserHandler := connect.NewUnaryHandler(
		IdentityServiceGetUserProcedure,
		svc.GetUser,
		connect.WithSchema(identityServiceMethods.ByName("GetUser")),
		connect.WithHandlerOptions(opts...),
	)
	identityServiceAssignRoleHandler := connect.NewUnaryHandler(
		IdentityServiceAssignRoleProcedure,
		svc.AssignRole,
		connect.WithSchema(identityServiceMethods.ByName("AssignRole")),
		connect.WithHandlerOptions(opts...),
	)
	identityServiceCreateApiKeyHandler := connect.NewUnaryHandler(
		IdentityServiceCreateApiKeyProcedure,
		svc.CreateApiKey,
		connect.WithSchema(identityServiceMethods.ByName("CreateApiKey")),
		connect.WithHandlerOptions(opts...),
	)
	identityServiceRevokeApiKeyHandler := connect.NewUnaryHandler(
		IdentityServiceRevokeApiKeyProcedure,
		svc.RevokeApiKey,
		connect.WithSchema(identityServiceMethods.ByName("RevokeApiKey")),
		connect.WithHandlerOptions(opts...),
	)
	identityServiceListApiKeysHandler := connect.NewUnaryHandler(
		IdentityServiceListApiKeysProcedure,
		svc.ListApiKeys,
		connect.WithSchema(identityServiceMethods.ByName("ListApiKeys")),
		connect.WithHandlerOptions(opts...),
	)
	return "/routeiq.v1.admin.IdentityService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case IdentityServiceInviteUserProcedure:
			identityServiceInviteUserHandler.ServeHTTP(w, r)
		case IdentityServiceGetUserProcedure:
			identityServiceGetUserHandler.ServeHTTP(w, r)
		case IdentityServiceAssignRoleProcedure:
			identityServiceAssignRoleHandler.ServeHTTP(w, r)
		case IdentityServiceCreateApiKeyProcedure:
			identityServiceCreateApiKeyHandler.ServeHTTP(w, r)
		case IdentityServiceRevokeApiKeyProcedure:
			identityServiceRevokeApiKeyHandler.ServeHTTP(w, r)
		case IdentityServiceListApiKeysProcedure:
			identityServiceListApiKeysHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedIdentityServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedIdentityServiceHandler struct{}

func (UnimplementedIdentityServiceHandler) InviteUser(context.Context, *connect.Request[admin.InviteUserRequest]) (*connect.Response[admin.User], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("routeiq.v1.admin.IdentityService.InviteUser is not implemented"))
}

func (UnimplementedIdentityServiceHandler) GetUser(context.Context, *connect.Request[admin.GetUserRequest]) (*connect.Response[admin.User], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("routeiq.v1.admin.IdentityService.GetUser is not implemented"))
}

func (UnimplementedIdentityServiceHandler) AssignRole(context.Context, *connect.Request[admin.AssignRoleRequest]) (*connect.Response[admin.RoleAssignment], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("routeiq.v1.admin.IdentityService.AssignRole is not implemented"))
}

func (UnimplementedIdentityServiceHandler) CreateApiKey(context.Context, *connect.Request[admin.CreateApiKeyRequest]) (*connect.Response[admin.ApiKey], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("routeiq.v1.admin.IdentityService.CreateApiKey is not implemented"))
}

func (UnimplementedIdentityServiceHandler) RevokeApiKey(context.Context, *connect.Request[admin.RevokeApiKeyRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("routeiq.v1.admin.IdentityService.RevokeApiKey is not implemented"))
}

func (UnimplementedIdentityServiceHandler) ListApiKeys(context.Context, *connect.Request[admin.ListApiKeysRequest]) (*connect.Response[admin.ListApiKeysResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("routeiq.v1.admin.IdentityService.ListApiKeys is not implemented"))
}
