// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: routeiq/v1/admin/organization.proto

package adminv1connect

import (
	admin "buf.build/gen/go/ssforge/routeiq/protocolbuffers/go/routeiq/v1/admin"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// OrganizationServiceName is the fully-qualified name of the OrganizationService service.
	OrganizationServiceName = "routeiq.v1.admin.OrganizationService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// OrganizationServiceCreateOrganizationProcedure is the fully-qualified name of the
	// OrganizationService's CreateOrganization RPC.
	OrganizationServiceCreateOrganizationProcedure = "/routeiq.v1.admin.OrganizationService/CreateOrganization"
	// OrganizationServiceGetOrganizationProcedure is the fully-qualified name of the
	// OrganizationService's GetOrganization RPC.
	OrganizationServiceGetOrganizationProcedure = "/routeiq.v1.admin.OrganizationService/GetOrganization"
	// OrganizationServiceListOrganizationsProcedure is the fully-qualified name of the
	// OrganizationService's ListOrganizations RPC.
	OrganizationServiceListOrganizationsProcedure = "/routeiq.v1.admin.OrganizationService/ListOrganizations"
	// OrganizationServiceUpdateOrganizationProcedure is the fully-qualified name of the
	// OrganizationService's UpdateOrganization RPC.
	OrganizationServiceUpdateOrganizationProcedure = "/routeiq.v1.admin.OrganizationService/UpdateOrganization"
	// OrganizationServiceDeleteOrganizationProcedure is the fully-qualified name of the
	// OrganizationService's DeleteOrganization RPC.
	OrganizationServiceDeleteOrganizationProcedure = "/routeiq.v1.admin.OrganizationService/DeleteOrganization"
	// OrganizationServiceCreateWorkspaceProcedure is the fully-qualified name of the
	// OrganizationService's CreateWorkspace RPC.
	OrganizationServiceCreateWorkspaceProcedure = "/routeiq.v1.admin.OrganizationService/CreateWorkspace"
	// OrganizationServiceListWorkspacesProcedure is the fully-qualified name of the
	// OrganizationService's ListWorkspaces RPC.
	OrganizationServiceListWorkspacesProcedure = "/routeiq.v1.admin.OrganizationService/ListWorkspaces"
	// OrganizationServiceUpdateWorkspaceProcedure is the fully-qualified name of the
	// OrganizationService's UpdateWorkspace RPC.
	OrganizationServiceUpdateWorkspaceProcedure = "/routeiq.v1.admin.OrganizationService/UpdateWorkspace"
)

// OrganizationServiceClient is a client for the routeiq.v1.admin.OrganizationService service.
type OrganizationServiceClient interface {
	CreateOrganization(context.Context, *connect.Request[admin.CreateOrganizationRequest]) (*connect.Response[admin.Organization], error)
	GetOrganization(context.Context, *connect.Request[admin.GetOrganizationRequest]) (*connect.Response[admin.Organization], error)
	ListOrganizations(context.Context, *connect.Request[admin.ListOrganizationsRequest]) (*connect.Response[admin.ListOrganizationsResponse], error)
	UpdateOrganization(context.Context, *connect.Request[admin.UpdateOrganizationRequest]) (*connect.Response[admin.Organization], error)
	DeleteOrganization(context.Context, *connect.Request[admin.DeleteOrganizationRequest]) (*connect.Response[emptypb.Empty], error)
	CreateWorkspace(context.Context, *connect.Request[admin.CreateWorkspaceRequest]) (*connect.Response[admin.Workspace], error)
	ListWorkspaces(context.Context, *connect.Request[admin.ListWorkspacesRequest]) (*connect.Response[admin.ListWorkspacesResponse], error)
	UpdateWorkspace(context.Context, *connect.Request[admin.UpdateWorkspaceRequest]) (*connect.Response[admin.Workspace], error)
}

// NewOrganizationServiceClient constructs a client for the routeiq.v1.admin.OrganizationService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewOrganizationServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) OrganizationServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	organizationServiceMethods := admin.File_routeiq_v1_admin_organization_proto.Services().ByName("OrganizationService").Methods()
	return &organizationServiceClient{
		createOrganization: connect.NewClient[admin.CreateOrganizationRequest, admin.Organization](
			httpClient,
			baseURL+OrganizationServiceCreateOrganizationProcedure,
			connect.WithSchema(organizationServiceMethods.ByName("CreateOrganization")),
			connect.WithClientOptions(opts...),
		),
		getOrganization: connect.NewClient[admin.GetOrganizationRequest, admin.Organization](
			httpClient,
			baseURL+OrganizationServiceGetOrganizationProcedure,
			connect.WithSchema(organizationServiceMethods.ByName("GetOrganization")),
			connect.WithClientOptions(opts...),
		),
		listOrganizations: connect.NewClient[admin.ListOrganizationsRequest, admin.ListOrganizationsResponse](
			httpClient,
			baseURL+OrganizationServiceListOrganizationsProcedure,
			connect.WithSchema(organizationServiceMethods.ByName("ListOrganizations")),
			connect.WithClientOptions(opts...),
		),
		updateOrganization: connect.NewClient[admin.UpdateOrganizationRequest, admin.Organization](
			httpClient,
			baseURL+OrganizationServiceUpdateOrganizationProcedure,
			connect.WithSchema(organizationServiceMethods.ByName("UpdateOrganization")),
			connect.WithClientOptions(opts...),
		),
		deleteOrganization: connect.NewClient[admin.DeleteOrganizationRequest, emptypb.Empty](
			httpClient,
			baseURL+OrganizationServiceDeleteOrganizationProcedure,
			connect.WithSchema(organizationServiceMethods.ByName("DeleteOrganization")),
			connect.WithClientOptions(opts...),
		),
		createWorkspace: connect.NewClient[admin.CreateWorkspaceRequest, admin.Workspace](
			httpClient,
			baseURL+OrganizationServiceCreateWorkspaceProcedure,
			connect.WithSchema(organizationServiceMethods.ByName("CreateWorkspace")),
			connect.WithClientOptions(opts...),
		),
		listWorkspaces: connect.NewClient[admin.ListWorkspacesRequest, admin.ListWorkspacesResponse](
			httpClient,
			baseURL+OrganizationServiceListWorkspacesProcedure,
			connect.WithSchema(organizationServiceMethods.ByName("ListWorkspaces")),
			connect.WithClientOptions(opts...),
		),
		updateWorkspace: connect.NewClient[admin.UpdateWorkspaceRequest, admin.Workspace](
			httpClient,
			baseURL+OrganizationServiceUpdateWorkspaceProcedure,
			connect.WithSchema(organizationServiceMethods.ByName("UpdateWorkspace")),
			connect.WithClientOptions(opts...),
		),
	}
}

// organizationServiceClient implements OrganizationServiceClient.
type organizationServiceClient struct {
	createOrganization *connect.Client[admin.CreateOrganizationRequest, admin.Organization]
	getOrganization    *connect.Client[admin.GetOrganizationRequest, admin.Organization]
	listOrganizations  *connect.Client[admin.ListOrganizationsRequest, admin.ListOrganizationsResponse]
	updateOrganization *connect.Client[admin.UpdateOrganizationRequest, admin.Organization]
	deleteOrganization *connect.Client[admin.DeleteOrganizationRequest, emptypb.Empty]
	createWorkspace    *connect.Client[admin.CreateWorkspaceRequest, admin.Workspace]
	listWorkspaces     *connect.Client[admin.ListWorkspacesRequest, admin.ListWorkspacesResponse]
	updateWorkspace    *connect.Client[admin.UpdateWorkspaceRequest, admin.Workspace]
}

// CreateOrganization calls routeiq.v1.admin.OrganizationService.CreateOrganization.
func (c *organizationServiceClient) CreateOrganization(ctx context.Context, req *connect.Request[admin.CreateOrganizationRequest]) (*connect.Response[admin.Organization], error) {
	return c.createOrganization.CallUnary(ctx, req)
}

// GetOrganization calls routeiq.v1.admin.OrganizationService.GetOrganization.
func (c *organizationServiceClient) GetOrganization(ctx context.Context, req *connect.Request[admin.GetOrganizationRequest]) (*connect.Response[admin.Organization], error) {
	return c.getOrganization.CallUnary(ctx, req)
}

// ListOrganizations calls routeiq.v1.admin.OrganizationService.ListOrganizations.
func (c *organizationServiceClient) ListOrganizations(ctx context.Context, req *connect.Request[admin.ListOrganizationsRequest]) (*connect.Response[admin.ListOrganizationsResponse], error) {
	return c.listOrganizations.CallUnary(ctx, req)
}

// UpdateOrganization calls routeiq.v1.admin.OrganizationService.UpdateOrganization.
func (c *organizationServiceClient) UpdateOrganization(ctx context.Context, req *connect.Request[admin.UpdateOrganizationRequest]) (*connect.Response[admin.Organization], error) {
	return c.updateOrganization.CallUnary(ctx, req)
}

// DeleteOrganization calls routeiq.v1.admin.OrganizationService.DeleteOrganization.
func (c *organizationServiceClient) DeleteOrganization(ctx context.Context, req *connect.Request[admin.DeleteOrganizationRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.deleteOrganization.CallUnary(ctx, req)
}

// CreateWorkspace calls routeiq.v1.admin.OrganizationService.CreateWorkspace.
func (c *organizationServiceClient) CreateWorkspace(ctx context.Context, req *connect.Request[admin.CreateWorkspaceRequest]) (*connect.Response[admin.Workspace], error) {
	return c.createWorkspace.CallUnary(ctx, req)
}

// ListWorkspaces calls routeiq.v1.admin.OrganizationService.ListWorkspaces.
func (c *organizationServiceClient) ListWorkspaces(ctx context.Context, req *connect.Request[admin.ListWorkspacesRequest]) (*connect.Response[admin.ListWorkspacesResponse], error) {
	return c.listWorkspaces.CallUnary(ctx, req)
}

// UpdateWorkspace calls routeiq.v1.admin.OrganizationService.UpdateWorkspace.
func (c *organizationServiceClient) UpdateWorkspace(ctx context.Context, req *connect.Request[admin.UpdateWorkspaceRequest]) (*connect.Response[admin.Workspace], error) {
	return c.updateWorkspace.CallUnary(ctx, req)
}

// OrganizationServiceHandler is an implementation of the routeiq.v1.admin.OrganizationService
// service.
type OrganizationServiceHandler interface {
	CreateOrganization(context.Context, *connect.Request[admin.CreateOrganizationRequest]) (*connect.Response[admin.Organization], error)
	GetOrganization(context.Context, *connect.Request[admin.GetOrganizationRequest]) (*connect.Response[admin.Organization], error)
	ListOrganizations(context.Context, *connect.Request[admin.ListOrganizationsRequest]) (*connect.Response[admin.ListOrganizationsResponse], error)
	UpdateOrganization(context.Context, *connect.Request[admin.UpdateOrganizationRequest]) (*connect.Response[admin.Organization], error)
	DeleteOrganization(context.Context, *connect.Request[admin.DeleteOrganizationRequest]) (*connect.Response[emptypb.Empty], error)
	CreateWorkspace(context.Context, *connect.Request[admin.CreateWorkspaceRequest]) (*connect.Response[admin.Workspace], error)
	ListWorkspaces(context.Context, *connect.Request[admin.ListWorkspacesRequest]) (*connect.Response[admin.ListWorkspacesResponse], error)
	UpdateWorkspace(context.Context, *connect.Request[admin.UpdateWorkspaceRequest]) (*connect.Response[admin.Workspace], error)
}

// NewOrganizationServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewOrganizationServiceHandler(svc OrganizationServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	organizationServiceMethods := admin.File_routeiq_v1_admin_organization_proto.Services().ByName("OrganizationService").Methods()
	organizationServiceCreateOrganizationHandler := connect.NewUnaryHandler(
		OrganizationServiceCreateOrganizationProcedure,
		svc.CreateOrganization,
		connect.WithSchema(organizationServiceMethods.ByName("CreateOrganization")),
		connect.WithHandlerOptions(opts...),
	)
	organizationServiceGetOrganizationHandler := connect.NewUnaryHandler(
		OrganizationServiceGetOrganizationProcedure,
		svc.GetOrganization,
		connect.WithSchema(organizationServiceMethods.ByName("GetOrganization")),
		connect.WithHandlerOptions(opts...),
	)
	organizationServiceListOrganizationsHandler := connect.NewUnaryHandler(
		OrganizationServiceListOrganizationsProcedure,
		svc.ListOrganizations,
		connect.WithSchema(organizationServiceMethods.ByName("ListOrganizations")),
		connect.WithHandlerOptions(opts...),
	)
	organizationServiceUpdateOrganizationHandler := connect.NewUnaryHandler(
		OrganizationServiceUpdateOrganizationProcedure,
		svc.UpdateOrganization,
		connect.WithSchema(organizationServiceMethods.ByName("UpdateOrganization")),
		connect.WithHandlerOptions(opts...),
	)
	organizationServiceDeleteOrganizationHandler := connect.NewUnaryHandler(
		OrganizationServiceDeleteOrganizationProcedure,
		svc.DeleteOrganization,
		connect.WithSchema(organizationServiceMethods.ByName("DeleteOrganization")),
		connect.WithHandlerOptions(opts...),
	)
	organizationServiceCreateWorkspaceHandler := connect.NewUnaryHandler(
		OrganizationServiceCreateWorkspaceProcedure,
		svc.CreateWorkspace,
		connect.WithSchema(organizationServiceMethods.ByName("CreateWorkspace")),
		connect.WithHandlerOptions(opts...),
	)
	organizationServiceListWorkspacesHandler := connect.NewUnaryHandler(
		OrganizationServiceListWorkspacesProcedure,
		svc.ListWorkspaces,
		connect.WithSchema(organizationServiceMethods.ByName("ListWorkspaces")),
		connect.WithHandlerOptions(opts...),
	)
	organizationServiceUpdateWorkspaceHandler := connect.NewUnaryHandler(
		OrganizationServiceUpdateWorkspaceProcedure,
		svc.UpdateWorkspace,
		connect.WithSchema(organizationServiceMethods.ByName("UpdateWorkspace")),
		connect.WithHandlerOptions(opts...),
	)
	return "/routeiq.v1.admin.OrganizationService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case OrganizationServiceCreateOrganizationProcedure:
			organizationServiceCreateOrganizationHandler.ServeHTTP(w, r)
		case OrganizationServiceGetOrganizationProcedure:
			organizationServiceGetOrganizationHandler.ServeHTTP(w, r)
		case OrganizationServiceListOrganizationsProcedure:
			organizationServiceListOrganizationsHandler.ServeHTTP(w, r)
		case OrganizationServiceUpdateOrganizationProcedure:
			organizationServiceUpdateOrganizationHandler.ServeHTTP(w, r)
		case OrganizationServiceDeleteOrganizationProcedure:
			organizationServiceDeleteOrganizationHandler.ServeHTTP(w, r)
		case OrganizationServiceCreateWorkspaceProcedure:
			organizationServiceCreateWorkspaceHandler.ServeHTTP(w, r)
		case OrganizationServiceListWorkspacesProcedure:
			organizationServiceListWorkspacesHandler.ServeHTTP(w, r)
		case OrganizationServiceUpdateWorkspaceProcedure:
			organizationServiceUpdateWorkspaceHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedOrganizationServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedOrganizationServiceHandler struct{}

func (UnimplementedOrganizationServiceHandler) CreateOrganization(context.Context, *connect.Request[admin.CreateOrganizationRequest]) (*connect.Response[admin.Organization], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("routeiq.v1.admin.OrganizationService.CreateOrganization is not implemented"))
}

func (UnimplementedOrganizationServiceHandler) GetOrganization(context.Context, *connect.Request[admin.GetOrganizationRequest]) (*connect.Response[admin.Organization], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("routeiq.v1.admin.OrganizationService.GetOrganization is not implemented"))
}

func (UnimplementedOrganizationServiceHandler) ListOrganizations(context.Context, *connect.Request[admin.ListOrganizationsRequest]) (*connect.Response[admin.ListOrganizationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("routeiq.v1.admin.OrganizationService.ListOrganizations is not implemented"))
}

func (UnimplementedOrganizationServiceHandler) UpdateOrganization(context.Context, *connect.Request[admin.UpdateOrganizationRequest]) (*connect.Response[admin.Organization], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("routeiq.v1.admin.OrganizationService.UpdateOrganization is not implemented"))
}

func (UnimplementedOrganizationServiceHandler) DeleteOrganization(context.Context, *connect.Request[admin.DeleteOrganizationRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("routeiq.v1.admin.OrganizationService.DeleteOrganization is not implemented"))
}

func (UnimplementedOrganizationServiceHandler) CreateWorkspace(context.Context, *connect.Request[admin.CreateWorkspaceRequest]) (*connect.Response[admin.Workspace], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("routeiq.v1.admin.OrganizationService.CreateWorkspace is not implemented"))
}

func (UnimplementedOrganizationServiceHandler) ListWorkspaces(context.Context, *connect.Request[admin.ListWorkspacesRequest]) (*connect.Response[admin.ListWorkspacesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("routeiq.v1.admin.OrganizationService.ListWorkspaces is not implemented"))
}

func (UnimplementedOrganizationServiceHandler) UpdateWorkspace(context.Context, *connect.Request[admin.UpdateWorkspaceRequest]) (*connect.Response[admin.Workspace], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("routeiq.v1.admin.OrganizationService.UpdateWorkspace is not implemented"))
}
