// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: routeiq/v1/admin/policy.proto

package adminv1connect

import (
	admin "buf.build/gen/go/ssforge/routeiq/protocolbuffers/go/routeiq/v1/admin"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// PolicyServiceName is the fully-qualified name of the PolicyService service.
	PolicyServiceName = "routeiq.v1.admin.PolicyService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PolicyServiceCreatePolicyBundleProcedure is the fully-qualified name of the PolicyService's
	// CreatePolicyBundle RPC.
	PolicyServiceCreatePolicyBundleProcedure = "/routeiq.v1.admin.PolicyService/CreatePolicyBundle"
	// PolicyServiceGetPolicyBundleProcedure is the fully-qualified name of the PolicyService's
	// GetPolicyBundle RPC.
	PolicyServiceGetPolicyBundleProcedure = "/routeiq.v1.admin.PolicyService/GetPolicyBundle"
	// PolicyServiceListPolicyBundlesProcedure is the fully-qualified name of the PolicyService's
	// ListPolicyBundles RPC.
	PolicyServiceListPolicyBundlesProcedure = "/routeiq.v1.admin.PolicyService/ListPolicyBundles"
	// PolicyServiceActivatePolicyBundleProcedure is the fully-qualified name of the PolicyService's
	// ActivatePolicyBundle RPC.
	PolicyServiceActivatePolicyBundleProcedure = "/routeiq.v1.admin.PolicyService/ActivatePolicyBundle"
	// PolicyServiceDeletePolicyBundleProcedure is the fully-qualified name of the PolicyService's
	// DeletePolicyBundle RPC.
	PolicyServiceDeletePolicyBundleProcedure = "/routeiq.v1.admin.PolicyService/DeletePolicyBundle"
)

// PolicyServiceClient is a client for the routeiq.v1.admin.PolicyService service.
type PolicyServiceClient interface {
	CreatePolicyBundle(context.Context, *connect.Request[admin.CreatePolicyBundleRequest]) (*connect.Response[admin.PolicyBundle], error)
	GetPolicyBundle(context.Context, *connect.Request[admin.GetPolicyBundleRequest]) (*connect.Response[admin.PolicyBundle], error)
	ListPolicyBundles(context.Context, *connect.Request[admin.ListPolicyBundlesRequest]) (*connect.Response[admin.ListPolicyBundlesResponse], error)
	ActivatePolicyBundle(context.Context, *connect.Request[admin.ActivatePolicyBundleRequest]) (*connect.Response[admin.PolicyBundle], error)
	DeletePolicyBundle(context.Context, *connect.Request[admin.DeletePolicyBundleRequest]) (*connect.Response[emptypb.Empty], error)
}

// NewPolicyServiceClient constructs a client for the routeiq.v1.admin.PolicyService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPolicyServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PolicyServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	policyServiceMethods := admin.File_routeiq_v1_admin_policy_proto.Services().ByName("PolicyService").Methods()
	return &policyServiceClient{
		createPolicyBundle: connect.NewClient[admin.CreatePolicyBundleRequest, admin.PolicyBundle](
			httpClient,
			baseURL+PolicyServiceCreatePolicyBundleProcedure,
			connect.WithSchema(policyServiceMethods.ByName("CreatePolicyBundle")),
			connect.WithClientOptions(opts...),
		),
		getPolicyBundle: connect.NewClient[admin.GetPolicyBundleRequest, admin.PolicyBundle](
			httpClient,
			baseURL+PolicyServiceGetPolicyBundleProcedure,
			connect.WithSchema(policyServiceMethods.ByName("GetPolicyBundle")),
			connect.WithClientOptions(opts...),
		),
		listPolicyBundles: connect.NewClient[admin.ListPolicyBundlesRequest, admin.ListPolicyBundlesResponse](
			httpClient,
			baseURL+PolicyServiceListPolicyBundlesProcedure,
			connect.WithSchema(policyServiceMethods.ByName("ListPolicyBundles")),
			connect.WithClientOptions(opts...),
		),
		activatePolicyBundle: connect.NewClient[admin.ActivatePolicyBundleRequest, admin.PolicyBundle](
			httpClient,
			baseURL+PolicyServiceActivatePolicyBundleProcedure,
			connect.WithSchema(policyServiceMethods.ByName("ActivatePolicyBundle")),
			connect.WithClientOptions(opts...),
		),
		deletePolicyBundle: connect.NewClient[admin.DeletePolicyBundleRequest, emptypb.Empty](
			httpClient,
			baseURL+PolicyServiceDeletePolicyBundleProcedure,
			connect.WithSchema(policyServiceMethods.ByName("DeletePolicyBundle")),
			connect.WithClientOptions(opts...),
		),
	}
}

// policyServiceClient implements PolicyServiceClient.
type policyServiceClient struct {
	createPolicyBundle   *connect.Client[admin.CreatePolicyBundleRequest, admin.PolicyBundle]
	getPolicyBundle      *connect.Client[admin.GetPolicyBundleRequest, admin.PolicyBundle]
	listPolicyBundles    *connect.Client[admin.ListPolicyBundlesRequest, admin.ListPolicyBundlesResponse]
	activatePolicyBundle *connect.Client[admin.ActivatePolicyBundleRequest, admin.PolicyBundle]
	deletePolicyBundle   *connect.Client[admin.DeletePolicyBundleRequest, emptypb.Empty]
}

// CreatePolicyBundle calls routeiq.v1.admin.PolicyService.CreatePolicyBundle.
func (c *policyServiceClient) CreatePolicyBundle(ctx context.Context, req *connect.Request[admin.CreatePolicyBundleRequest]) (*connect.Response[admin.PolicyBundle], error) {
	return c.createPolicyBundle.CallUnary(ctx, req)
}

// GetPolicyBundle calls routeiq.v1.admin.PolicyService.GetPolicyBundle.
func (c *policyServiceClient) GetPolicyBundle(ctx context.Context, req *connect.Request[admin.GetPolicyBundleRequest]) (*connect.Response[admin.PolicyBundle], error) {
	return c.getPolicyBundle.CallUnary(ctx, req)
}

// ListPolicyBundles calls routeiq.v1.admin.PolicyService.ListPolicyBundles.
func (c *policyServiceClient) ListPolicyBundles(ctx context.Context, req *connect.Request[admin.ListPolicyBundlesRequest]) (*connect.Response[admin.ListPolicyBundlesResponse], error) {
	return c.listPolicyBundles.CallUnary(ctx, req)
}

// ActivatePolicyBundle calls routeiq.v1.admin.PolicyService.ActivatePolicyBundle.
func (c *policyServiceClient) ActivatePolicyBundle(ctx context.Context, req *connect.Request[admin.ActivatePolicyBundleRequest]) (*connect.Response[admin.PolicyBundle], error) {
	return c.activatePolicyBundle.CallUnary(ctx, req)
}

// DeletePolicyBundle calls routeiq.v1.admin.PolicyService.DeletePolicyBundle.
func (c *policyServiceClient) DeletePolicyBundle(ctx context.Context, req *connect.Request[admin.DeletePolicyBundleRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.deletePolicyBundle.CallUnary(ctx, req)
}

// PolicyServiceHandler is an implementation of the routeiq.v1.admin.PolicyService service.
type PolicyServiceHandler interface {
	CreatePolicyBundle(context.Context, *connect.Request[admin.CreatePolicyBundleRequest]) (*connect.Response[admin.PolicyBundle], error)
	GetPolicyBundle(context.Context, *connect.Request[admin.GetPolicyBundleRequest]) (*connect.Response[admin.PolicyBundle], error)
	ListPolicyBundles(context.Context, *connect.Request[admin.ListPolicyBundlesRequest]) (*connect.Response[admin.ListPolicyBundlesResponse], error)
	ActivatePolicyBundle(context.Context, *connect.Request[admin.ActivatePolicyBundleRequest]) (*connect.Response[admin.PolicyBundle], error)
	DeletePolicyBundle(context.Context, *connect.Request[admin.DeletePolicyBundleRequest]) (*connect.Response[emptypb.Empty], error)
}

// NewPolicyServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPolicyServiceHandler(svc PolicyServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	policyServiceMethods := admin.File_routeiq_v1_admin_policy_proto.Services().ByName("PolicyService").Methods()
	policyServiceCreatePolicyBundleHandler := connect.NewUnaryHandler(
		PolicyServiceCreatePolicyBundleProcedure,
		svc.CreatePolicyBundle,
		connect.WithSchema(policyServiceMethods.ByName("CreatePolicyBundle")),
		connect.WithHandlerOptions(opts...),
	)
	policyServiceGetPolicyBundleHandler := connect.NewUnaryHandler(
		PolicyServiceGetPolicyBundleProcedure,
		svc.GetPolicyBundle,
		connect.WithSchema(policyServiceMethods.ByName("GetPolicyBundle")),
		connect.WithHandlerOptions(opts...),
	)
	policyServiceListPolicyBundlesHandler := connect.NewUnaryHandler(
		PolicyServiceListPolicyBundlesProcedure,
		svc.ListPolicyBundles,
		connect.WithSchema(policyServiceMethods.ByName("ListPolicyBundles")),
		connect.WithHandlerOptions(opts...),
	)
	policyServiceActivatePolicyBundleHandler := connect.NewUnaryHandler(
		PolicyServiceActivatePolicyBundleProcedure,
		svc.ActivatePolicyBundle,
		connect.WithSchema(policyServiceMethods.ByName("ActivatePolicyBundle")),
		connect.WithHandlerOptions(opts...),
	)
	policyServiceDeletePolicyBundleHandler := connect.NewUnaryHandler(
		PolicyServiceDeletePolicyBundleProcedure,
		svc.DeletePolicyBundle,
		connect.WithSchema(policyServiceMethods.ByName("DeletePolicyBundle")),
		connect.WithHandlerOptions(opts...),
	)
	return "/routeiq.v1.admin.PolicyService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PolicyServiceCreatePolicyBundleProcedure:
			policyServiceCreatePolicyBundleHandler.ServeHTTP(w, r)
		case PolicyServiceGetPolicyBundleProcedure:
			policyServiceGetPolicyBundleHandler.ServeHTTP(w, r)
		case PolicyServiceListPolicyBundlesProcedure:
			policyServiceListPolicyBundlesHandler.ServeHTTP(w, r)
		case PolicyServiceActivatePolicyBundleProcedure:
			policyServiceActivatePolicyBundleHandler.ServeHTTP(w, r)
		case PolicyServiceDeletePolicyBundleProcedure:
			policyServiceDeletePolicyBundleHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPolicyServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPolicyServiceHandler struct{}

func (UnimplementedPolicyServiceHandler) CreatePolicyBundle(context.Context, *connect.Request[admin.CreatePolicyBundleRequest]) (*connect.Response[admin.PolicyBundle], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("routeiq.v1.admin.PolicyService.CreatePolicyBundle is not implemented"))
}

func (UnimplementedPolicyServiceHandler) GetPolicyBundle(context.Context, *connect.Request[admin.GetPolicyBundleRequest]) (*connect.Response[admin.PolicyBundle], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("routeiq.v1.admin.PolicyService.GetPolicyBundle is not implemented"))
}

func (UnimplementedPolicyServiceHandler) ListPolicyBundles(context.Context, *connect.Request[admin.ListPolicyBundlesRequest]) (*connect.Response[admin.ListPolicyBundlesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("routeiq.v1.admin.PolicyService.ListPolicyBundles is not implemented"))
}

func (UnimplementedPolicyServiceHandler) ActivatePolicyBundle(context.Context, *connect.Request[admin.ActivatePolicyBundleRequest]) (*connect.Response[admin.PolicyBundle], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("routeiq.v1.admin.PolicyService.ActivatePolicyBundle is not implemented"))
}

func (UnimplementedPolicyServiceHandler) DeletePolicyBundle(context.Context, *connect.Request[admin.DeletePolicyBundleRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("routeiq.v1.admin.PolicyService.DeletePolicyBundle is not implemented"))
}
