// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: routeiq/v1/admin/slo_config.proto

package adminv1connect

import (
	admin "buf.build/gen/go/ssforge/routeiq/protocolbuffers/go/routeiq/v1/admin"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SloConfigServiceName is the fully-qualified name of the SloConfigService service.
	SloConfigServiceName = "routeiq.v1.admin.SloConfigService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SloConfigServiceGetSloOverridesProcedure is the fully-qualified name of the SloConfigService's
	// GetSloOverrides RPC.
	SloConfigServiceGetSloOverridesProcedure = "/routeiq.v1.admin.SloConfigService/GetSloOverrides"
	// SloConfigServiceSetSloOverrideProcedure is the fully-qualified name of the SloConfigService's
	// SetSloOverride RPC.
	SloConfigServiceSetSloOverrideProcedure = "/routeiq.v1.admin.SloConfigService/SetSloOverride"
	// SloConfigServiceDeleteSloOverrideProcedure is the fully-qualified name of the SloConfigService's
	// DeleteSloOverride RPC.
	SloConfigServiceDeleteSloOverrideProcedure = "/routeiq.v1.admin.SloConfigService/DeleteSloOverride"
)

// SloConfigServiceClient is a client for the routeiq.v1.admin.SloConfigService service.
type SloConfigServiceClient interface {
	GetSloOverrides(context.Context, *connect.Request[admin.GetSloOverridesRequest]) (*connect.Response[admin.SloOverrides], error)
	SetSloOverride(context.Context, *connect.Request[admin.SetSloOverrideRequest]) (*connect.Response[admin.SloOverride], error)
	DeleteSloOverride(context.Context, *connect.Request[admin.DeleteSloOverrideRequest]) (*connect.Response[admin.SloOverrides], error)
}

// NewSloConfigServiceClient constructs a client for the routeiq.v1.admin.SloConfigService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSloConfigServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SloConfigServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	sloConfigServiceMethods := admin.File_routeiq_v1_admin_slo_config_proto.Services().ByName("SloConfigService").Methods()
	return &sloConfigServiceClient{
		getSloOverrides: connect.NewClient[admin.GetSloOverridesRequest, admin.SloOverrides](
			httpClient,
			baseURL+SloConfigServiceGetSloOverridesProcedure,
			connect.WithSchema(sloConfigServiceMethods.ByName("GetSloOverrides")),
			connect.WithClientOptions(opts...),
		),
		setSloOverride: connect.NewClient[admin.SetSloOverrideRequest, admin.SloOverride](
			httpClient,
			baseURL+SloConfigServiceSetSloOverrideProcedure,
			connect.WithSchema(sloConfigServiceMethods.ByName("SetSloOverride")),
			connect.WithClientOptions(opts...),
		),
		deleteSloOverride: connect.NewClient[admin.DeleteSloOverrideRequest, admin.SloOverrides](
			httpClient,
			baseURL+SloConfigServiceDeleteSloOverrideProcedure,
			connect.WithSchema(sloConfigServiceMethods.ByName("DeleteSloOverride")),
			connect.WithClientOptions(opts...),
		),
	}
}

// sloConfigServiceClient implements SloConfigServiceClient.
type sloConfigServiceClient struct {
	getSloOverrides   *connect.Client[admin.GetSloOverridesRequest, admin.SloOverrides]
	setSloOverride    *connect.Client[admin.SetSloOverrideRequest, admin.SloOverride]
	deleteSloOverride *connect.Client[admin.DeleteSloOverrideRequest, admin.SloOverrides]
}

// GetSloOverrides calls routeiq.v1.admin.SloConfigService.GetSloOverrides.
func (c *sloConfigServiceClient) GetSloOverrides(ctx context.Context, req *connect.Request[admin.GetSloOverridesRequest]) (*connect.Response[admin.SloOverrides], error) {
	return c.getSloOverrides.CallUnary(ctx, req)
}

// SetSloOverride calls routeiq.v1.admin.SloConfigService.SetSloOverride.
func (c *sloConfigServiceClient) SetSloOverride(ctx context.Context, req *connect.Request[admin.SetSloOverrideRequest]) (*connect.Response[admin.SloOverride], error) {
	return c.setSloOverride.CallUnary(ctx, req)
}

// DeleteSloOverride calls routeiq.v1.admin.SloConfigService.DeleteSloOverride.
func (c *sloConfigServiceClient) DeleteSloOverride(ctx context.Context, req *connect.Request[admin.DeleteSloOverrideRequest]) (*connect.Response[admin.SloOverrides], error) {
	return c.deleteSloOverride.CallUnary(ctx, req)
}

// SloConfigServiceHandler is an implementation of the routeiq.v1.admin.SloConfigService service.
type SloConfigServiceHandler interface {
	GetSloOverrides(context.Context, *connect.Request[admin.GetSloOverridesRequest]) (*connect.Response[admin.SloOverrides], error)
	SetSloOverride(context.Context, *connect.Request[admin.SetSloOverrideRequest]) (*connect.Response[admin.SloOverride], error)
	DeleteSloOverride(context.Context, *connect.Request[admin.DeleteSloOverrideRequest]) (*connect.Response[admin.SloOverrides], error)
}

// NewSloConfigServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSloConfigServiceHandler(svc SloConfigServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	sloConfigServiceMethods := admin.File_routeiq_v1_admin_slo_config_proto.Services().ByName("SloConfigService").Methods()
	sloConfigServiceGetSloOverridesHandler := connect.NewUnaryHandler(
		SloConfigServiceGetSloOverridesProcedure,
		svc.GetSloOverrides,
		connect.WithSchema(sloConfigServiceMethods.ByName("GetSloOverrides")),
		connect.WithHandlerOptions(opts...),
	)
	sloConfigServiceSetSloOverrideHandler := connect.NewUnaryHandler(
		SloConfigServiceSetSloOverrideProcedure,
		svc.SetSloOverride,
		connect.WithSchema(sloConfigServiceMethods.ByName("SetSloOverride")),
		connect.WithHandlerOptions(opts...),
	)
	sloConfigServiceDeleteSloOverrideHandler := connect.NewUnaryHandler(
		SloConfigServiceDeleteSloOverrideProcedure,
		svc.DeleteSloOverride,
		connect.WithSchema(sloConfigServiceMethods.ByName("DeleteSloOverride")),
		connect.WithHandlerOptions(opts...),
	)
	return "/routeiq.v1.admin.SloConfigService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SloConfigServiceGetSloOverridesProcedure:
			sloConfigServiceGetSloOverridesHandler.ServeHTTP(w, r)
		case SloConfigServiceSetSloOverrideProcedure:
			sloConfigServiceSetSloOverrideHandler.ServeHTTP(w, r)
		case SloConfigServiceDeleteSloOverrideProcedure:
			sloConfigServiceDeleteSloOverrideHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSloConfigServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSloConfigServiceHandler struct{}

func (UnimplementedSloConfigServiceHandler) GetSloOverrides(context.Context, *connect.Request[admin.GetSloOverridesRequest]) (*connect.Response[admin.SloOverrides], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("routeiq.v1.admin.SloConfigService.GetSloOverrides is not implemented"))
}

func (UnimplementedSloConfigServiceHandler) SetSloOverride(context.Context, *connect.Request[admin.SetSloOverrideRequest]) (*connect.Response[admin.SloOverride], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("routeiq.v1.admin.SloConfigService.SetSloOverride is not implemented"))
}

func (UnimplementedSloConfigServiceHandler) DeleteSloOverride(context.Context, *connect.Request[admin.DeleteSloOverrideRequest]) (*connect.Response[admin.SloOverrides], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("routeiq.v1.admin.SloConfigService.DeleteSloOverride is not implemented"))
}
