// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: routeiq/v1/metrics/definitions.proto

package metricsv1

import (
	telemetry "buf.build/gen/go/ssforge/routeiq/protocolbuffers/go/routeiq/v1/telemetry"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Layer int32

const (
	Layer_LAYER_UNSPECIFIED      Layer = 0
	Layer_LAYER_0_RUNTIME        Layer = 1
	Layer_LAYER_1_AGENT_BEHAVIOR Layer = 2
	Layer_LAYER_2_QUALITY        Layer = 3
	Layer_LAYER_3_BUSINESS       Layer = 4
	Layer_LAYER_4_GOVERNANCE     Layer = 5
)

// Enum value maps for Layer.
var (
	Layer_name = map[int32]string{
		0: "LAYER_UNSPECIFIED",
		1: "LAYER_0_RUNTIME",
		2: "LAYER_1_AGENT_BEHAVIOR",
		3: "LAYER_2_QUALITY",
		4: "LAYER_3_BUSINESS",
		5: "LAYER_4_GOVERNANCE",
	}
	Layer_value = map[string]int32{
		"LAYER_UNSPECIFIED":      0,
		"LAYER_0_RUNTIME":        1,
		"LAYER_1_AGENT_BEHAVIOR": 2,
		"LAYER_2_QUALITY":        3,
		"LAYER_3_BUSINESS":       4,
		"LAYER_4_GOVERNANCE":     5,
	}
)

func (x Layer) Enum() *Layer {
	p := new(Layer)
	*p = x
	return p
}

func (x Layer) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Layer) Descriptor() protoreflect.EnumDescriptor {
	return file_routeiq_v1_metrics_definitions_proto_enumTypes[0].Descriptor()
}

func (Layer) Type() protoreflect.EnumType {
	return &file_routeiq_v1_metrics_definitions_proto_enumTypes[0]
}

func (x Layer) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Layer.Descriptor instead.
func (Layer) EnumDescriptor() ([]byte, []int) {
	return file_routeiq_v1_metrics_definitions_proto_rawDescGZIP(), []int{0}
}

type EvidenceClass int32

const (
	EvidenceClass_EVIDENCE_UNSPECIFIED EvidenceClass = 0
	EvidenceClass_OTEL_DIRECT          EvidenceClass = 1
	EvidenceClass_HEURISTIC            EvidenceClass = 2
	EvidenceClass_SEMANTIC             EvidenceClass = 3
	EvidenceClass_FRONTIER             EvidenceClass = 4
)

// Enum value maps for EvidenceClass.
var (
	EvidenceClass_name = map[int32]string{
		0: "EVIDENCE_UNSPECIFIED",
		1: "OTEL_DIRECT",
		2: "HEURISTIC",
		3: "SEMANTIC",
		4: "FRONTIER",
	}
	EvidenceClass_value = map[string]int32{
		"EVIDENCE_UNSPECIFIED": 0,
		"OTEL_DIRECT":          1,
		"HEURISTIC":            2,
		"SEMANTIC":             3,
		"FRONTIER":             4,
	}
)

func (x EvidenceClass) Enum() *EvidenceClass {
	p := new(EvidenceClass)
	*p = x
	return p
}

func (x EvidenceClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EvidenceClass) Descriptor() protoreflect.EnumDescriptor {
	return file_routeiq_v1_metrics_definitions_proto_enumTypes[1].Descriptor()
}

func (EvidenceClass) Type() protoreflect.EnumType {
	return &file_routeiq_v1_metrics_definitions_proto_enumTypes[1]
}

func (x EvidenceClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EvidenceClass.Descriptor instead.
func (EvidenceClass) EnumDescriptor() ([]byte, []int) {
	return file_routeiq_v1_metrics_definitions_proto_rawDescGZIP(), []int{1}
}

type Aggregation int32

const (
	Aggregation_AGGREGATION_UNSPECIFIED Aggregation = 0
	Aggregation_AVG                     Aggregation = 1
	Aggregation_SUM                     Aggregation = 2
	Aggregation_COUNT                   Aggregation = 3
	Aggregation_RATE                    Aggregation = 4
	Aggregation_P50                     Aggregation = 5
	Aggregation_P90                     Aggregation = 6
	Aggregation_P95                     Aggregation = 7
	Aggregation_P99                     Aggregation = 8
	Aggregation_MAX                     Aggregation = 9
	Aggregation_MIN                     Aggregation = 10
	Aggregation_LAST                    Aggregation = 11
)

// Enum value maps for Aggregation.
var (
	Aggregation_name = map[int32]string{
		0:  "AGGREGATION_UNSPECIFIED",
		1:  "AVG",
		2:  "SUM",
		3:  "COUNT",
		4:  "RATE",
		5:  "P50",
		6:  "P90",
		7:  "P95",
		8:  "P99",
		9:  "MAX",
		10: "MIN",
		11: "LAST",
	}
	Aggregation_value = map[string]int32{
		"AGGREGATION_UNSPECIFIED": 0,
		"AVG":                     1,
		"SUM":                     2,
		"COUNT":                   3,
		"RATE":                    4,
		"P50":                     5,
		"P90":                     6,
		"P95":                     7,
		"P99":                     8,
		"MAX":                     9,
		"MIN":                     10,
		"LAST":                    11,
	}
)

func (x Aggregation) Enum() *Aggregation {
	p := new(Aggregation)
	*p = x
	return p
}

func (x Aggregation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Aggregation) Descriptor() protoreflect.EnumDescriptor {
	return file_routeiq_v1_metrics_definitions_proto_enumTypes[2].Descriptor()
}

func (Aggregation) Type() protoreflect.EnumType {
	return &file_routeiq_v1_metrics_definitions_proto_enumTypes[2]
}

func (x Aggregation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Aggregation.Descriptor instead.
func (Aggregation) EnumDescriptor() ([]byte, []int) {
	return file_routeiq_v1_metrics_definitions_proto_rawDescGZIP(), []int{2}
}

// MetricDefinition is the canonical declaration of a single derived metric.
// Lives in routeiq-catalog as YAML; this proto defines the shape only.
type MetricDefinition struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName        string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description        string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Layer              Layer                  `protobuf:"varint,4,opt,name=layer,proto3,enum=routeiq.v1.metrics.Layer" json:"layer,omitempty"`
	EvidenceClass      EvidenceClass          `protobuf:"varint,5,opt,name=evidence_class,json=evidenceClass,proto3,enum=routeiq.v1.metrics.EvidenceClass" json:"evidence_class,omitempty"`
	Inputs             []*MetricInput         `protobuf:"bytes,6,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Formula            *Formula               `protobuf:"bytes,7,opt,name=formula,proto3" json:"formula,omitempty"`
	Unit               string                 `protobuf:"bytes,8,opt,name=unit,proto3" json:"unit,omitempty"`
	DefaultAggregation Aggregation            `protobuf:"varint,9,opt,name=default_aggregation,json=defaultAggregation,proto3,enum=routeiq.v1.metrics.Aggregation" json:"default_aggregation,omitempty"`
	SloTemplates       []*SloTemplate         `protobuf:"bytes,10,rep,name=slo_templates,json=sloTemplates,proto3" json:"slo_templates,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MetricDefinition) Reset() {
	*x = MetricDefinition{}
	mi := &file_routeiq_v1_metrics_definitions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricDefinition) ProtoMessage() {}

func (x *MetricDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_metrics_definitions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricDefinition.ProtoReflect.Descriptor instead.
func (*MetricDefinition) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_metrics_definitions_proto_rawDescGZIP(), []int{0}
}

func (x *MetricDefinition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MetricDefinition) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *MetricDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MetricDefinition) GetLayer() Layer {
	if x != nil {
		return x.Layer
	}
	return Layer_LAYER_UNSPECIFIED
}

func (x *MetricDefinition) GetEvidenceClass() EvidenceClass {
	if x != nil {
		return x.EvidenceClass
	}
	return EvidenceClass_EVIDENCE_UNSPECIFIED
}

func (x *MetricDefinition) GetInputs() []*MetricInput {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *MetricDefinition) GetFormula() *Formula {
	if x != nil {
		return x.Formula
	}
	return nil
}

func (x *MetricDefinition) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *MetricDefinition) GetDefaultAggregation() Aggregation {
	if x != nil {
		return x.DefaultAggregation
	}
	return Aggregation_AGGREGATION_UNSPECIFIED
}

func (x *MetricDefinition) GetSloTemplates() []*SloTemplate {
	if x != nil {
		return x.SloTemplates
	}
	return nil
}

type MetricInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventTypes    []telemetry.EventType  `protobuf:"varint,1,rep,packed,name=event_types,json=eventTypes,proto3,enum=routeiq.v1.telemetry.EventType" json:"event_types,omitempty"`
	FieldPaths    []string               `protobuf:"bytes,2,rep,name=field_paths,json=fieldPaths,proto3" json:"field_paths,omitempty"`
	Filter        string                 `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricInput) Reset() {
	*x = MetricInput{}
	mi := &file_routeiq_v1_metrics_definitions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricInput) ProtoMessage() {}

func (x *MetricInput) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_metrics_definitions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricInput.ProtoReflect.Descriptor instead.
func (*MetricInput) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_metrics_definitions_proto_rawDescGZIP(), []int{1}
}

func (x *MetricInput) GetEventTypes() []telemetry.EventType {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

func (x *MetricInput) GetFieldPaths() []string {
	if x != nil {
		return x.FieldPaths
	}
	return nil
}

func (x *MetricInput) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

type SloTemplate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tier          string                 `protobuf:"bytes,1,opt,name=tier,proto3" json:"tier,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SloTemplate) Reset() {
	*x = SloTemplate{}
	mi := &file_routeiq_v1_metrics_definitions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SloTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SloTemplate) ProtoMessage() {}

func (x *SloTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_metrics_definitions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SloTemplate.ProtoReflect.Descriptor instead.
func (*SloTemplate) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_metrics_definitions_proto_rawDescGZIP(), []int{2}
}

func (x *SloTemplate) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

func (x *SloTemplate) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

// Formula is the computation declaration for a metric. Exactly one kind is set.
type Formula struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Formula_Deterministic
	//	*Formula_Heuristic
	//	*Formula_Semantic
	//	*Formula_Frontier
	Kind          isFormula_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Formula) Reset() {
	*x = Formula{}
	mi := &file_routeiq_v1_metrics_definitions_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Formula) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Formula) ProtoMessage() {}

func (x *Formula) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_metrics_definitions_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Formula.ProtoReflect.Descriptor instead.
func (*Formula) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_metrics_definitions_proto_rawDescGZIP(), []int{3}
}

func (x *Formula) GetKind() isFormula_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Formula) GetDeterministic() *DeterministicFormula {
	if x != nil {
		if x, ok := x.Kind.(*Formula_Deterministic); ok {
			return x.Deterministic
		}
	}
	return nil
}

func (x *Formula) GetHeuristic() *HeuristicFormula {
	if x != nil {
		if x, ok := x.Kind.(*Formula_Heuristic); ok {
			return x.Heuristic
		}
	}
	return nil
}

func (x *Formula) GetSemantic() *SemanticFormula {
	if x != nil {
		if x, ok := x.Kind.(*Formula_Semantic); ok {
			return x.Semantic
		}
	}
	return nil
}

func (x *Formula) GetFrontier() *FrontierFormula {
	if x != nil {
		if x, ok := x.Kind.(*Formula_Frontier); ok {
			return x.Frontier
		}
	}
	return nil
}

type isFormula_Kind interface {
	isFormula_Kind()
}

type Formula_Deterministic struct {
	Deterministic *DeterministicFormula `protobuf:"bytes,1,opt,name=deterministic,proto3,oneof"`
}

type Formula_Heuristic struct {
	Heuristic *HeuristicFormula `protobuf:"bytes,2,opt,name=heuristic,proto3,oneof"`
}

type Formula_Semantic struct {
	Semantic *SemanticFormula `protobuf:"bytes,3,opt,name=semantic,proto3,oneof"`
}

type Formula_Frontier struct {
	Frontier *FrontierFormula `protobuf:"bytes,4,opt,name=frontier,proto3,oneof"`
}

func (*Formula_Deterministic) isFormula_Kind() {}

func (*Formula_Heuristic) isFormula_Kind() {}

func (*Formula_Semantic) isFormula_Kind() {}

func (*Formula_Frontier) isFormula_Kind() {}

type DeterministicFormula struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expression    string                 `protobuf:"bytes,1,opt,name=expression,proto3" json:"expression,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeterministicFormula) Reset() {
	*x = DeterministicFormula{}
	mi := &file_routeiq_v1_metrics_definitions_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeterministicFormula) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeterministicFormula) ProtoMessage() {}

func (x *DeterministicFormula) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_metrics_definitions_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeterministicFormula.ProtoReflect.Descriptor instead.
func (*DeterministicFormula) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_metrics_definitions_proto_rawDescGZIP(), []int{4}
}

func (x *DeterministicFormula) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

type HeuristicFormula struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DetectorId    string                 `protobuf:"bytes,1,opt,name=detector_id,json=detectorId,proto3" json:"detector_id,omitempty"`
	Parameters    map[string]string      `protobuf:"bytes,2,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeuristicFormula) Reset() {
	*x = HeuristicFormula{}
	mi := &file_routeiq_v1_metrics_definitions_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeuristicFormula) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeuristicFormula) ProtoMessage() {}

func (x *HeuristicFormula) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_metrics_definitions_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeuristicFormula.ProtoReflect.Descriptor instead.
func (*HeuristicFormula) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_metrics_definitions_proto_rawDescGZIP(), []int{5}
}

func (x *HeuristicFormula) GetDetectorId() string {
	if x != nil {
		return x.DetectorId
	}
	return ""
}

func (x *HeuristicFormula) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type SemanticFormula struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClassifierId  string                 `protobuf:"bytes,1,opt,name=classifier_id,json=classifierId,proto3" json:"classifier_id,omitempty"`
	Operation     string                 `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SemanticFormula) Reset() {
	*x = SemanticFormula{}
	mi := &file_routeiq_v1_metrics_definitions_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SemanticFormula) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SemanticFormula) ProtoMessage() {}

func (x *SemanticFormula) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_metrics_definitions_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SemanticFormula.ProtoReflect.Descriptor instead.
func (*SemanticFormula) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_metrics_definitions_proto_rawDescGZIP(), []int{6}
}

func (x *SemanticFormula) GetClassifierId() string {
	if x != nil {
		return x.ClassifierId
	}
	return ""
}

func (x *SemanticFormula) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

type FrontierFormula struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JudgeModel    string                 `protobuf:"bytes,1,opt,name=judge_model,json=judgeModel,proto3" json:"judge_model,omitempty"`
	RubricId      string                 `protobuf:"bytes,2,opt,name=rubric_id,json=rubricId,proto3" json:"rubric_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrontierFormula) Reset() {
	*x = FrontierFormula{}
	mi := &file_routeiq_v1_metrics_definitions_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrontierFormula) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrontierFormula) ProtoMessage() {}

func (x *FrontierFormula) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_metrics_definitions_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrontierFormula.ProtoReflect.Descriptor instead.
func (*FrontierFormula) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_metrics_definitions_proto_rawDescGZIP(), []int{7}
}

func (x *FrontierFormula) GetJudgeModel() string {
	if x != nil {
		return x.JudgeModel
	}
	return ""
}

func (x *FrontierFormula) GetRubricId() string {
	if x != nil {
		return x.RubricId
	}
	return ""
}

var File_routeiq_v1_metrics_definitions_proto protoreflect.FileDescriptor

const file_routeiq_v1_metrics_definitions_proto_rawDesc = "" +
	"\n" +
	"$routeiq/v1/metrics/definitions.proto\x12\x12routeiq.v1.metrics\x1a!routeiq/v1/telemetry/events.proto\"\xfe\x03\n" +
	"\x10MetricDefinition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12/\n" +
	"\x05layer\x18\x04 \x01(\x0e2\x19.routeiq.v1.metrics.LayerR\x05layer\x12H\n" +
	"\x0eevidence_class\x18\x05 \x01(\x0e2!.routeiq.v1.metrics.EvidenceClassR\revidenceClass\x127\n" +
	"\x06inputs\x18\x06 \x03(\v2\x1f.routeiq.v1.metrics.MetricInputR\x06inputs\x125\n" +
	"\aformula\x18\a \x01(\v2\x1b.routeiq.v1.metrics.FormulaR\aformula\x12\x12\n" +
	"\x04unit\x18\b \x01(\tR\x04unit\x12P\n" +
	"\x13default_aggregation\x18\t \x01(\x0e2\x1f.routeiq.v1.metrics.AggregationR\x12defaultAggregation\x12D\n" +
	"\rslo_templates\x18\n" +
	" \x03(\v2\x1f.routeiq.v1.metrics.SloTemplateR\fsloTemplates\"\x88\x01\n" +
	"\vMetricInput\x12@\n" +
	"\vevent_types\x18\x01 \x03(\x0e2\x1f.routeiq.v1.telemetry.EventTypeR\n" +
	"eventTypes\x12\x1f\n" +
	"\vfield_paths\x18\x02 \x03(\tR\n" +
	"fieldPaths\x12\x16\n" +
	"\x06filter\x18\x03 \x01(\tR\x06filter\"9\n" +
	"\vSloTemplate\x12\x12\n" +
	"\x04tier\x18\x01 \x01(\tR\x04tier\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\"\xaf\x02\n" +
	"\aFormula\x12P\n" +
	"\rdeterministic\x18\x01 \x01(\v2(.routeiq.v1.metrics.DeterministicFormulaH\x00R\rdeterministic\x12D\n" +
	"\theuristic\x18\x02 \x01(\v2$.routeiq.v1.metrics.HeuristicFormulaH\x00R\theuristic\x12A\n" +
	"\bsemantic\x18\x03 \x01(\v2#.routeiq.v1.metrics.SemanticFormulaH\x00R\bsemantic\x12A\n" +
	"\bfrontier\x18\x04 \x01(\v2#.routeiq.v1.metrics.FrontierFormulaH\x00R\bfrontierB\x06\n" +
	"\x04kind\"6\n" +
	"\x14DeterministicFormula\x12\x1e\n" +
	"\n" +
	"expression\x18\x01 \x01(\tR\n" +
	"expression\"\xc8\x01\n" +
	"\x10HeuristicFormula\x12\x1f\n" +
	"\vdetector_id\x18\x01 \x01(\tR\n" +
	"detectorId\x12T\n" +
	"\n" +
	"parameters\x18\x02 \x03(\v24.routeiq.v1.metrics.HeuristicFormula.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"T\n" +
	"\x0fSemanticFormula\x12#\n" +
	"\rclassifier_id\x18\x01 \x01(\tR\fclassifierId\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\"O\n" +
	"\x0fFrontierFormula\x12\x1f\n" +
	"\vjudge_model\x18\x01 \x01(\tR\n" +
	"judgeModel\x12\x1b\n" +
	"\trubric_id\x18\x02 \x01(\tR\brubricId*\x92\x01\n" +
	"\x05Layer\x12\x15\n" +
	"\x11LAYER_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fLAYER_0_RUNTIME\x10\x01\x12\x1a\n" +
	"\x16LAYER_1_AGENT_BEHAVIOR\x10\x02\x12\x13\n" +
	"\x0fLAYER_2_QUALITY\x10\x03\x12\x14\n" +
	"\x10LAYER_3_BUSINESS\x10\x04\x12\x16\n" +
	"\x12LAYER_4_GOVERNANCE\x10\x05*e\n" +
	"\rEvidenceClass\x12\x18\n" +
	"\x14EVIDENCE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vOTEL_DIRECT\x10\x01\x12\r\n" +
	"\tHEURISTIC\x10\x02\x12\f\n" +
	"\bSEMANTIC\x10\x03\x12\f\n" +
	"\bFRONTIER\x10\x04*\x91\x01\n" +
	"\vAggregation\x12\x1b\n" +
	"\x17AGGREGATION_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03AVG\x10\x01\x12\a\n" +
	"\x03SUM\x10\x02\x12\t\n" +
	"\x05COUNT\x10\x03\x12\b\n" +
	"\x04RATE\x10\x04\x12\a\n" +
	"\x03P50\x10\x05\x12\a\n" +
	"\x03P90\x10\x06\x12\a\n" +
	"\x03P95\x10\a\x12\a\n" +
	"\x03P99\x10\b\x12\a\n" +
	"\x03MAX\x10\t\x12\a\n" +
	"\x03MIN\x10\n" +
	"\x12\b\n" +
	"\x04LAST\x10\vB\x96\x01\n" +
	"0build.buf.gen.ssforge.routeiq.routeiq.v1.metricsB\x10DefinitionsProtoZPbuf.build/gen/go/ssforge/routeiq/protocolbuffers/go/routeiq/v1/metrics;metricsv1b\x06proto3"

var (
	file_routeiq_v1_metrics_definitions_proto_rawDescOnce sync.Once
	file_routeiq_v1_metrics_definitions_proto_rawDescData []byte
)

func file_routeiq_v1_metrics_definitions_proto_rawDescGZIP() []byte {
	file_routeiq_v1_metrics_definitions_proto_rawDescOnce.Do(func() {
		file_routeiq_v1_metrics_definitions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_routeiq_v1_metrics_definitions_proto_rawDesc), len(file_routeiq_v1_metrics_definitions_proto_rawDesc)))
	})
	return file_routeiq_v1_metrics_definitions_proto_rawDescData
}

var file_routeiq_v1_metrics_definitions_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_routeiq_v1_metrics_definitions_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_routeiq_v1_metrics_definitions_proto_goTypes = []any{
	(Layer)(0),                   // 0: routeiq.v1.metrics.Layer
	(EvidenceClass)(0),           // 1: routeiq.v1.metrics.EvidenceClass
	(Aggregation)(0),             // 2: routeiq.v1.metrics.Aggregation
	(*MetricDefinition)(nil),     // 3: routeiq.v1.metrics.MetricDefinition
	(*MetricInput)(nil),          // 4: routeiq.v1.metrics.MetricInput
	(*SloTemplate)(nil),          // 5: routeiq.v1.metrics.SloTemplate
	(*Formula)(nil),              // 6: routeiq.v1.metrics.Formula
	(*DeterministicFormula)(nil), // 7: routeiq.v1.metrics.DeterministicFormula
	(*HeuristicFormula)(nil),     // 8: routeiq.v1.metrics.HeuristicFormula
	(*SemanticFormula)(nil),      // 9: routeiq.v1.metrics.SemanticFormula
	(*FrontierFormula)(nil),      // 10: routeiq.v1.metrics.FrontierFormula
	nil,                          // 11: routeiq.v1.metrics.HeuristicFormula.ParametersEntry
	(telemetry.EventType)(0),     // 12: routeiq.v1.telemetry.EventType
}
var file_routeiq_v1_metrics_definitions_proto_depIdxs = []int32{
	0,  // 0: routeiq.v1.metrics.MetricDefinition.layer:type_name -> routeiq.v1.metrics.Layer
	1,  // 1: routeiq.v1.metrics.MetricDefinition.evidence_class:type_name -> routeiq.v1.metrics.EvidenceClass
	4,  // 2: routeiq.v1.metrics.MetricDefinition.inputs:type_name -> routeiq.v1.metrics.MetricInput
	6,  // 3: routeiq.v1.metrics.MetricDefinition.formula:type_name -> routeiq.v1.metrics.Formula
	2,  // 4: routeiq.v1.metrics.MetricDefinition.default_aggregation:type_name -> routeiq.v1.metrics.Aggregation
	5,  // 5: routeiq.v1.metrics.MetricDefinition.slo_templates:type_name -> routeiq.v1.metrics.SloTemplate
	12, // 6: routeiq.v1.metrics.MetricInput.event_types:type_name -> routeiq.v1.telemetry.EventType
	7,  // 7: routeiq.v1.metrics.Formula.deterministic:type_name -> routeiq.v1.metrics.DeterministicFormula
	8,  // 8: routeiq.v1.metrics.Formula.heuristic:type_name -> routeiq.v1.metrics.HeuristicFormula
	9,  // 9: routeiq.v1.metrics.Formula.semantic:type_name -> routeiq.v1.metrics.SemanticFormula
	10, // 10: routeiq.v1.metrics.Formula.frontier:type_name -> routeiq.v1.metrics.FrontierFormula
	11, // 11: routeiq.v1.metrics.HeuristicFormula.parameters:type_name -> routeiq.v1.metrics.HeuristicFormula.ParametersEntry
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_routeiq_v1_metrics_definitions_proto_init() }
func file_routeiq_v1_metrics_definitions_proto_init() {
	if File_routeiq_v1_metrics_definitions_proto != nil {
		return
	}
	file_routeiq_v1_metrics_definitions_proto_msgTypes[3].OneofWrappers = []any{
		(*Formula_Deterministic)(nil),
		(*Formula_Heuristic)(nil),
		(*Formula_Semantic)(nil),
		(*Formula_Frontier)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_routeiq_v1_metrics_definitions_proto_rawDesc), len(file_routeiq_v1_metrics_definitions_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_routeiq_v1_metrics_definitions_proto_goTypes,
		DependencyIndexes: file_routeiq_v1_metrics_definitions_proto_depIdxs,
		EnumInfos:         file_routeiq_v1_metrics_definitions_proto_enumTypes,
		MessageInfos:      file_routeiq_v1_metrics_definitions_proto_msgTypes,
	}.Build()
	File_routeiq_v1_metrics_definitions_proto = out.File
	file_routeiq_v1_metrics_definitions_proto_goTypes = nil
	file_routeiq_v1_metrics_definitions_proto_depIdxs = nil
}
