// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: routeiq/v1/insights/alerts.proto

package insightsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Operator int32

const (
	Operator_OPERATOR_UNSPECIFIED Operator = 0
	Operator_GT                   Operator = 1
	Operator_LT                   Operator = 2
	Operator_GTE                  Operator = 3
	Operator_LTE                  Operator = 4
	Operator_EQ                   Operator = 5
	Operator_TREND_UP             Operator = 6
	Operator_TREND_DOWN           Operator = 7
)

// Enum value maps for Operator.
var (
	Operator_name = map[int32]string{
		0: "OPERATOR_UNSPECIFIED",
		1: "GT",
		2: "LT",
		3: "GTE",
		4: "LTE",
		5: "EQ",
		6: "TREND_UP",
		7: "TREND_DOWN",
	}
	Operator_value = map[string]int32{
		"OPERATOR_UNSPECIFIED": 0,
		"GT":                   1,
		"LT":                   2,
		"GTE":                  3,
		"LTE":                  4,
		"EQ":                   5,
		"TREND_UP":             6,
		"TREND_DOWN":           7,
	}
)

func (x Operator) Enum() *Operator {
	p := new(Operator)
	*p = x
	return p
}

func (x Operator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Operator) Descriptor() protoreflect.EnumDescriptor {
	return file_routeiq_v1_insights_alerts_proto_enumTypes[0].Descriptor()
}

func (Operator) Type() protoreflect.EnumType {
	return &file_routeiq_v1_insights_alerts_proto_enumTypes[0]
}

func (x Operator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Operator.Descriptor instead.
func (Operator) EnumDescriptor() ([]byte, []int) {
	return file_routeiq_v1_insights_alerts_proto_rawDescGZIP(), []int{0}
}

type Severity int32

const (
	Severity_SEVERITY_UNSPECIFIED Severity = 0
	Severity_INFO                 Severity = 1
	Severity_WARNING              Severity = 2
	Severity_CRITICAL             Severity = 3
	Severity_PAGE                 Severity = 4
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "SEVERITY_UNSPECIFIED",
		1: "INFO",
		2: "WARNING",
		3: "CRITICAL",
		4: "PAGE",
	}
	Severity_value = map[string]int32{
		"SEVERITY_UNSPECIFIED": 0,
		"INFO":                 1,
		"WARNING":              2,
		"CRITICAL":             3,
		"PAGE":                 4,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_routeiq_v1_insights_alerts_proto_enumTypes[1].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_routeiq_v1_insights_alerts_proto_enumTypes[1]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_routeiq_v1_insights_alerts_proto_rawDescGZIP(), []int{1}
}

type RecommendedAction int32

const (
	RecommendedAction_ACTION_UNSPECIFIED RecommendedAction = 0
	RecommendedAction_REDUCE_AUTONOMY    RecommendedAction = 1
	RecommendedAction_CIRCUIT_BREAK      RecommendedAction = 2
	RecommendedAction_ESCALATE_HUMAN     RecommendedAction = 3
	RecommendedAction_ROLLBACK_VERSION   RecommendedAction = 4
	RecommendedAction_SWITCH_MODEL       RecommendedAction = 5
	RecommendedAction_REQUIRE_APPROVAL   RecommendedAction = 6
)

// Enum value maps for RecommendedAction.
var (
	RecommendedAction_name = map[int32]string{
		0: "ACTION_UNSPECIFIED",
		1: "REDUCE_AUTONOMY",
		2: "CIRCUIT_BREAK",
		3: "ESCALATE_HUMAN",
		4: "ROLLBACK_VERSION",
		5: "SWITCH_MODEL",
		6: "REQUIRE_APPROVAL",
	}
	RecommendedAction_value = map[string]int32{
		"ACTION_UNSPECIFIED": 0,
		"REDUCE_AUTONOMY":    1,
		"CIRCUIT_BREAK":      2,
		"ESCALATE_HUMAN":     3,
		"ROLLBACK_VERSION":   4,
		"SWITCH_MODEL":       5,
		"REQUIRE_APPROVAL":   6,
	}
)

func (x RecommendedAction) Enum() *RecommendedAction {
	p := new(RecommendedAction)
	*p = x
	return p
}

func (x RecommendedAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RecommendedAction) Descriptor() protoreflect.EnumDescriptor {
	return file_routeiq_v1_insights_alerts_proto_enumTypes[2].Descriptor()
}

func (RecommendedAction) Type() protoreflect.EnumType {
	return &file_routeiq_v1_insights_alerts_proto_enumTypes[2]
}

func (x RecommendedAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RecommendedAction.Descriptor instead.
func (RecommendedAction) EnumDescriptor() ([]byte, []int) {
	return file_routeiq_v1_insights_alerts_proto_rawDescGZIP(), []int{2}
}

type AlertRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MetricId      string                 `protobuf:"bytes,2,opt,name=metric_id,json=metricId,proto3" json:"metric_id,omitempty"`
	Condition     *Condition             `protobuf:"bytes,3,opt,name=condition,proto3" json:"condition,omitempty"`
	Severity      Severity               `protobuf:"varint,4,opt,name=severity,proto3,enum=routeiq.v1.insights.Severity" json:"severity,omitempty"`
	Actions       []RecommendedAction    `protobuf:"varint,5,rep,packed,name=actions,proto3,enum=routeiq.v1.insights.RecommendedAction" json:"actions,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Enabled       bool                   `protobuf:"varint,7,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertRule) Reset() {
	*x = AlertRule{}
	mi := &file_routeiq_v1_insights_alerts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertRule) ProtoMessage() {}

func (x *AlertRule) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_insights_alerts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertRule.ProtoReflect.Descriptor instead.
func (*AlertRule) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_insights_alerts_proto_rawDescGZIP(), []int{0}
}

func (x *AlertRule) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AlertRule) GetMetricId() string {
	if x != nil {
		return x.MetricId
	}
	return ""
}

func (x *AlertRule) GetCondition() *Condition {
	if x != nil {
		return x.Condition
	}
	return nil
}

func (x *AlertRule) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_UNSPECIFIED
}

func (x *AlertRule) GetActions() []RecommendedAction {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *AlertRule) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AlertRule) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type Condition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            Operator               `protobuf:"varint,1,opt,name=op,proto3,enum=routeiq.v1.insights.Operator" json:"op,omitempty"`
	Threshold     float64                `protobuf:"fixed64,2,opt,name=threshold,proto3" json:"threshold,omitempty"`
	Window        string                 `protobuf:"bytes,3,opt,name=window,proto3" json:"window,omitempty"`
	MinSamples    int32                  `protobuf:"varint,4,opt,name=min_samples,json=minSamples,proto3" json:"min_samples,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Condition) Reset() {
	*x = Condition{}
	mi := &file_routeiq_v1_insights_alerts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Condition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Condition) ProtoMessage() {}

func (x *Condition) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_insights_alerts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Condition.ProtoReflect.Descriptor instead.
func (*Condition) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_insights_alerts_proto_rawDescGZIP(), []int{1}
}

func (x *Condition) GetOp() Operator {
	if x != nil {
		return x.Op
	}
	return Operator_OPERATOR_UNSPECIFIED
}

func (x *Condition) GetThreshold() float64 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *Condition) GetWindow() string {
	if x != nil {
		return x.Window
	}
	return ""
}

func (x *Condition) GetMinSamples() int32 {
	if x != nil {
		return x.MinSamples
	}
	return 0
}

var File_routeiq_v1_insights_alerts_proto protoreflect.FileDescriptor

const file_routeiq_v1_insights_alerts_proto_rawDesc = "" +
	"\n" +
	" routeiq/v1/insights/alerts.proto\x12\x13routeiq.v1.insights\"\xaf\x02\n" +
	"\tAlertRule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tmetric_id\x18\x02 \x01(\tR\bmetricId\x12<\n" +
	"\tcondition\x18\x03 \x01(\v2\x1e.routeiq.v1.insights.ConditionR\tcondition\x129\n" +
	"\bseverity\x18\x04 \x01(\x0e2\x1d.routeiq.v1.insights.SeverityR\bseverity\x12@\n" +
	"\aactions\x18\x05 \x03(\x0e2&.routeiq.v1.insights.RecommendedActionR\aactions\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x18\n" +
	"\aenabled\x18\a \x01(\bR\aenabled\"\x91\x01\n" +
	"\tCondition\x12-\n" +
	"\x02op\x18\x01 \x01(\x0e2\x1d.routeiq.v1.insights.OperatorR\x02op\x12\x1c\n" +
	"\tthreshold\x18\x02 \x01(\x01R\tthreshold\x12\x16\n" +
	"\x06window\x18\x03 \x01(\tR\x06window\x12\x1f\n" +
	"\vmin_samples\x18\x04 \x01(\x05R\n" +
	"minSamples*l\n" +
	"\bOperator\x12\x18\n" +
	"\x14OPERATOR_UNSPECIFIED\x10\x00\x12\x06\n" +
	"\x02GT\x10\x01\x12\x06\n" +
	"\x02LT\x10\x02\x12\a\n" +
	"\x03GTE\x10\x03\x12\a\n" +
	"\x03LTE\x10\x04\x12\x06\n" +
	"\x02EQ\x10\x05\x12\f\n" +
	"\bTREND_UP\x10\x06\x12\x0e\n" +
	"\n" +
	"TREND_DOWN\x10\a*S\n" +
	"\bSeverity\x12\x18\n" +
	"\x14SEVERITY_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04INFO\x10\x01\x12\v\n" +
	"\aWARNING\x10\x02\x12\f\n" +
	"\bCRITICAL\x10\x03\x12\b\n" +
	"\x04PAGE\x10\x04*\xa5\x01\n" +
	"\x11RecommendedAction\x12\x16\n" +
	"\x12ACTION_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fREDUCE_AUTONOMY\x10\x01\x12\x11\n" +
	"\rCIRCUIT_BREAK\x10\x02\x12\x12\n" +
	"\x0eESCALATE_HUMAN\x10\x03\x12\x14\n" +
	"\x10ROLLBACK_VERSION\x10\x04\x12\x10\n" +
	"\fSWITCH_MODEL\x10\x05\x12\x14\n" +
	"\x10REQUIRE_APPROVAL\x10\x06B\x94\x01\n" +
	"1build.buf.gen.ssforge.routeiq.routeiq.v1.insightsB\vAlertsProtoZRbuf.build/gen/go/ssforge/routeiq/protocolbuffers/go/routeiq/v1/insights;insightsv1b\x06proto3"

var (
	file_routeiq_v1_insights_alerts_proto_rawDescOnce sync.Once
	file_routeiq_v1_insights_alerts_proto_rawDescData []byte
)

func file_routeiq_v1_insights_alerts_proto_rawDescGZIP() []byte {
	file_routeiq_v1_insights_alerts_proto_rawDescOnce.Do(func() {
		file_routeiq_v1_insights_alerts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_routeiq_v1_insights_alerts_proto_rawDesc), len(file_routeiq_v1_insights_alerts_proto_rawDesc)))
	})
	return file_routeiq_v1_insights_alerts_proto_rawDescData
}

var file_routeiq_v1_insights_alerts_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_routeiq_v1_insights_alerts_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_routeiq_v1_insights_alerts_proto_goTypes = []any{
	(Operator)(0),          // 0: routeiq.v1.insights.Operator
	(Severity)(0),          // 1: routeiq.v1.insights.Severity
	(RecommendedAction)(0), // 2: routeiq.v1.insights.RecommendedAction
	(*AlertRule)(nil),      // 3: routeiq.v1.insights.AlertRule
	(*Condition)(nil),      // 4: routeiq.v1.insights.Condition
}
var file_routeiq_v1_insights_alerts_proto_depIdxs = []int32{
	4, // 0: routeiq.v1.insights.AlertRule.condition:type_name -> routeiq.v1.insights.Condition
	1, // 1: routeiq.v1.insights.AlertRule.severity:type_name -> routeiq.v1.insights.Severity
	2, // 2: routeiq.v1.insights.AlertRule.actions:type_name -> routeiq.v1.insights.RecommendedAction
	0, // 3: routeiq.v1.insights.Condition.op:type_name -> routeiq.v1.insights.Operator
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_routeiq_v1_insights_alerts_proto_init() }
func file_routeiq_v1_insights_alerts_proto_init() {
	if File_routeiq_v1_insights_alerts_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_routeiq_v1_insights_alerts_proto_rawDesc), len(file_routeiq_v1_insights_alerts_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_routeiq_v1_insights_alerts_proto_goTypes,
		DependencyIndexes: file_routeiq_v1_insights_alerts_proto_depIdxs,
		EnumInfos:         file_routeiq_v1_insights_alerts_proto_enumTypes,
		MessageInfos:      file_routeiq_v1_insights_alerts_proto_msgTypes,
	}.Build()
	File_routeiq_v1_insights_alerts_proto = out.File
	file_routeiq_v1_insights_alerts_proto_goTypes = nil
	file_routeiq_v1_insights_alerts_proto_depIdxs = nil
}
