// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: routeiq/v1/insights/dashboards.proto

package insightsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WidgetType int32

const (
	WidgetType_WIDGET_TYPE_UNSPECIFIED WidgetType = 0
	WidgetType_GAUGE                   WidgetType = 1
	WidgetType_TIMESERIES              WidgetType = 2
	WidgetType_TABLE                   WidgetType = 3
	WidgetType_HEATMAP                 WidgetType = 4
	WidgetType_SPARKLINE               WidgetType = 5
)

// Enum value maps for WidgetType.
var (
	WidgetType_name = map[int32]string{
		0: "WIDGET_TYPE_UNSPECIFIED",
		1: "GAUGE",
		2: "TIMESERIES",
		3: "TABLE",
		4: "HEATMAP",
		5: "SPARKLINE",
	}
	WidgetType_value = map[string]int32{
		"WIDGET_TYPE_UNSPECIFIED": 0,
		"GAUGE":                   1,
		"TIMESERIES":              2,
		"TABLE":                   3,
		"HEATMAP":                 4,
		"SPARKLINE":               5,
	}
)

func (x WidgetType) Enum() *WidgetType {
	p := new(WidgetType)
	*p = x
	return p
}

func (x WidgetType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WidgetType) Descriptor() protoreflect.EnumDescriptor {
	return file_routeiq_v1_insights_dashboards_proto_enumTypes[0].Descriptor()
}

func (WidgetType) Type() protoreflect.EnumType {
	return &file_routeiq_v1_insights_dashboards_proto_enumTypes[0]
}

func (x WidgetType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WidgetType.Descriptor instead.
func (WidgetType) EnumDescriptor() ([]byte, []int) {
	return file_routeiq_v1_insights_dashboards_proto_rawDescGZIP(), []int{0}
}

type DashboardWidget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	MetricIds     []string               `protobuf:"bytes,3,rep,name=metric_ids,json=metricIds,proto3" json:"metric_ids,omitempty"`
	Type          WidgetType             `protobuf:"varint,4,opt,name=type,proto3,enum=routeiq.v1.insights.WidgetType" json:"type,omitempty"`
	DefaultRange  string                 `protobuf:"bytes,5,opt,name=default_range,json=defaultRange,proto3" json:"default_range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DashboardWidget) Reset() {
	*x = DashboardWidget{}
	mi := &file_routeiq_v1_insights_dashboards_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardWidget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardWidget) ProtoMessage() {}

func (x *DashboardWidget) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_insights_dashboards_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardWidget.ProtoReflect.Descriptor instead.
func (*DashboardWidget) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_insights_dashboards_proto_rawDescGZIP(), []int{0}
}

func (x *DashboardWidget) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DashboardWidget) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DashboardWidget) GetMetricIds() []string {
	if x != nil {
		return x.MetricIds
	}
	return nil
}

func (x *DashboardWidget) GetType() WidgetType {
	if x != nil {
		return x.Type
	}
	return WidgetType_WIDGET_TYPE_UNSPECIFIED
}

func (x *DashboardWidget) GetDefaultRange() string {
	if x != nil {
		return x.DefaultRange
	}
	return ""
}

type Dashboard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Widgets       []*DashboardWidget     `protobuf:"bytes,3,rep,name=widgets,proto3" json:"widgets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dashboard) Reset() {
	*x = Dashboard{}
	mi := &file_routeiq_v1_insights_dashboards_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dashboard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dashboard) ProtoMessage() {}

func (x *Dashboard) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_insights_dashboards_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dashboard.ProtoReflect.Descriptor instead.
func (*Dashboard) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_insights_dashboards_proto_rawDescGZIP(), []int{1}
}

func (x *Dashboard) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Dashboard) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Dashboard) GetWidgets() []*DashboardWidget {
	if x != nil {
		return x.Widgets
	}
	return nil
}

var File_routeiq_v1_insights_dashboards_proto protoreflect.FileDescriptor

const file_routeiq_v1_insights_dashboards_proto_rawDesc = "" +
	"\n" +
	"$routeiq/v1/insights/dashboards.proto\x12\x13routeiq.v1.insights\"\xb0\x01\n" +
	"\x0fDashboardWidget\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1d\n" +
	"\n" +
	"metric_ids\x18\x03 \x03(\tR\tmetricIds\x123\n" +
	"\x04type\x18\x04 \x01(\x0e2\x1f.routeiq.v1.insights.WidgetTypeR\x04type\x12#\n" +
	"\rdefault_range\x18\x05 \x01(\tR\fdefaultRange\"q\n" +
	"\tDashboard\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12>\n" +
	"\awidgets\x18\x03 \x03(\v2$.routeiq.v1.insights.DashboardWidgetR\awidgets*k\n" +
	"\n" +
	"WidgetType\x12\x1b\n" +
	"\x17WIDGET_TYPE_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05GAUGE\x10\x01\x12\x0e\n" +
	"\n" +
	"TIMESERIES\x10\x02\x12\t\n" +
	"\x05TABLE\x10\x03\x12\v\n" +
	"\aHEATMAP\x10\x04\x12\r\n" +
	"\tSPARKLINE\x10\x05B\x98\x01\n" +
	"1build.buf.gen.ssforge.routeiq.routeiq.v1.insightsB\x0fDashboardsProtoZRbuf.build/gen/go/ssforge/routeiq/protocolbuffers/go/routeiq/v1/insights;insightsv1b\x06proto3"

var (
	file_routeiq_v1_insights_dashboards_proto_rawDescOnce sync.Once
	file_routeiq_v1_insights_dashboards_proto_rawDescData []byte
)

func file_routeiq_v1_insights_dashboards_proto_rawDescGZIP() []byte {
	file_routeiq_v1_insights_dashboards_proto_rawDescOnce.Do(func() {
		file_routeiq_v1_insights_dashboards_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_routeiq_v1_insights_dashboards_proto_rawDesc), len(file_routeiq_v1_insights_dashboards_proto_rawDesc)))
	})
	return file_routeiq_v1_insights_dashboards_proto_rawDescData
}

var file_routeiq_v1_insights_dashboards_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_routeiq_v1_insights_dashboards_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_routeiq_v1_insights_dashboards_proto_goTypes = []any{
	(WidgetType)(0),         // 0: routeiq.v1.insights.WidgetType
	(*DashboardWidget)(nil), // 1: routeiq.v1.insights.DashboardWidget
	(*Dashboard)(nil),       // 2: routeiq.v1.insights.Dashboard
}
var file_routeiq_v1_insights_dashboards_proto_depIdxs = []int32{
	0, // 0: routeiq.v1.insights.DashboardWidget.type:type_name -> routeiq.v1.insights.WidgetType
	1, // 1: routeiq.v1.insights.Dashboard.widgets:type_name -> routeiq.v1.insights.DashboardWidget
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_routeiq_v1_insights_dashboards_proto_init() }
func file_routeiq_v1_insights_dashboards_proto_init() {
	if File_routeiq_v1_insights_dashboards_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_routeiq_v1_insights_dashboards_proto_rawDesc), len(file_routeiq_v1_insights_dashboards_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_routeiq_v1_insights_dashboards_proto_goTypes,
		DependencyIndexes: file_routeiq_v1_insights_dashboards_proto_depIdxs,
		EnumInfos:         file_routeiq_v1_insights_dashboards_proto_enumTypes,
		MessageInfos:      file_routeiq_v1_insights_dashboards_proto_msgTypes,
	}.Build()
	File_routeiq_v1_insights_dashboards_proto = out.File
	file_routeiq_v1_insights_dashboards_proto_goTypes = nil
	file_routeiq_v1_insights_dashboards_proto_depIdxs = nil
}
