// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: routeiq/v1/insights/interventions.proto

package insightsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InterventionStatus int32

const (
	InterventionStatus_INTERVENTION_STATUS_UNSPECIFIED InterventionStatus = 0
	InterventionStatus_PENDING                         InterventionStatus = 1
	InterventionStatus_APPLIED                         InterventionStatus = 2
	InterventionStatus_DISMISSED                       InterventionStatus = 3
	InterventionStatus_EXPIRED                         InterventionStatus = 4
)

// Enum value maps for InterventionStatus.
var (
	InterventionStatus_name = map[int32]string{
		0: "INTERVENTION_STATUS_UNSPECIFIED",
		1: "PENDING",
		2: "APPLIED",
		3: "DISMISSED",
		4: "EXPIRED",
	}
	InterventionStatus_value = map[string]int32{
		"INTERVENTION_STATUS_UNSPECIFIED": 0,
		"PENDING":                         1,
		"APPLIED":                         2,
		"DISMISSED":                       3,
		"EXPIRED":                         4,
	}
)

func (x InterventionStatus) Enum() *InterventionStatus {
	p := new(InterventionStatus)
	*p = x
	return p
}

func (x InterventionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InterventionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_routeiq_v1_insights_interventions_proto_enumTypes[0].Descriptor()
}

func (InterventionStatus) Type() protoreflect.EnumType {
	return &file_routeiq_v1_insights_interventions_proto_enumTypes[0]
}

func (x InterventionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InterventionStatus.Descriptor instead.
func (InterventionStatus) EnumDescriptor() ([]byte, []int) {
	return file_routeiq_v1_insights_interventions_proto_rawDescGZIP(), []int{0}
}

type InterventionRecommendation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AlertRuleId   string                 `protobuf:"bytes,2,opt,name=alert_rule_id,json=alertRuleId,proto3" json:"alert_rule_id,omitempty"`
	MetricId      string                 `protobuf:"bytes,3,opt,name=metric_id,json=metricId,proto3" json:"metric_id,omitempty"`
	Action        RecommendedAction      `protobuf:"varint,4,opt,name=action,proto3,enum=routeiq.v1.insights.RecommendedAction" json:"action,omitempty"`
	Rationale     string                 `protobuf:"bytes,5,opt,name=rationale,proto3" json:"rationale,omitempty"`
	Confidence    float64                `protobuf:"fixed64,6,opt,name=confidence,proto3" json:"confidence,omitempty"`
	GeneratedAt   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	Status        InterventionStatus     `protobuf:"varint,8,opt,name=status,proto3,enum=routeiq.v1.insights.InterventionStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterventionRecommendation) Reset() {
	*x = InterventionRecommendation{}
	mi := &file_routeiq_v1_insights_interventions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterventionRecommendation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterventionRecommendation) ProtoMessage() {}

func (x *InterventionRecommendation) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_insights_interventions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterventionRecommendation.ProtoReflect.Descriptor instead.
func (*InterventionRecommendation) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_insights_interventions_proto_rawDescGZIP(), []int{0}
}

func (x *InterventionRecommendation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InterventionRecommendation) GetAlertRuleId() string {
	if x != nil {
		return x.AlertRuleId
	}
	return ""
}

func (x *InterventionRecommendation) GetMetricId() string {
	if x != nil {
		return x.MetricId
	}
	return ""
}

func (x *InterventionRecommendation) GetAction() RecommendedAction {
	if x != nil {
		return x.Action
	}
	return RecommendedAction_ACTION_UNSPECIFIED
}

func (x *InterventionRecommendation) GetRationale() string {
	if x != nil {
		return x.Rationale
	}
	return ""
}

func (x *InterventionRecommendation) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *InterventionRecommendation) GetGeneratedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GeneratedAt
	}
	return nil
}

func (x *InterventionRecommendation) GetStatus() InterventionStatus {
	if x != nil {
		return x.Status
	}
	return InterventionStatus_INTERVENTION_STATUS_UNSPECIFIED
}

var File_routeiq_v1_insights_interventions_proto protoreflect.FileDescriptor

const file_routeiq_v1_insights_interventions_proto_rawDesc = "" +
	"\n" +
	"'routeiq/v1/insights/interventions.proto\x12\x13routeiq.v1.insights\x1a\x1fgoogle/protobuf/timestamp.proto\x1a routeiq/v1/insights/alerts.proto\"\xeb\x02\n" +
	"\x1aInterventionRecommendation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\"\n" +
	"\ralert_rule_id\x18\x02 \x01(\tR\valertRuleId\x12\x1b\n" +
	"\tmetric_id\x18\x03 \x01(\tR\bmetricId\x12>\n" +
	"\x06action\x18\x04 \x01(\x0e2&.routeiq.v1.insights.RecommendedActionR\x06action\x12\x1c\n" +
	"\trationale\x18\x05 \x01(\tR\trationale\x12\x1e\n" +
	"\n" +
	"confidence\x18\x06 \x01(\x01R\n" +
	"confidence\x12=\n" +
	"\fgenerated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vgeneratedAt\x12?\n" +
	"\x06status\x18\b \x01(\x0e2'.routeiq.v1.insights.InterventionStatusR\x06status*o\n" +
	"\x12InterventionStatus\x12#\n" +
	"\x1fINTERVENTION_STATUS_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\v\n" +
	"\aAPPLIED\x10\x02\x12\r\n" +
	"\tDISMISSED\x10\x03\x12\v\n" +
	"\aEXPIRED\x10\x04B\x9b\x01\n" +
	"1build.buf.gen.ssforge.routeiq.routeiq.v1.insightsB\x12InterventionsProtoZRbuf.build/gen/go/ssforge/routeiq/protocolbuffers/go/routeiq/v1/insights;insightsv1b\x06proto3"

var (
	file_routeiq_v1_insights_interventions_proto_rawDescOnce sync.Once
	file_routeiq_v1_insights_interventions_proto_rawDescData []byte
)

func file_routeiq_v1_insights_interventions_proto_rawDescGZIP() []byte {
	file_routeiq_v1_insights_interventions_proto_rawDescOnce.Do(func() {
		file_routeiq_v1_insights_interventions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_routeiq_v1_insights_interventions_proto_rawDesc), len(file_routeiq_v1_insights_interventions_proto_rawDesc)))
	})
	return file_routeiq_v1_insights_interventions_proto_rawDescData
}

var file_routeiq_v1_insights_interventions_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_routeiq_v1_insights_interventions_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_routeiq_v1_insights_interventions_proto_goTypes = []any{
	(InterventionStatus)(0),            // 0: routeiq.v1.insights.InterventionStatus
	(*InterventionRecommendation)(nil), // 1: routeiq.v1.insights.InterventionRecommendation
	(RecommendedAction)(0),             // 2: routeiq.v1.insights.RecommendedAction
	(*timestamppb.Timestamp)(nil),      // 3: google.protobuf.Timestamp
}
var file_routeiq_v1_insights_interventions_proto_depIdxs = []int32{
	2, // 0: routeiq.v1.insights.InterventionRecommendation.action:type_name -> routeiq.v1.insights.RecommendedAction
	3, // 1: routeiq.v1.insights.InterventionRecommendation.generated_at:type_name -> google.protobuf.Timestamp
	0, // 2: routeiq.v1.insights.InterventionRecommendation.status:type_name -> routeiq.v1.insights.InterventionStatus
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_routeiq_v1_insights_interventions_proto_init() }
func file_routeiq_v1_insights_interventions_proto_init() {
	if File_routeiq_v1_insights_interventions_proto != nil {
		return
	}
	file_routeiq_v1_insights_alerts_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_routeiq_v1_insights_interventions_proto_rawDesc), len(file_routeiq_v1_insights_interventions_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_routeiq_v1_insights_interventions_proto_goTypes,
		DependencyIndexes: file_routeiq_v1_insights_interventions_proto_depIdxs,
		EnumInfos:         file_routeiq_v1_insights_interventions_proto_enumTypes,
		MessageInfos:      file_routeiq_v1_insights_interventions_proto_msgTypes,
	}.Build()
	File_routeiq_v1_insights_interventions_proto = out.File
	file_routeiq_v1_insights_interventions_proto_goTypes = nil
	file_routeiq_v1_insights_interventions_proto_depIdxs = nil
}
