// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: routeiq/v1/insights/slo.proto

package insightsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SloState int32

const (
	SloState_SLO_STATE_UNSPECIFIED SloState = 0
	SloState_MEETING               SloState = 1
	SloState_AT_RISK               SloState = 2
	SloState_BREACHED              SloState = 3
)

// Enum value maps for SloState.
var (
	SloState_name = map[int32]string{
		0: "SLO_STATE_UNSPECIFIED",
		1: "MEETING",
		2: "AT_RISK",
		3: "BREACHED",
	}
	SloState_value = map[string]int32{
		"SLO_STATE_UNSPECIFIED": 0,
		"MEETING":               1,
		"AT_RISK":               2,
		"BREACHED":              3,
	}
)

func (x SloState) Enum() *SloState {
	p := new(SloState)
	*p = x
	return p
}

func (x SloState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SloState) Descriptor() protoreflect.EnumDescriptor {
	return file_routeiq_v1_insights_slo_proto_enumTypes[0].Descriptor()
}

func (SloState) Type() protoreflect.EnumType {
	return &file_routeiq_v1_insights_slo_proto_enumTypes[0]
}

func (x SloState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SloState.Descriptor instead.
func (SloState) EnumDescriptor() ([]byte, []int) {
	return file_routeiq_v1_insights_slo_proto_rawDescGZIP(), []int{0}
}

type SloTarget struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MetricId         string                 `protobuf:"bytes,2,opt,name=metric_id,json=metricId,proto3" json:"metric_id,omitempty"`
	WorkspaceId      string                 `protobuf:"bytes,3,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Tier             string                 `protobuf:"bytes,4,opt,name=tier,proto3" json:"tier,omitempty"`
	TargetExpression string                 `protobuf:"bytes,5,opt,name=target_expression,json=targetExpression,proto3" json:"target_expression,omitempty"`
	Window           string                 `protobuf:"bytes,6,opt,name=window,proto3" json:"window,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SloTarget) Reset() {
	*x = SloTarget{}
	mi := &file_routeiq_v1_insights_slo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SloTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SloTarget) ProtoMessage() {}

func (x *SloTarget) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_insights_slo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SloTarget.ProtoReflect.Descriptor instead.
func (*SloTarget) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_insights_slo_proto_rawDescGZIP(), []int{0}
}

func (x *SloTarget) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SloTarget) GetMetricId() string {
	if x != nil {
		return x.MetricId
	}
	return ""
}

func (x *SloTarget) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *SloTarget) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

func (x *SloTarget) GetTargetExpression() string {
	if x != nil {
		return x.TargetExpression
	}
	return ""
}

func (x *SloTarget) GetWindow() string {
	if x != nil {
		return x.Window
	}
	return ""
}

type SloStatus struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SloId                string                 `protobuf:"bytes,1,opt,name=slo_id,json=sloId,proto3" json:"slo_id,omitempty"`
	MetricId             string                 `protobuf:"bytes,2,opt,name=metric_id,json=metricId,proto3" json:"metric_id,omitempty"`
	CurrentValue         float64                `protobuf:"fixed64,3,opt,name=current_value,json=currentValue,proto3" json:"current_value,omitempty"`
	TargetValue          float64                `protobuf:"fixed64,4,opt,name=target_value,json=targetValue,proto3" json:"target_value,omitempty"`
	State                SloState               `protobuf:"varint,5,opt,name=state,proto3,enum=routeiq.v1.insights.SloState" json:"state,omitempty"`
	ErrorBudgetRemaining float64                `protobuf:"fixed64,6,opt,name=error_budget_remaining,json=errorBudgetRemaining,proto3" json:"error_budget_remaining,omitempty"`
	EvaluatedAt          *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=evaluated_at,json=evaluatedAt,proto3" json:"evaluated_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SloStatus) Reset() {
	*x = SloStatus{}
	mi := &file_routeiq_v1_insights_slo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SloStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SloStatus) ProtoMessage() {}

func (x *SloStatus) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_insights_slo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SloStatus.ProtoReflect.Descriptor instead.
func (*SloStatus) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_insights_slo_proto_rawDescGZIP(), []int{1}
}

func (x *SloStatus) GetSloId() string {
	if x != nil {
		return x.SloId
	}
	return ""
}

func (x *SloStatus) GetMetricId() string {
	if x != nil {
		return x.MetricId
	}
	return ""
}

func (x *SloStatus) GetCurrentValue() float64 {
	if x != nil {
		return x.CurrentValue
	}
	return 0
}

func (x *SloStatus) GetTargetValue() float64 {
	if x != nil {
		return x.TargetValue
	}
	return 0
}

func (x *SloStatus) GetState() SloState {
	if x != nil {
		return x.State
	}
	return SloState_SLO_STATE_UNSPECIFIED
}

func (x *SloStatus) GetErrorBudgetRemaining() float64 {
	if x != nil {
		return x.ErrorBudgetRemaining
	}
	return 0
}

func (x *SloStatus) GetEvaluatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EvaluatedAt
	}
	return nil
}

var File_routeiq_v1_insights_slo_proto protoreflect.FileDescriptor

const file_routeiq_v1_insights_slo_proto_rawDesc = "" +
	"\n" +
	"\x1drouteiq/v1/insights/slo.proto\x12\x13routeiq.v1.insights\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb4\x01\n" +
	"\tSloTarget\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tmetric_id\x18\x02 \x01(\tR\bmetricId\x12!\n" +
	"\fworkspace_id\x18\x03 \x01(\tR\vworkspaceId\x12\x12\n" +
	"\x04tier\x18\x04 \x01(\tR\x04tier\x12+\n" +
	"\x11target_expression\x18\x05 \x01(\tR\x10targetExpression\x12\x16\n" +
	"\x06window\x18\x06 \x01(\tR\x06window\"\xb1\x02\n" +
	"\tSloStatus\x12\x15\n" +
	"\x06slo_id\x18\x01 \x01(\tR\x05sloId\x12\x1b\n" +
	"\tmetric_id\x18\x02 \x01(\tR\bmetricId\x12#\n" +
	"\rcurrent_value\x18\x03 \x01(\x01R\fcurrentValue\x12!\n" +
	"\ftarget_value\x18\x04 \x01(\x01R\vtargetValue\x123\n" +
	"\x05state\x18\x05 \x01(\x0e2\x1d.routeiq.v1.insights.SloStateR\x05state\x124\n" +
	"\x16error_budget_remaining\x18\x06 \x01(\x01R\x14errorBudgetRemaining\x12=\n" +
	"\fevaluated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vevaluatedAt*M\n" +
	"\bSloState\x12\x19\n" +
	"\x15SLO_STATE_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aMEETING\x10\x01\x12\v\n" +
	"\aAT_RISK\x10\x02\x12\f\n" +
	"\bBREACHED\x10\x03B\x91\x01\n" +
	"1build.buf.gen.ssforge.routeiq.routeiq.v1.insightsB\bSloProtoZRbuf.build/gen/go/ssforge/routeiq/protocolbuffers/go/routeiq/v1/insights;insightsv1b\x06proto3"

var (
	file_routeiq_v1_insights_slo_proto_rawDescOnce sync.Once
	file_routeiq_v1_insights_slo_proto_rawDescData []byte
)

func file_routeiq_v1_insights_slo_proto_rawDescGZIP() []byte {
	file_routeiq_v1_insights_slo_proto_rawDescOnce.Do(func() {
		file_routeiq_v1_insights_slo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_routeiq_v1_insights_slo_proto_rawDesc), len(file_routeiq_v1_insights_slo_proto_rawDesc)))
	})
	return file_routeiq_v1_insights_slo_proto_rawDescData
}

var file_routeiq_v1_insights_slo_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_routeiq_v1_insights_slo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_routeiq_v1_insights_slo_proto_goTypes = []any{
	(SloState)(0),                 // 0: routeiq.v1.insights.SloState
	(*SloTarget)(nil),             // 1: routeiq.v1.insights.SloTarget
	(*SloStatus)(nil),             // 2: routeiq.v1.insights.SloStatus
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_routeiq_v1_insights_slo_proto_depIdxs = []int32{
	0, // 0: routeiq.v1.insights.SloStatus.state:type_name -> routeiq.v1.insights.SloState
	3, // 1: routeiq.v1.insights.SloStatus.evaluated_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_routeiq_v1_insights_slo_proto_init() }
func file_routeiq_v1_insights_slo_proto_init() {
	if File_routeiq_v1_insights_slo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_routeiq_v1_insights_slo_proto_rawDesc), len(file_routeiq_v1_insights_slo_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_routeiq_v1_insights_slo_proto_goTypes,
		DependencyIndexes: file_routeiq_v1_insights_slo_proto_depIdxs,
		EnumInfos:         file_routeiq_v1_insights_slo_proto_enumTypes,
		MessageInfos:      file_routeiq_v1_insights_slo_proto_msgTypes,
	}.Build()
	File_routeiq_v1_insights_slo_proto = out.File
	file_routeiq_v1_insights_slo_proto_goTypes = nil
	file_routeiq_v1_insights_slo_proto_depIdxs = nil
}
