// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: routeiq/v1/control/escalation.proto

package controlv1connect

import (
	control "buf.build/gen/go/ssforge/routeiq/protocolbuffers/go/routeiq/v1/control"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// EscalationServiceName is the fully-qualified name of the EscalationService service.
	EscalationServiceName = "routeiq.v1.control.EscalationService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// EscalationServiceEscalateProcedure is the fully-qualified name of the EscalationService's
	// Escalate RPC.
	EscalationServiceEscalateProcedure = "/routeiq.v1.control.EscalationService/Escalate"
	// EscalationServiceResolveEscalationProcedure is the fully-qualified name of the
	// EscalationService's ResolveEscalation RPC.
	EscalationServiceResolveEscalationProcedure = "/routeiq.v1.control.EscalationService/ResolveEscalation"
)

// EscalationServiceClient is a client for the routeiq.v1.control.EscalationService service.
type EscalationServiceClient interface {
	Escalate(context.Context, *connect.Request[control.EscalateRequest]) (*connect.Response[control.EscalateResponse], error)
	ResolveEscalation(context.Context, *connect.Request[control.ResolveEscalationRequest]) (*connect.Response[control.ResolveEscalationResponse], error)
}

// NewEscalationServiceClient constructs a client for the routeiq.v1.control.EscalationService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewEscalationServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) EscalationServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	escalationServiceMethods := control.File_routeiq_v1_control_escalation_proto.Services().ByName("EscalationService").Methods()
	return &escalationServiceClient{
		escalate: connect.NewClient[control.EscalateRequest, control.EscalateResponse](
			httpClient,
			baseURL+EscalationServiceEscalateProcedure,
			connect.WithSchema(escalationServiceMethods.ByName("Escalate")),
			connect.WithClientOptions(opts...),
		),
		resolveEscalation: connect.NewClient[control.ResolveEscalationRequest, control.ResolveEscalationResponse](
			httpClient,
			baseURL+EscalationServiceResolveEscalationProcedure,
			connect.WithSchema(escalationServiceMethods.ByName("ResolveEscalation")),
			connect.WithClientOptions(opts...),
		),
	}
}

// escalationServiceClient implements EscalationServiceClient.
type escalationServiceClient struct {
	escalate          *connect.Client[control.EscalateRequest, control.EscalateResponse]
	resolveEscalation *connect.Client[control.ResolveEscalationRequest, control.ResolveEscalationResponse]
}

// Escalate calls routeiq.v1.control.EscalationService.Escalate.
func (c *escalationServiceClient) Escalate(ctx context.Context, req *connect.Request[control.EscalateRequest]) (*connect.Response[control.EscalateResponse], error) {
	return c.escalate.CallUnary(ctx, req)
}

// ResolveEscalation calls routeiq.v1.control.EscalationService.ResolveEscalation.
func (c *escalationServiceClient) ResolveEscalation(ctx context.Context, req *connect.Request[control.ResolveEscalationRequest]) (*connect.Response[control.ResolveEscalationResponse], error) {
	return c.resolveEscalation.CallUnary(ctx, req)
}

// EscalationServiceHandler is an implementation of the routeiq.v1.control.EscalationService
// service.
type EscalationServiceHandler interface {
	Escalate(context.Context, *connect.Request[control.EscalateRequest]) (*connect.Response[control.EscalateResponse], error)
	ResolveEscalation(context.Context, *connect.Request[control.ResolveEscalationRequest]) (*connect.Response[control.ResolveEscalationResponse], error)
}

// NewEscalationServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewEscalationServiceHandler(svc EscalationServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	escalationServiceMethods := control.File_routeiq_v1_control_escalation_proto.Services().ByName("EscalationService").Methods()
	escalationServiceEscalateHandler := connect.NewUnaryHandler(
		EscalationServiceEscalateProcedure,
		svc.Escalate,
		connect.WithSchema(escalationServiceMethods.ByName("Escalate")),
		connect.WithHandlerOptions(opts...),
	)
	escalationServiceResolveEscalationHandler := connect.NewUnaryHandler(
		EscalationServiceResolveEscalationProcedure,
		svc.ResolveEscalation,
		connect.WithSchema(escalationServiceMethods.ByName("ResolveEscalation")),
		connect.WithHandlerOptions(opts...),
	)
	return "/routeiq.v1.control.EscalationService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case EscalationServiceEscalateProcedure:
			escalationServiceEscalateHandler.ServeHTTP(w, r)
		case EscalationServiceResolveEscalationProcedure:
			escalationServiceResolveEscalationHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedEscalationServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedEscalationServiceHandler struct{}

func (UnimplementedEscalationServiceHandler) Escalate(context.Context, *connect.Request[control.EscalateRequest]) (*connect.Response[control.EscalateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("routeiq.v1.control.EscalationService.Escalate is not implemented"))
}

func (UnimplementedEscalationServiceHandler) ResolveEscalation(context.Context, *connect.Request[control.ResolveEscalationRequest]) (*connect.Response[control.ResolveEscalationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("routeiq.v1.control.EscalationService.ResolveEscalation is not implemented"))
}
