// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: routeiq/v1/control/guardrail.proto

package controlv1connect

import (
	control "buf.build/gen/go/ssforge/routeiq/protocolbuffers/go/routeiq/v1/control"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// GuardrailServiceName is the fully-qualified name of the GuardrailService service.
	GuardrailServiceName = "routeiq.v1.control.GuardrailService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// GuardrailServiceCheckGuardrailProcedure is the fully-qualified name of the GuardrailService's
	// CheckGuardrail RPC.
	GuardrailServiceCheckGuardrailProcedure = "/routeiq.v1.control.GuardrailService/CheckGuardrail"
	// GuardrailServiceRegisterPolicyProcedure is the fully-qualified name of the GuardrailService's
	// RegisterPolicy RPC.
	GuardrailServiceRegisterPolicyProcedure = "/routeiq.v1.control.GuardrailService/RegisterPolicy"
)

// GuardrailServiceClient is a client for the routeiq.v1.control.GuardrailService service.
type GuardrailServiceClient interface {
	CheckGuardrail(context.Context, *connect.Request[control.CheckGuardrailRequest]) (*connect.Response[control.CheckGuardrailResponse], error)
	RegisterPolicy(context.Context, *connect.Request[control.RegisterPolicyRequest]) (*connect.Response[control.RegisterPolicyResponse], error)
}

// NewGuardrailServiceClient constructs a client for the routeiq.v1.control.GuardrailService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewGuardrailServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) GuardrailServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	guardrailServiceMethods := control.File_routeiq_v1_control_guardrail_proto.Services().ByName("GuardrailService").Methods()
	return &guardrailServiceClient{
		checkGuardrail: connect.NewClient[control.CheckGuardrailRequest, control.CheckGuardrailResponse](
			httpClient,
			baseURL+GuardrailServiceCheckGuardrailProcedure,
			connect.WithSchema(guardrailServiceMethods.ByName("CheckGuardrail")),
			connect.WithClientOptions(opts...),
		),
		registerPolicy: connect.NewClient[control.RegisterPolicyRequest, control.RegisterPolicyResponse](
			httpClient,
			baseURL+GuardrailServiceRegisterPolicyProcedure,
			connect.WithSchema(guardrailServiceMethods.ByName("RegisterPolicy")),
			connect.WithClientOptions(opts...),
		),
	}
}

// guardrailServiceClient implements GuardrailServiceClient.
type guardrailServiceClient struct {
	checkGuardrail *connect.Client[control.CheckGuardrailRequest, control.CheckGuardrailResponse]
	registerPolicy *connect.Client[control.RegisterPolicyRequest, control.RegisterPolicyResponse]
}

// CheckGuardrail calls routeiq.v1.control.GuardrailService.CheckGuardrail.
func (c *guardrailServiceClient) CheckGuardrail(ctx context.Context, req *connect.Request[control.CheckGuardrailRequest]) (*connect.Response[control.CheckGuardrailResponse], error) {
	return c.checkGuardrail.CallUnary(ctx, req)
}

// RegisterPolicy calls routeiq.v1.control.GuardrailService.RegisterPolicy.
func (c *guardrailServiceClient) RegisterPolicy(ctx context.Context, req *connect.Request[control.RegisterPolicyRequest]) (*connect.Response[control.RegisterPolicyResponse], error) {
	return c.registerPolicy.CallUnary(ctx, req)
}

// GuardrailServiceHandler is an implementation of the routeiq.v1.control.GuardrailService service.
type GuardrailServiceHandler interface {
	CheckGuardrail(context.Context, *connect.Request[control.CheckGuardrailRequest]) (*connect.Response[control.CheckGuardrailResponse], error)
	RegisterPolicy(context.Context, *connect.Request[control.RegisterPolicyRequest]) (*connect.Response[control.RegisterPolicyResponse], error)
}

// NewGuardrailServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewGuardrailServiceHandler(svc GuardrailServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	guardrailServiceMethods := control.File_routeiq_v1_control_guardrail_proto.Services().ByName("GuardrailService").Methods()
	guardrailServiceCheckGuardrailHandler := connect.NewUnaryHandler(
		GuardrailServiceCheckGuardrailProcedure,
		svc.CheckGuardrail,
		connect.WithSchema(guardrailServiceMethods.ByName("CheckGuardrail")),
		connect.WithHandlerOptions(opts...),
	)
	guardrailServiceRegisterPolicyHandler := connect.NewUnaryHandler(
		GuardrailServiceRegisterPolicyProcedure,
		svc.RegisterPolicy,
		connect.WithSchema(guardrailServiceMethods.ByName("RegisterPolicy")),
		connect.WithHandlerOptions(opts...),
	)
	return "/routeiq.v1.control.GuardrailService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case GuardrailServiceCheckGuardrailProcedure:
			guardrailServiceCheckGuardrailHandler.ServeHTTP(w, r)
		case GuardrailServiceRegisterPolicyProcedure:
			guardrailServiceRegisterPolicyHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedGuardrailServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedGuardrailServiceHandler struct{}

func (UnimplementedGuardrailServiceHandler) CheckGuardrail(context.Context, *connect.Request[control.CheckGuardrailRequest]) (*connect.Response[control.CheckGuardrailResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("routeiq.v1.control.GuardrailService.CheckGuardrail is not implemented"))
}

func (UnimplementedGuardrailServiceHandler) RegisterPolicy(context.Context, *connect.Request[control.RegisterPolicyRequest]) (*connect.Response[control.RegisterPolicyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("routeiq.v1.control.GuardrailService.RegisterPolicy is not implemented"))
}
