// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: routeiq/v1/control/intervention.proto

package controlv1connect

import (
	control "buf.build/gen/go/ssforge/routeiq/protocolbuffers/go/routeiq/v1/control"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// InterventionServiceName is the fully-qualified name of the InterventionService service.
	InterventionServiceName = "routeiq.v1.control.InterventionService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// InterventionServiceTriggerInterventionProcedure is the fully-qualified name of the
	// InterventionService's TriggerIntervention RPC.
	InterventionServiceTriggerInterventionProcedure = "/routeiq.v1.control.InterventionService/TriggerIntervention"
	// InterventionServiceGetInterventionStatusProcedure is the fully-qualified name of the
	// InterventionService's GetInterventionStatus RPC.
	InterventionServiceGetInterventionStatusProcedure = "/routeiq.v1.control.InterventionService/GetInterventionStatus"
)

// InterventionServiceClient is a client for the routeiq.v1.control.InterventionService service.
type InterventionServiceClient interface {
	TriggerIntervention(context.Context, *connect.Request[control.TriggerInterventionRequest]) (*connect.Response[control.TriggerInterventionResponse], error)
	GetInterventionStatus(context.Context, *connect.Request[control.GetInterventionStatusRequest]) (*connect.Response[control.GetInterventionStatusResponse], error)
}

// NewInterventionServiceClient constructs a client for the routeiq.v1.control.InterventionService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewInterventionServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) InterventionServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	interventionServiceMethods := control.File_routeiq_v1_control_intervention_proto.Services().ByName("InterventionService").Methods()
	return &interventionServiceClient{
		triggerIntervention: connect.NewClient[control.TriggerInterventionRequest, control.TriggerInterventionResponse](
			httpClient,
			baseURL+InterventionServiceTriggerInterventionProcedure,
			connect.WithSchema(interventionServiceMethods.ByName("TriggerIntervention")),
			connect.WithClientOptions(opts...),
		),
		getInterventionStatus: connect.NewClient[control.GetInterventionStatusRequest, control.GetInterventionStatusResponse](
			httpClient,
			baseURL+InterventionServiceGetInterventionStatusProcedure,
			connect.WithSchema(interventionServiceMethods.ByName("GetInterventionStatus")),
			connect.WithClientOptions(opts...),
		),
	}
}

// interventionServiceClient implements InterventionServiceClient.
type interventionServiceClient struct {
	triggerIntervention   *connect.Client[control.TriggerInterventionRequest, control.TriggerInterventionResponse]
	getInterventionStatus *connect.Client[control.GetInterventionStatusRequest, control.GetInterventionStatusResponse]
}

// TriggerIntervention calls routeiq.v1.control.InterventionService.TriggerIntervention.
func (c *interventionServiceClient) TriggerIntervention(ctx context.Context, req *connect.Request[control.TriggerInterventionRequest]) (*connect.Response[control.TriggerInterventionResponse], error) {
	return c.triggerIntervention.CallUnary(ctx, req)
}

// GetInterventionStatus calls routeiq.v1.control.InterventionService.GetInterventionStatus.
func (c *interventionServiceClient) GetInterventionStatus(ctx context.Context, req *connect.Request[control.GetInterventionStatusRequest]) (*connect.Response[control.GetInterventionStatusResponse], error) {
	return c.getInterventionStatus.CallUnary(ctx, req)
}

// InterventionServiceHandler is an implementation of the routeiq.v1.control.InterventionService
// service.
type InterventionServiceHandler interface {
	TriggerIntervention(context.Context, *connect.Request[control.TriggerInterventionRequest]) (*connect.Response[control.TriggerInterventionResponse], error)
	GetInterventionStatus(context.Context, *connect.Request[control.GetInterventionStatusRequest]) (*connect.Response[control.GetInterventionStatusResponse], error)
}

// NewInterventionServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewInterventionServiceHandler(svc InterventionServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	interventionServiceMethods := control.File_routeiq_v1_control_intervention_proto.Services().ByName("InterventionService").Methods()
	interventionServiceTriggerInterventionHandler := connect.NewUnaryHandler(
		InterventionServiceTriggerInterventionProcedure,
		svc.TriggerIntervention,
		connect.WithSchema(interventionServiceMethods.ByName("TriggerIntervention")),
		connect.WithHandlerOptions(opts...),
	)
	interventionServiceGetInterventionStatusHandler := connect.NewUnaryHandler(
		InterventionServiceGetInterventionStatusProcedure,
		svc.GetInterventionStatus,
		connect.WithSchema(interventionServiceMethods.ByName("GetInterventionStatus")),
		connect.WithHandlerOptions(opts...),
	)
	return "/routeiq.v1.control.InterventionService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case InterventionServiceTriggerInterventionProcedure:
			interventionServiceTriggerInterventionHandler.ServeHTTP(w, r)
		case InterventionServiceGetInterventionStatusProcedure:
			interventionServiceGetInterventionStatusHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedInterventionServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedInterventionServiceHandler struct{}

func (UnimplementedInterventionServiceHandler) TriggerIntervention(context.Context, *connect.Request[control.TriggerInterventionRequest]) (*connect.Response[control.TriggerInterventionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("routeiq.v1.control.InterventionService.TriggerIntervention is not implemented"))
}

func (UnimplementedInterventionServiceHandler) GetInterventionStatus(context.Context, *connect.Request[control.GetInterventionStatusRequest]) (*connect.Response[control.GetInterventionStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("routeiq.v1.control.InterventionService.GetInterventionStatus is not implemented"))
}
