// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: routeiq/v1/control/session.proto

package controlv1connect

import (
	control "buf.build/gen/go/ssforge/routeiq/protocolbuffers/go/routeiq/v1/control"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SessionServiceName is the fully-qualified name of the SessionService service.
	SessionServiceName = "routeiq.v1.control.SessionService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SessionServiceStartSessionProcedure is the fully-qualified name of the SessionService's
	// StartSession RPC.
	SessionServiceStartSessionProcedure = "/routeiq.v1.control.SessionService/StartSession"
	// SessionServiceEndSessionProcedure is the fully-qualified name of the SessionService's EndSession
	// RPC.
	SessionServiceEndSessionProcedure = "/routeiq.v1.control.SessionService/EndSession"
	// SessionServiceUpdateStateProcedure is the fully-qualified name of the SessionService's
	// UpdateState RPC.
	SessionServiceUpdateStateProcedure = "/routeiq.v1.control.SessionService/UpdateState"
)

// SessionServiceClient is a client for the routeiq.v1.control.SessionService service.
type SessionServiceClient interface {
	StartSession(context.Context, *connect.Request[control.StartSessionRequest]) (*connect.Response[control.StartSessionResponse], error)
	EndSession(context.Context, *connect.Request[control.EndSessionRequest]) (*connect.Response[control.EndSessionResponse], error)
	UpdateState(context.Context, *connect.Request[control.UpdateStateRequest]) (*connect.Response[control.UpdateStateResponse], error)
}

// NewSessionServiceClient constructs a client for the routeiq.v1.control.SessionService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSessionServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SessionServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	sessionServiceMethods := control.File_routeiq_v1_control_session_proto.Services().ByName("SessionService").Methods()
	return &sessionServiceClient{
		startSession: connect.NewClient[control.StartSessionRequest, control.StartSessionResponse](
			httpClient,
			baseURL+SessionServiceStartSessionProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("StartSession")),
			connect.WithClientOptions(opts...),
		),
		endSession: connect.NewClient[control.EndSessionRequest, control.EndSessionResponse](
			httpClient,
			baseURL+SessionServiceEndSessionProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("EndSession")),
			connect.WithClientOptions(opts...),
		),
		updateState: connect.NewClient[control.UpdateStateRequest, control.UpdateStateResponse](
			httpClient,
			baseURL+SessionServiceUpdateStateProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("UpdateState")),
			connect.WithClientOptions(opts...),
		),
	}
}

// sessionServiceClient implements SessionServiceClient.
type sessionServiceClient struct {
	startSession *connect.Client[control.StartSessionRequest, control.StartSessionResponse]
	endSession   *connect.Client[control.EndSessionRequest, control.EndSessionResponse]
	updateState  *connect.Client[control.UpdateStateRequest, control.UpdateStateResponse]
}

// StartSession calls routeiq.v1.control.SessionService.StartSession.
func (c *sessionServiceClient) StartSession(ctx context.Context, req *connect.Request[control.StartSessionRequest]) (*connect.Response[control.StartSessionResponse], error) {
	return c.startSession.CallUnary(ctx, req)
}

// EndSession calls routeiq.v1.control.SessionService.EndSession.
func (c *sessionServiceClient) EndSession(ctx context.Context, req *connect.Request[control.EndSessionRequest]) (*connect.Response[control.EndSessionResponse], error) {
	return c.endSession.CallUnary(ctx, req)
}

// UpdateState calls routeiq.v1.control.SessionService.UpdateState.
func (c *sessionServiceClient) UpdateState(ctx context.Context, req *connect.Request[control.UpdateStateRequest]) (*connect.Response[control.UpdateStateResponse], error) {
	return c.updateState.CallUnary(ctx, req)
}

// SessionServiceHandler is an implementation of the routeiq.v1.control.SessionService service.
type SessionServiceHandler interface {
	StartSession(context.Context, *connect.Request[control.StartSessionRequest]) (*connect.Response[control.StartSessionResponse], error)
	EndSession(context.Context, *connect.Request[control.EndSessionRequest]) (*connect.Response[control.EndSessionResponse], error)
	UpdateState(context.Context, *connect.Request[control.UpdateStateRequest]) (*connect.Response[control.UpdateStateResponse], error)
}

// NewSessionServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSessionServiceHandler(svc SessionServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	sessionServiceMethods := control.File_routeiq_v1_control_session_proto.Services().ByName("SessionService").Methods()
	sessionServiceStartSessionHandler := connect.NewUnaryHandler(
		SessionServiceStartSessionProcedure,
		svc.StartSession,
		connect.WithSchema(sessionServiceMethods.ByName("StartSession")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceEndSessionHandler := connect.NewUnaryHandler(
		SessionServiceEndSessionProcedure,
		svc.EndSession,
		connect.WithSchema(sessionServiceMethods.ByName("EndSession")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceUpdateStateHandler := connect.NewUnaryHandler(
		SessionServiceUpdateStateProcedure,
		svc.UpdateState,
		connect.WithSchema(sessionServiceMethods.ByName("UpdateState")),
		connect.WithHandlerOptions(opts...),
	)
	return "/routeiq.v1.control.SessionService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SessionServiceStartSessionProcedure:
			sessionServiceStartSessionHandler.ServeHTTP(w, r)
		case SessionServiceEndSessionProcedure:
			sessionServiceEndSessionHandler.ServeHTTP(w, r)
		case SessionServiceUpdateStateProcedure:
			sessionServiceUpdateStateHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSessionServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSessionServiceHandler struct{}

func (UnimplementedSessionServiceHandler) StartSession(context.Context, *connect.Request[control.StartSessionRequest]) (*connect.Response[control.StartSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("routeiq.v1.control.SessionService.StartSession is not implemented"))
}

func (UnimplementedSessionServiceHandler) EndSession(context.Context, *connect.Request[control.EndSessionRequest]) (*connect.Response[control.EndSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("routeiq.v1.control.SessionService.EndSession is not implemented"))
}

func (UnimplementedSessionServiceHandler) UpdateState(context.Context, *connect.Request[control.UpdateStateRequest]) (*connect.Response[control.UpdateStateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("routeiq.v1.control.SessionService.UpdateState is not implemented"))
}
