// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: routeiq/v1/telemetry/conventions.proto

package telemetryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SemanticConvention maps a typed proto field to its OTel span attribute key.
// Read by the SDK code generator to emit the right attribute keys.
// Read by routeiq_validator (collector component) to validate incoming spans.
type SemanticConvention struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ProtoFieldPath   string                 `protobuf:"bytes,1,opt,name=proto_field_path,json=protoFieldPath,proto3" json:"proto_field_path,omitempty"`       // e.g. "TaskEvent.completion_status"
	OtelAttributeKey string                 `protobuf:"bytes,2,opt,name=otel_attribute_key,json=otelAttributeKey,proto3" json:"otel_attribute_key,omitempty"` // e.g. "routeiq.task.completion_status"
	Type             AttributeType          `protobuf:"varint,3,opt,name=type,proto3,enum=routeiq.v1.telemetry.AttributeType" json:"type,omitempty"`
	Required         bool                   `protobuf:"varint,4,opt,name=required,proto3" json:"required,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SemanticConvention) Reset() {
	*x = SemanticConvention{}
	mi := &file_routeiq_v1_telemetry_conventions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SemanticConvention) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SemanticConvention) ProtoMessage() {}

func (x *SemanticConvention) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_telemetry_conventions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SemanticConvention.ProtoReflect.Descriptor instead.
func (*SemanticConvention) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_telemetry_conventions_proto_rawDescGZIP(), []int{0}
}

func (x *SemanticConvention) GetProtoFieldPath() string {
	if x != nil {
		return x.ProtoFieldPath
	}
	return ""
}

func (x *SemanticConvention) GetOtelAttributeKey() string {
	if x != nil {
		return x.OtelAttributeKey
	}
	return ""
}

func (x *SemanticConvention) GetType() AttributeType {
	if x != nil {
		return x.Type
	}
	return AttributeType_ATTRIBUTE_TYPE_UNSPECIFIED
}

func (x *SemanticConvention) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

// ConventionRegistry is the root message for conventions/telemetry.yaml.
// Every AgentEvent field that appears on the wire must have an entry here.
type ConventionRegistry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conventions   []*SemanticConvention  `protobuf:"bytes,1,rep,name=conventions,proto3" json:"conventions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConventionRegistry) Reset() {
	*x = ConventionRegistry{}
	mi := &file_routeiq_v1_telemetry_conventions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConventionRegistry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConventionRegistry) ProtoMessage() {}

func (x *ConventionRegistry) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_telemetry_conventions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConventionRegistry.ProtoReflect.Descriptor instead.
func (*ConventionRegistry) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_telemetry_conventions_proto_rawDescGZIP(), []int{1}
}

func (x *ConventionRegistry) GetConventions() []*SemanticConvention {
	if x != nil {
		return x.Conventions
	}
	return nil
}

var File_routeiq_v1_telemetry_conventions_proto protoreflect.FileDescriptor

const file_routeiq_v1_telemetry_conventions_proto_rawDesc = "" +
	"\n" +
	"&routeiq/v1/telemetry/conventions.proto\x12\x14routeiq.v1.telemetry\x1a#routeiq/v1/telemetry/entities.proto\"\xc1\x01\n" +
	"\x12SemanticConvention\x12(\n" +
	"\x10proto_field_path\x18\x01 \x01(\tR\x0eprotoFieldPath\x12,\n" +
	"\x12otel_attribute_key\x18\x02 \x01(\tR\x10otelAttributeKey\x127\n" +
	"\x04type\x18\x03 \x01(\x0e2#.routeiq.v1.telemetry.AttributeTypeR\x04type\x12\x1a\n" +
	"\brequired\x18\x04 \x01(\bR\brequired\"`\n" +
	"\x12ConventionRegistry\x12J\n" +
	"\vconventions\x18\x01 \x03(\v2(.routeiq.v1.telemetry.SemanticConventionR\vconventionsB\x9c\x01\n" +
	"2build.buf.gen.ssforge.routeiq.routeiq.v1.telemetryB\x10ConventionsProtoZTbuf.build/gen/go/ssforge/routeiq/protocolbuffers/go/routeiq/v1/telemetry;telemetryv1b\x06proto3"

var (
	file_routeiq_v1_telemetry_conventions_proto_rawDescOnce sync.Once
	file_routeiq_v1_telemetry_conventions_proto_rawDescData []byte
)

func file_routeiq_v1_telemetry_conventions_proto_rawDescGZIP() []byte {
	file_routeiq_v1_telemetry_conventions_proto_rawDescOnce.Do(func() {
		file_routeiq_v1_telemetry_conventions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_routeiq_v1_telemetry_conventions_proto_rawDesc), len(file_routeiq_v1_telemetry_conventions_proto_rawDesc)))
	})
	return file_routeiq_v1_telemetry_conventions_proto_rawDescData
}

var file_routeiq_v1_telemetry_conventions_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_routeiq_v1_telemetry_conventions_proto_goTypes = []any{
	(*SemanticConvention)(nil), // 0: routeiq.v1.telemetry.SemanticConvention
	(*ConventionRegistry)(nil), // 1: routeiq.v1.telemetry.ConventionRegistry
	(AttributeType)(0),         // 2: routeiq.v1.telemetry.AttributeType
}
var file_routeiq_v1_telemetry_conventions_proto_depIdxs = []int32{
	2, // 0: routeiq.v1.telemetry.SemanticConvention.type:type_name -> routeiq.v1.telemetry.AttributeType
	0, // 1: routeiq.v1.telemetry.ConventionRegistry.conventions:type_name -> routeiq.v1.telemetry.SemanticConvention
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_routeiq_v1_telemetry_conventions_proto_init() }
func file_routeiq_v1_telemetry_conventions_proto_init() {
	if File_routeiq_v1_telemetry_conventions_proto != nil {
		return
	}
	file_routeiq_v1_telemetry_entities_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_routeiq_v1_telemetry_conventions_proto_rawDesc), len(file_routeiq_v1_telemetry_conventions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_routeiq_v1_telemetry_conventions_proto_goTypes,
		DependencyIndexes: file_routeiq_v1_telemetry_conventions_proto_depIdxs,
		MessageInfos:      file_routeiq_v1_telemetry_conventions_proto_msgTypes,
	}.Build()
	File_routeiq_v1_telemetry_conventions_proto = out.File
	file_routeiq_v1_telemetry_conventions_proto_goTypes = nil
	file_routeiq_v1_telemetry_conventions_proto_depIdxs = nil
}
