// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: routeiq/v1/telemetry/entities.proto

package telemetryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CompletionStatus int32

const (
	CompletionStatus_COMPLETION_STATUS_UNSPECIFIED CompletionStatus = 0
	CompletionStatus_SUCCESS                       CompletionStatus = 1
	CompletionStatus_FAILURE                       CompletionStatus = 2
	CompletionStatus_PARTIAL                       CompletionStatus = 3
	CompletionStatus_CANCELLED                     CompletionStatus = 4
	CompletionStatus_TIMEOUT                       CompletionStatus = 5
)

// Enum value maps for CompletionStatus.
var (
	CompletionStatus_name = map[int32]string{
		0: "COMPLETION_STATUS_UNSPECIFIED",
		1: "SUCCESS",
		2: "FAILURE",
		3: "PARTIAL",
		4: "CANCELLED",
		5: "TIMEOUT",
	}
	CompletionStatus_value = map[string]int32{
		"COMPLETION_STATUS_UNSPECIFIED": 0,
		"SUCCESS":                       1,
		"FAILURE":                       2,
		"PARTIAL":                       3,
		"CANCELLED":                     4,
		"TIMEOUT":                       5,
	}
)

func (x CompletionStatus) Enum() *CompletionStatus {
	p := new(CompletionStatus)
	*p = x
	return p
}

func (x CompletionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CompletionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_routeiq_v1_telemetry_entities_proto_enumTypes[0].Descriptor()
}

func (CompletionStatus) Type() protoreflect.EnumType {
	return &file_routeiq_v1_telemetry_entities_proto_enumTypes[0]
}

func (x CompletionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CompletionStatus.Descriptor instead.
func (CompletionStatus) EnumDescriptor() ([]byte, []int) {
	return file_routeiq_v1_telemetry_entities_proto_rawDescGZIP(), []int{0}
}

type FailureCategory int32

const (
	FailureCategory_FAILURE_CATEGORY_UNSPECIFIED FailureCategory = 0
	FailureCategory_TOOL_ERROR                   FailureCategory = 1
	FailureCategory_MODEL_ERROR                  FailureCategory = 2
	FailureCategory_POLICY_BLOCK                 FailureCategory = 3
	FailureCategory_LOOP_DETECTED                FailureCategory = 4
	FailureCategory_TIMEOUT_EXCEEDED             FailureCategory = 5
	FailureCategory_HUMAN_CANCELLED              FailureCategory = 6
	FailureCategory_RESOURCE_EXHAUSTED           FailureCategory = 7
	FailureCategory_CONTEXT_OVERFLOW             FailureCategory = 8
)

// Enum value maps for FailureCategory.
var (
	FailureCategory_name = map[int32]string{
		0: "FAILURE_CATEGORY_UNSPECIFIED",
		1: "TOOL_ERROR",
		2: "MODEL_ERROR",
		3: "POLICY_BLOCK",
		4: "LOOP_DETECTED",
		5: "TIMEOUT_EXCEEDED",
		6: "HUMAN_CANCELLED",
		7: "RESOURCE_EXHAUSTED",
		8: "CONTEXT_OVERFLOW",
	}
	FailureCategory_value = map[string]int32{
		"FAILURE_CATEGORY_UNSPECIFIED": 0,
		"TOOL_ERROR":                   1,
		"MODEL_ERROR":                  2,
		"POLICY_BLOCK":                 3,
		"LOOP_DETECTED":                4,
		"TIMEOUT_EXCEEDED":             5,
		"HUMAN_CANCELLED":              6,
		"RESOURCE_EXHAUSTED":           7,
		"CONTEXT_OVERFLOW":             8,
	}
)

func (x FailureCategory) Enum() *FailureCategory {
	p := new(FailureCategory)
	*p = x
	return p
}

func (x FailureCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FailureCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_routeiq_v1_telemetry_entities_proto_enumTypes[1].Descriptor()
}

func (FailureCategory) Type() protoreflect.EnumType {
	return &file_routeiq_v1_telemetry_entities_proto_enumTypes[1]
}

func (x FailureCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FailureCategory.Descriptor instead.
func (FailureCategory) EnumDescriptor() ([]byte, []int) {
	return file_routeiq_v1_telemetry_entities_proto_rawDescGZIP(), []int{1}
}

type AutonomyMode int32

const (
	AutonomyMode_AUTONOMY_MODE_UNSPECIFIED AutonomyMode = 0
	AutonomyMode_SUPERVISED                AutonomyMode = 1
	AutonomyMode_SEMI_AUTONOMOUS           AutonomyMode = 2
	AutonomyMode_AUTONOMOUS                AutonomyMode = 3
)

// Enum value maps for AutonomyMode.
var (
	AutonomyMode_name = map[int32]string{
		0: "AUTONOMY_MODE_UNSPECIFIED",
		1: "SUPERVISED",
		2: "SEMI_AUTONOMOUS",
		3: "AUTONOMOUS",
	}
	AutonomyMode_value = map[string]int32{
		"AUTONOMY_MODE_UNSPECIFIED": 0,
		"SUPERVISED":                1,
		"SEMI_AUTONOMOUS":           2,
		"AUTONOMOUS":                3,
	}
)

func (x AutonomyMode) Enum() *AutonomyMode {
	p := new(AutonomyMode)
	*p = x
	return p
}

func (x AutonomyMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AutonomyMode) Descriptor() protoreflect.EnumDescriptor {
	return file_routeiq_v1_telemetry_entities_proto_enumTypes[2].Descriptor()
}

func (AutonomyMode) Type() protoreflect.EnumType {
	return &file_routeiq_v1_telemetry_entities_proto_enumTypes[2]
}

func (x AutonomyMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AutonomyMode.Descriptor instead.
func (AutonomyMode) EnumDescriptor() ([]byte, []int) {
	return file_routeiq_v1_telemetry_entities_proto_rawDescGZIP(), []int{2}
}

type RiskTier int32

const (
	RiskTier_RISK_TIER_UNSPECIFIED RiskTier = 0
	RiskTier_LOW                   RiskTier = 1
	RiskTier_MEDIUM                RiskTier = 2
	RiskTier_HIGH                  RiskTier = 3
	RiskTier_CRITICAL              RiskTier = 4
)

// Enum value maps for RiskTier.
var (
	RiskTier_name = map[int32]string{
		0: "RISK_TIER_UNSPECIFIED",
		1: "LOW",
		2: "MEDIUM",
		3: "HIGH",
		4: "CRITICAL",
	}
	RiskTier_value = map[string]int32{
		"RISK_TIER_UNSPECIFIED": 0,
		"LOW":                   1,
		"MEDIUM":                2,
		"HIGH":                  3,
		"CRITICAL":              4,
	}
)

func (x RiskTier) Enum() *RiskTier {
	p := new(RiskTier)
	*p = x
	return p
}

func (x RiskTier) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RiskTier) Descriptor() protoreflect.EnumDescriptor {
	return file_routeiq_v1_telemetry_entities_proto_enumTypes[3].Descriptor()
}

func (RiskTier) Type() protoreflect.EnumType {
	return &file_routeiq_v1_telemetry_entities_proto_enumTypes[3]
}

func (x RiskTier) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RiskTier.Descriptor instead.
func (RiskTier) EnumDescriptor() ([]byte, []int) {
	return file_routeiq_v1_telemetry_entities_proto_rawDescGZIP(), []int{3}
}

type PermissionLevel int32

const (
	PermissionLevel_PERMISSION_LEVEL_UNSPECIFIED PermissionLevel = 0
	PermissionLevel_READ_ONLY                    PermissionLevel = 1
	PermissionLevel_READ_WRITE                   PermissionLevel = 2
	PermissionLevel_PRIVILEGED                   PermissionLevel = 3
	PermissionLevel_SYSTEM                       PermissionLevel = 4
)

// Enum value maps for PermissionLevel.
var (
	PermissionLevel_name = map[int32]string{
		0: "PERMISSION_LEVEL_UNSPECIFIED",
		1: "READ_ONLY",
		2: "READ_WRITE",
		3: "PRIVILEGED",
		4: "SYSTEM",
	}
	PermissionLevel_value = map[string]int32{
		"PERMISSION_LEVEL_UNSPECIFIED": 0,
		"READ_ONLY":                    1,
		"READ_WRITE":                   2,
		"PRIVILEGED":                   3,
		"SYSTEM":                       4,
	}
)

func (x PermissionLevel) Enum() *PermissionLevel {
	p := new(PermissionLevel)
	*p = x
	return p
}

func (x PermissionLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PermissionLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_routeiq_v1_telemetry_entities_proto_enumTypes[4].Descriptor()
}

func (PermissionLevel) Type() protoreflect.EnumType {
	return &file_routeiq_v1_telemetry_entities_proto_enumTypes[4]
}

func (x PermissionLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PermissionLevel.Descriptor instead.
func (PermissionLevel) EnumDescriptor() ([]byte, []int) {
	return file_routeiq_v1_telemetry_entities_proto_rawDescGZIP(), []int{4}
}

type ToolResultStatus int32

const (
	ToolResultStatus_TOOL_RESULT_STATUS_UNSPECIFIED ToolResultStatus = 0
	ToolResultStatus_TOOL_SUCCESS                   ToolResultStatus = 1
	ToolResultStatus_TOOL_FAILURE                   ToolResultStatus = 2
	ToolResultStatus_TOOL_TIMEOUT                   ToolResultStatus = 3
	ToolResultStatus_TOOL_PERMISSION_DENIED         ToolResultStatus = 4
)

// Enum value maps for ToolResultStatus.
var (
	ToolResultStatus_name = map[int32]string{
		0: "TOOL_RESULT_STATUS_UNSPECIFIED",
		1: "TOOL_SUCCESS",
		2: "TOOL_FAILURE",
		3: "TOOL_TIMEOUT",
		4: "TOOL_PERMISSION_DENIED",
	}
	ToolResultStatus_value = map[string]int32{
		"TOOL_RESULT_STATUS_UNSPECIFIED": 0,
		"TOOL_SUCCESS":                   1,
		"TOOL_FAILURE":                   2,
		"TOOL_TIMEOUT":                   3,
		"TOOL_PERMISSION_DENIED":         4,
	}
)

func (x ToolResultStatus) Enum() *ToolResultStatus {
	p := new(ToolResultStatus)
	*p = x
	return p
}

func (x ToolResultStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ToolResultStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_routeiq_v1_telemetry_entities_proto_enumTypes[5].Descriptor()
}

func (ToolResultStatus) Type() protoreflect.EnumType {
	return &file_routeiq_v1_telemetry_entities_proto_enumTypes[5]
}

func (x ToolResultStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ToolResultStatus.Descriptor instead.
func (ToolResultStatus) EnumDescriptor() ([]byte, []int) {
	return file_routeiq_v1_telemetry_entities_proto_rawDescGZIP(), []int{5}
}

type AttributeType int32

const (
	AttributeType_ATTRIBUTE_TYPE_UNSPECIFIED AttributeType = 0
	AttributeType_STRING                     AttributeType = 1
	AttributeType_INT64                      AttributeType = 2
	AttributeType_DOUBLE                     AttributeType = 3
	AttributeType_BOOL                       AttributeType = 4
	AttributeType_BYTES                      AttributeType = 5
	AttributeType_STRING_ARRAY               AttributeType = 6
)

// Enum value maps for AttributeType.
var (
	AttributeType_name = map[int32]string{
		0: "ATTRIBUTE_TYPE_UNSPECIFIED",
		1: "STRING",
		2: "INT64",
		3: "DOUBLE",
		4: "BOOL",
		5: "BYTES",
		6: "STRING_ARRAY",
	}
	AttributeType_value = map[string]int32{
		"ATTRIBUTE_TYPE_UNSPECIFIED": 0,
		"STRING":                     1,
		"INT64":                      2,
		"DOUBLE":                     3,
		"BOOL":                       4,
		"BYTES":                      5,
		"STRING_ARRAY":               6,
	}
)

func (x AttributeType) Enum() *AttributeType {
	p := new(AttributeType)
	*p = x
	return p
}

func (x AttributeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AttributeType) Descriptor() protoreflect.EnumDescriptor {
	return file_routeiq_v1_telemetry_entities_proto_enumTypes[6].Descriptor()
}

func (AttributeType) Type() protoreflect.EnumType {
	return &file_routeiq_v1_telemetry_entities_proto_enumTypes[6]
}

func (x AttributeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AttributeType.Descriptor instead.
func (AttributeType) EnumDescriptor() ([]byte, []int) {
	return file_routeiq_v1_telemetry_entities_proto_rawDescGZIP(), []int{6}
}

var File_routeiq_v1_telemetry_entities_proto protoreflect.FileDescriptor

const file_routeiq_v1_telemetry_entities_proto_rawDesc = "" +
	"\n" +
	"#routeiq/v1/telemetry/entities.proto\x12\x14routeiq.v1.telemetry*x\n" +
	"\x10CompletionStatus\x12!\n" +
	"\x1dCOMPLETION_STATUS_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aSUCCESS\x10\x01\x12\v\n" +
	"\aFAILURE\x10\x02\x12\v\n" +
	"\aPARTIAL\x10\x03\x12\r\n" +
	"\tCANCELLED\x10\x04\x12\v\n" +
	"\aTIMEOUT\x10\x05*\xd2\x01\n" +
	"\x0fFailureCategory\x12 \n" +
	"\x1cFAILURE_CATEGORY_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"TOOL_ERROR\x10\x01\x12\x0f\n" +
	"\vMODEL_ERROR\x10\x02\x12\x10\n" +
	"\fPOLICY_BLOCK\x10\x03\x12\x11\n" +
	"\rLOOP_DETECTED\x10\x04\x12\x14\n" +
	"\x10TIMEOUT_EXCEEDED\x10\x05\x12\x13\n" +
	"\x0fHUMAN_CANCELLED\x10\x06\x12\x16\n" +
	"\x12RESOURCE_EXHAUSTED\x10\a\x12\x14\n" +
	"\x10CONTEXT_OVERFLOW\x10\b*b\n" +
	"\fAutonomyMode\x12\x1d\n" +
	"\x19AUTONOMY_MODE_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"SUPERVISED\x10\x01\x12\x13\n" +
	"\x0fSEMI_AUTONOMOUS\x10\x02\x12\x0e\n" +
	"\n" +
	"AUTONOMOUS\x10\x03*R\n" +
	"\bRiskTier\x12\x19\n" +
	"\x15RISK_TIER_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03LOW\x10\x01\x12\n" +
	"\n" +
	"\x06MEDIUM\x10\x02\x12\b\n" +
	"\x04HIGH\x10\x03\x12\f\n" +
	"\bCRITICAL\x10\x04*n\n" +
	"\x0fPermissionLevel\x12 \n" +
	"\x1cPERMISSION_LEVEL_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tREAD_ONLY\x10\x01\x12\x0e\n" +
	"\n" +
	"READ_WRITE\x10\x02\x12\x0e\n" +
	"\n" +
	"PRIVILEGED\x10\x03\x12\n" +
	"\n" +
	"\x06SYSTEM\x10\x04*\x88\x01\n" +
	"\x10ToolResultStatus\x12\"\n" +
	"\x1eTOOL_RESULT_STATUS_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fTOOL_SUCCESS\x10\x01\x12\x10\n" +
	"\fTOOL_FAILURE\x10\x02\x12\x10\n" +
	"\fTOOL_TIMEOUT\x10\x03\x12\x1a\n" +
	"\x16TOOL_PERMISSION_DENIED\x10\x04*y\n" +
	"\rAttributeType\x12\x1e\n" +
	"\x1aATTRIBUTE_TYPE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06STRING\x10\x01\x12\t\n" +
	"\x05INT64\x10\x02\x12\n" +
	"\n" +
	"\x06DOUBLE\x10\x03\x12\b\n" +
	"\x04BOOL\x10\x04\x12\t\n" +
	"\x05BYTES\x10\x05\x12\x10\n" +
	"\fSTRING_ARRAY\x10\x06B\x99\x01\n" +
	"2build.buf.gen.ssforge.routeiq.routeiq.v1.telemetryB\rEntitiesProtoZTbuf.build/gen/go/ssforge/routeiq/protocolbuffers/go/routeiq/v1/telemetry;telemetryv1b\x06proto3"

var (
	file_routeiq_v1_telemetry_entities_proto_rawDescOnce sync.Once
	file_routeiq_v1_telemetry_entities_proto_rawDescData []byte
)

func file_routeiq_v1_telemetry_entities_proto_rawDescGZIP() []byte {
	file_routeiq_v1_telemetry_entities_proto_rawDescOnce.Do(func() {
		file_routeiq_v1_telemetry_entities_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_routeiq_v1_telemetry_entities_proto_rawDesc), len(file_routeiq_v1_telemetry_entities_proto_rawDesc)))
	})
	return file_routeiq_v1_telemetry_entities_proto_rawDescData
}

var file_routeiq_v1_telemetry_entities_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_routeiq_v1_telemetry_entities_proto_goTypes = []any{
	(CompletionStatus)(0), // 0: routeiq.v1.telemetry.CompletionStatus
	(FailureCategory)(0),  // 1: routeiq.v1.telemetry.FailureCategory
	(AutonomyMode)(0),     // 2: routeiq.v1.telemetry.AutonomyMode
	(RiskTier)(0),         // 3: routeiq.v1.telemetry.RiskTier
	(PermissionLevel)(0),  // 4: routeiq.v1.telemetry.PermissionLevel
	(ToolResultStatus)(0), // 5: routeiq.v1.telemetry.ToolResultStatus
	(AttributeType)(0),    // 6: routeiq.v1.telemetry.AttributeType
}
var file_routeiq_v1_telemetry_entities_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_routeiq_v1_telemetry_entities_proto_init() }
func file_routeiq_v1_telemetry_entities_proto_init() {
	if File_routeiq_v1_telemetry_entities_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_routeiq_v1_telemetry_entities_proto_rawDesc), len(file_routeiq_v1_telemetry_entities_proto_rawDesc)),
			NumEnums:      7,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_routeiq_v1_telemetry_entities_proto_goTypes,
		DependencyIndexes: file_routeiq_v1_telemetry_entities_proto_depIdxs,
		EnumInfos:         file_routeiq_v1_telemetry_entities_proto_enumTypes,
	}.Build()
	File_routeiq_v1_telemetry_entities_proto = out.File
	file_routeiq_v1_telemetry_entities_proto_goTypes = nil
	file_routeiq_v1_telemetry_entities_proto_depIdxs = nil
}
