// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: routeiq/v1/telemetry/events.proto

package telemetryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED  EventType = 0
	EventType_TASK_STARTED            EventType = 1
	EventType_TASK_COMPLETED          EventType = 2
	EventType_TASK_FAILED             EventType = 3
	EventType_STEP_STARTED            EventType = 4
	EventType_STEP_COMPLETED          EventType = 5
	EventType_DECISION_MADE           EventType = 6
	EventType_TOOL_CALLED             EventType = 7
	EventType_TOOL_RETURNED           EventType = 8
	EventType_RETRIEVAL_PERFORMED     EventType = 9
	EventType_MEMORY_READ             EventType = 10
	EventType_MEMORY_WRITTEN          EventType = 11
	EventType_HANDOFF_INITIATED       EventType = 12
	EventType_HANDOFF_ACCEPTED        EventType = 13
	EventType_POLICY_EVALUATED        EventType = 14
	EventType_INTERVENTION_TRIGGERED  EventType = 15
	EventType_RECOVERY_ATTEMPTED      EventType = 16
	EventType_STATE_SNAPSHOT_CAPTURED EventType = 17
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0:  "EVENT_TYPE_UNSPECIFIED",
		1:  "TASK_STARTED",
		2:  "TASK_COMPLETED",
		3:  "TASK_FAILED",
		4:  "STEP_STARTED",
		5:  "STEP_COMPLETED",
		6:  "DECISION_MADE",
		7:  "TOOL_CALLED",
		8:  "TOOL_RETURNED",
		9:  "RETRIEVAL_PERFORMED",
		10: "MEMORY_READ",
		11: "MEMORY_WRITTEN",
		12: "HANDOFF_INITIATED",
		13: "HANDOFF_ACCEPTED",
		14: "POLICY_EVALUATED",
		15: "INTERVENTION_TRIGGERED",
		16: "RECOVERY_ATTEMPTED",
		17: "STATE_SNAPSHOT_CAPTURED",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED":  0,
		"TASK_STARTED":            1,
		"TASK_COMPLETED":          2,
		"TASK_FAILED":             3,
		"STEP_STARTED":            4,
		"STEP_COMPLETED":          5,
		"DECISION_MADE":           6,
		"TOOL_CALLED":             7,
		"TOOL_RETURNED":           8,
		"RETRIEVAL_PERFORMED":     9,
		"MEMORY_READ":             10,
		"MEMORY_WRITTEN":          11,
		"HANDOFF_INITIATED":       12,
		"HANDOFF_ACCEPTED":        13,
		"POLICY_EVALUATED":        14,
		"INTERVENTION_TRIGGERED":  15,
		"RECOVERY_ATTEMPTED":      16,
		"STATE_SNAPSHOT_CAPTURED": 17,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_routeiq_v1_telemetry_events_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_routeiq_v1_telemetry_events_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_routeiq_v1_telemetry_events_proto_rawDescGZIP(), []int{0}
}

// VersionLineage carries the full software bill-of-materials for a run.
type VersionLineage struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AgentVersion        string                 `protobuf:"bytes,1,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	ModelName           string                 `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	ModelVersion        string                 `protobuf:"bytes,3,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	PromptVersion       string                 `protobuf:"bytes,4,opt,name=prompt_version,json=promptVersion,proto3" json:"prompt_version,omitempty"`
	ToolchainVersion    string                 `protobuf:"bytes,5,opt,name=toolchain_version,json=toolchainVersion,proto3" json:"toolchain_version,omitempty"`
	MemoryVersion       string                 `protobuf:"bytes,6,opt,name=memory_version,json=memoryVersion,proto3" json:"memory_version,omitempty"`
	RetrievalVersion    string                 `protobuf:"bytes,7,opt,name=retrieval_version,json=retrievalVersion,proto3" json:"retrieval_version,omitempty"`
	PolicyBundleVersion string                 `protobuf:"bytes,8,opt,name=policy_bundle_version,json=policyBundleVersion,proto3" json:"policy_bundle_version,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *VersionLineage) Reset() {
	*x = VersionLineage{}
	mi := &file_routeiq_v1_telemetry_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionLineage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionLineage) ProtoMessage() {}

func (x *VersionLineage) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_telemetry_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionLineage.ProtoReflect.Descriptor instead.
func (*VersionLineage) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_telemetry_events_proto_rawDescGZIP(), []int{0}
}

func (x *VersionLineage) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *VersionLineage) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *VersionLineage) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

func (x *VersionLineage) GetPromptVersion() string {
	if x != nil {
		return x.PromptVersion
	}
	return ""
}

func (x *VersionLineage) GetToolchainVersion() string {
	if x != nil {
		return x.ToolchainVersion
	}
	return ""
}

func (x *VersionLineage) GetMemoryVersion() string {
	if x != nil {
		return x.MemoryVersion
	}
	return ""
}

func (x *VersionLineage) GetRetrievalVersion() string {
	if x != nil {
		return x.RetrievalVersion
	}
	return ""
}

func (x *VersionLineage) GetPolicyBundleVersion() string {
	if x != nil {
		return x.PolicyBundleVersion
	}
	return ""
}

// AgentEvent is the canonical envelope for every event emitted by an agent.
// Maps to an OTel span with routeiq.* attributes (see conventions/telemetry.yaml).
type AgentEvent struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	TraceId      []byte                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SpanId       []byte                 `protobuf:"bytes,2,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	ParentSpanId []byte                 `protobuf:"bytes,3,opt,name=parent_span_id,json=parentSpanId,proto3" json:"parent_span_id,omitempty"`
	Timestamp    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	EventType    EventType              `protobuf:"varint,5,opt,name=event_type,json=eventType,proto3,enum=routeiq.v1.telemetry.EventType" json:"event_type,omitempty"`
	TenantId     string                 `protobuf:"bytes,6,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Environment  string                 `protobuf:"bytes,7,opt,name=environment,proto3" json:"environment,omitempty"`
	TaskId       string                 `protobuf:"bytes,8,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	RunId        string                 `protobuf:"bytes,9,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	StepId       string                 `protobuf:"bytes,10,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	AgentId      string                 `protobuf:"bytes,11,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentRole    string                 `protobuf:"bytes,12,opt,name=agent_role,json=agentRole,proto3" json:"agent_role,omitempty"`
	WorkflowId   string                 `protobuf:"bytes,13,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	Versions     *VersionLineage        `protobuf:"bytes,14,opt,name=versions,proto3" json:"versions,omitempty"`
	AutonomyMode AutonomyMode           `protobuf:"varint,15,opt,name=autonomy_mode,json=autonomyMode,proto3,enum=routeiq.v1.telemetry.AutonomyMode" json:"autonomy_mode,omitempty"`
	RiskTier     RiskTier               `protobuf:"varint,16,opt,name=risk_tier,json=riskTier,proto3,enum=routeiq.v1.telemetry.RiskTier" json:"risk_tier,omitempty"`
	SessionId    string                 `protobuf:"bytes,17,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentEvent_Task
	//	*AgentEvent_Step
	//	*AgentEvent_Decision
	//	*AgentEvent_ToolCall
	//	*AgentEvent_Retrieval
	//	*AgentEvent_Memory
	//	*AgentEvent_Handoff
	//	*AgentEvent_Policy
	//	*AgentEvent_Intervention
	//	*AgentEvent_Recovery
	//	*AgentEvent_StateSnapshot
	Payload       isAgentEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentEvent) Reset() {
	*x = AgentEvent{}
	mi := &file_routeiq_v1_telemetry_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentEvent) ProtoMessage() {}

func (x *AgentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_telemetry_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentEvent.ProtoReflect.Descriptor instead.
func (*AgentEvent) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_telemetry_events_proto_rawDescGZIP(), []int{1}
}

func (x *AgentEvent) GetTraceId() []byte {
	if x != nil {
		return x.TraceId
	}
	return nil
}

func (x *AgentEvent) GetSpanId() []byte {
	if x != nil {
		return x.SpanId
	}
	return nil
}

func (x *AgentEvent) GetParentSpanId() []byte {
	if x != nil {
		return x.ParentSpanId
	}
	return nil
}

func (x *AgentEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *AgentEvent) GetEventType() EventType {
	if x != nil {
		return x.EventType
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *AgentEvent) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *AgentEvent) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *AgentEvent) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *AgentEvent) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *AgentEvent) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *AgentEvent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentEvent) GetAgentRole() string {
	if x != nil {
		return x.AgentRole
	}
	return ""
}

func (x *AgentEvent) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *AgentEvent) GetVersions() *VersionLineage {
	if x != nil {
		return x.Versions
	}
	return nil
}

func (x *AgentEvent) GetAutonomyMode() AutonomyMode {
	if x != nil {
		return x.AutonomyMode
	}
	return AutonomyMode_AUTONOMY_MODE_UNSPECIFIED
}

func (x *AgentEvent) GetRiskTier() RiskTier {
	if x != nil {
		return x.RiskTier
	}
	return RiskTier_RISK_TIER_UNSPECIFIED
}

func (x *AgentEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AgentEvent) GetPayload() isAgentEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentEvent) GetTask() *TaskEvent {
	if x != nil {
		if x, ok := x.Payload.(*AgentEvent_Task); ok {
			return x.Task
		}
	}
	return nil
}

func (x *AgentEvent) GetStep() *StepEvent {
	if x != nil {
		if x, ok := x.Payload.(*AgentEvent_Step); ok {
			return x.Step
		}
	}
	return nil
}

func (x *AgentEvent) GetDecision() *DecisionEvent {
	if x != nil {
		if x, ok := x.Payload.(*AgentEvent_Decision); ok {
			return x.Decision
		}
	}
	return nil
}

func (x *AgentEvent) GetToolCall() *ToolCallEvent {
	if x != nil {
		if x, ok := x.Payload.(*AgentEvent_ToolCall); ok {
			return x.ToolCall
		}
	}
	return nil
}

func (x *AgentEvent) GetRetrieval() *RetrievalEvent {
	if x != nil {
		if x, ok := x.Payload.(*AgentEvent_Retrieval); ok {
			return x.Retrieval
		}
	}
	return nil
}

func (x *AgentEvent) GetMemory() *MemoryEvent {
	if x != nil {
		if x, ok := x.Payload.(*AgentEvent_Memory); ok {
			return x.Memory
		}
	}
	return nil
}

func (x *AgentEvent) GetHandoff() *HandoffEvent {
	if x != nil {
		if x, ok := x.Payload.(*AgentEvent_Handoff); ok {
			return x.Handoff
		}
	}
	return nil
}

func (x *AgentEvent) GetPolicy() *PolicyEvent {
	if x != nil {
		if x, ok := x.Payload.(*AgentEvent_Policy); ok {
			return x.Policy
		}
	}
	return nil
}

func (x *AgentEvent) GetIntervention() *InterventionEvent {
	if x != nil {
		if x, ok := x.Payload.(*AgentEvent_Intervention); ok {
			return x.Intervention
		}
	}
	return nil
}

func (x *AgentEvent) GetRecovery() *RecoveryEvent {
	if x != nil {
		if x, ok := x.Payload.(*AgentEvent_Recovery); ok {
			return x.Recovery
		}
	}
	return nil
}

func (x *AgentEvent) GetStateSnapshot() *StateSnapshotEvent {
	if x != nil {
		if x, ok := x.Payload.(*AgentEvent_StateSnapshot); ok {
			return x.StateSnapshot
		}
	}
	return nil
}

type isAgentEvent_Payload interface {
	isAgentEvent_Payload()
}

type AgentEvent_Task struct {
	Task *TaskEvent `protobuf:"bytes,100,opt,name=task,proto3,oneof"`
}

type AgentEvent_Step struct {
	Step *StepEvent `protobuf:"bytes,101,opt,name=step,proto3,oneof"`
}

type AgentEvent_Decision struct {
	Decision *DecisionEvent `protobuf:"bytes,102,opt,name=decision,proto3,oneof"`
}

type AgentEvent_ToolCall struct {
	ToolCall *ToolCallEvent `protobuf:"bytes,103,opt,name=tool_call,json=toolCall,proto3,oneof"`
}

type AgentEvent_Retrieval struct {
	Retrieval *RetrievalEvent `protobuf:"bytes,104,opt,name=retrieval,proto3,oneof"`
}

type AgentEvent_Memory struct {
	Memory *MemoryEvent `protobuf:"bytes,105,opt,name=memory,proto3,oneof"`
}

type AgentEvent_Handoff struct {
	Handoff *HandoffEvent `protobuf:"bytes,106,opt,name=handoff,proto3,oneof"`
}

type AgentEvent_Policy struct {
	Policy *PolicyEvent `protobuf:"bytes,107,opt,name=policy,proto3,oneof"`
}

type AgentEvent_Intervention struct {
	Intervention *InterventionEvent `protobuf:"bytes,108,opt,name=intervention,proto3,oneof"`
}

type AgentEvent_Recovery struct {
	Recovery *RecoveryEvent `protobuf:"bytes,109,opt,name=recovery,proto3,oneof"`
}

type AgentEvent_StateSnapshot struct {
	StateSnapshot *StateSnapshotEvent `protobuf:"bytes,110,opt,name=state_snapshot,json=stateSnapshot,proto3,oneof"`
}

func (*AgentEvent_Task) isAgentEvent_Payload() {}

func (*AgentEvent_Step) isAgentEvent_Payload() {}

func (*AgentEvent_Decision) isAgentEvent_Payload() {}

func (*AgentEvent_ToolCall) isAgentEvent_Payload() {}

func (*AgentEvent_Retrieval) isAgentEvent_Payload() {}

func (*AgentEvent_Memory) isAgentEvent_Payload() {}

func (*AgentEvent_Handoff) isAgentEvent_Payload() {}

func (*AgentEvent_Policy) isAgentEvent_Payload() {}

func (*AgentEvent_Intervention) isAgentEvent_Payload() {}

func (*AgentEvent_Recovery) isAgentEvent_Payload() {}

func (*AgentEvent_StateSnapshot) isAgentEvent_Payload() {}

// TaskEvent carries the outcome of a complete agent task.
type TaskEvent struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	InputIntent        string                 `protobuf:"bytes,1,opt,name=input_intent,json=inputIntent,proto3" json:"input_intent,omitempty"`
	NormalizedTaskType string                 `protobuf:"bytes,2,opt,name=normalized_task_type,json=normalizedTaskType,proto3" json:"normalized_task_type,omitempty"`
	ExpectedOutcome    string                 `protobuf:"bytes,3,opt,name=expected_outcome,json=expectedOutcome,proto3" json:"expected_outcome,omitempty"`
	ActualOutcome      string                 `protobuf:"bytes,4,opt,name=actual_outcome,json=actualOutcome,proto3" json:"actual_outcome,omitempty"`
	CompletionStatus   CompletionStatus       `protobuf:"varint,5,opt,name=completion_status,json=completionStatus,proto3,enum=routeiq.v1.telemetry.CompletionStatus" json:"completion_status,omitempty"`
	FailureCategory    FailureCategory        `protobuf:"varint,6,opt,name=failure_category,json=failureCategory,proto3,enum=routeiq.v1.telemetry.FailureCategory" json:"failure_category,omitempty"`
	TotalCostUsd       float64                `protobuf:"fixed64,7,opt,name=total_cost_usd,json=totalCostUsd,proto3" json:"total_cost_usd,omitempty"`
	TotalTokens        int64                  `protobuf:"varint,8,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	HumanEscalated     bool                   `protobuf:"varint,9,opt,name=human_escalated,json=humanEscalated,proto3" json:"human_escalated,omitempty"`
	RolledBack         bool                   `protobuf:"varint,10,opt,name=rolled_back,json=rolledBack,proto3" json:"rolled_back,omitempty"`
	Cohort             string                 `protobuf:"bytes,11,opt,name=cohort,proto3" json:"cohort,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TaskEvent) Reset() {
	*x = TaskEvent{}
	mi := &file_routeiq_v1_telemetry_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskEvent) ProtoMessage() {}

func (x *TaskEvent) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_telemetry_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskEvent.ProtoReflect.Descriptor instead.
func (*TaskEvent) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_telemetry_events_proto_rawDescGZIP(), []int{2}
}

func (x *TaskEvent) GetInputIntent() string {
	if x != nil {
		return x.InputIntent
	}
	return ""
}

func (x *TaskEvent) GetNormalizedTaskType() string {
	if x != nil {
		return x.NormalizedTaskType
	}
	return ""
}

func (x *TaskEvent) GetExpectedOutcome() string {
	if x != nil {
		return x.ExpectedOutcome
	}
	return ""
}

func (x *TaskEvent) GetActualOutcome() string {
	if x != nil {
		return x.ActualOutcome
	}
	return ""
}

func (x *TaskEvent) GetCompletionStatus() CompletionStatus {
	if x != nil {
		return x.CompletionStatus
	}
	return CompletionStatus_COMPLETION_STATUS_UNSPECIFIED
}

func (x *TaskEvent) GetFailureCategory() FailureCategory {
	if x != nil {
		return x.FailureCategory
	}
	return FailureCategory_FAILURE_CATEGORY_UNSPECIFIED
}

func (x *TaskEvent) GetTotalCostUsd() float64 {
	if x != nil {
		return x.TotalCostUsd
	}
	return 0
}

func (x *TaskEvent) GetTotalTokens() int64 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *TaskEvent) GetHumanEscalated() bool {
	if x != nil {
		return x.HumanEscalated
	}
	return false
}

func (x *TaskEvent) GetRolledBack() bool {
	if x != nil {
		return x.RolledBack
	}
	return false
}

func (x *TaskEvent) GetCohort() string {
	if x != nil {
		return x.Cohort
	}
	return ""
}

// ToolCallEvent records a single tool invocation within a step.
type ToolCallEvent struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ToolName           string                 `protobuf:"bytes,1,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	ToolVersion        string                 `protobuf:"bytes,2,opt,name=tool_version,json=toolVersion,proto3" json:"tool_version,omitempty"`
	ArgumentsHash      string                 `protobuf:"bytes,3,opt,name=arguments_hash,json=argumentsHash,proto3" json:"arguments_hash,omitempty"`
	ArgumentsSummary   string                 `protobuf:"bytes,4,opt,name=arguments_summary,json=argumentsSummary,proto3" json:"arguments_summary,omitempty"`
	PermissionLevel    PermissionLevel        `protobuf:"varint,5,opt,name=permission_level,json=permissionLevel,proto3,enum=routeiq.v1.telemetry.PermissionLevel" json:"permission_level,omitempty"`
	StartTime          *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime            *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	LatencyMs          float64                `protobuf:"fixed64,8,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	ResultStatus       ToolResultStatus       `protobuf:"varint,9,opt,name=result_status,json=resultStatus,proto3,enum=routeiq.v1.telemetry.ToolResultStatus" json:"result_status,omitempty"`
	ErrorCode          string                 `protobuf:"bytes,10,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ResultSummary      string                 `protobuf:"bytes,11,opt,name=result_summary,json=resultSummary,proto3" json:"result_summary,omitempty"`
	ResultQualityFlags []string               `protobuf:"bytes,12,rep,name=result_quality_flags,json=resultQualityFlags,proto3" json:"result_quality_flags,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ToolCallEvent) Reset() {
	*x = ToolCallEvent{}
	mi := &file_routeiq_v1_telemetry_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallEvent) ProtoMessage() {}

func (x *ToolCallEvent) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_telemetry_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallEvent.ProtoReflect.Descriptor instead.
func (*ToolCallEvent) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_telemetry_events_proto_rawDescGZIP(), []int{3}
}

func (x *ToolCallEvent) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolCallEvent) GetToolVersion() string {
	if x != nil {
		return x.ToolVersion
	}
	return ""
}

func (x *ToolCallEvent) GetArgumentsHash() string {
	if x != nil {
		return x.ArgumentsHash
	}
	return ""
}

func (x *ToolCallEvent) GetArgumentsSummary() string {
	if x != nil {
		return x.ArgumentsSummary
	}
	return ""
}

func (x *ToolCallEvent) GetPermissionLevel() PermissionLevel {
	if x != nil {
		return x.PermissionLevel
	}
	return PermissionLevel_PERMISSION_LEVEL_UNSPECIFIED
}

func (x *ToolCallEvent) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *ToolCallEvent) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *ToolCallEvent) GetLatencyMs() float64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *ToolCallEvent) GetResultStatus() ToolResultStatus {
	if x != nil {
		return x.ResultStatus
	}
	return ToolResultStatus_TOOL_RESULT_STATUS_UNSPECIFIED
}

func (x *ToolCallEvent) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *ToolCallEvent) GetResultSummary() string {
	if x != nil {
		return x.ResultSummary
	}
	return ""
}

func (x *ToolCallEvent) GetResultQualityFlags() []string {
	if x != nil {
		return x.ResultQualityFlags
	}
	return nil
}

// StepEvent captures the outcome of a single reasoning step within a task run.
type StepEvent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SelectedAction   string                 `protobuf:"bytes,1,opt,name=selected_action,json=selectedAction,proto3" json:"selected_action,omitempty"`
	ActionRationale  string                 `protobuf:"bytes,2,opt,name=action_rationale,json=actionRationale,proto3" json:"action_rationale,omitempty"`
	CompletionStatus CompletionStatus       `protobuf:"varint,3,opt,name=completion_status,json=completionStatus,proto3,enum=routeiq.v1.telemetry.CompletionStatus" json:"completion_status,omitempty"`
	FailureCategory  FailureCategory        `protobuf:"varint,4,opt,name=failure_category,json=failureCategory,proto3,enum=routeiq.v1.telemetry.FailureCategory" json:"failure_category,omitempty"`
	StepIndex        int32                  `protobuf:"varint,5,opt,name=step_index,json=stepIndex,proto3" json:"step_index,omitempty"`
	RetryCount       int32                  `protobuf:"varint,6,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StepEvent) Reset() {
	*x = StepEvent{}
	mi := &file_routeiq_v1_telemetry_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepEvent) ProtoMessage() {}

func (x *StepEvent) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_telemetry_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepEvent.ProtoReflect.Descriptor instead.
func (*StepEvent) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_telemetry_events_proto_rawDescGZIP(), []int{4}
}

func (x *StepEvent) GetSelectedAction() string {
	if x != nil {
		return x.SelectedAction
	}
	return ""
}

func (x *StepEvent) GetActionRationale() string {
	if x != nil {
		return x.ActionRationale
	}
	return ""
}

func (x *StepEvent) GetCompletionStatus() CompletionStatus {
	if x != nil {
		return x.CompletionStatus
	}
	return CompletionStatus_COMPLETION_STATUS_UNSPECIFIED
}

func (x *StepEvent) GetFailureCategory() FailureCategory {
	if x != nil {
		return x.FailureCategory
	}
	return FailureCategory_FAILURE_CATEGORY_UNSPECIFIED
}

func (x *StepEvent) GetStepIndex() int32 {
	if x != nil {
		return x.StepIndex
	}
	return 0
}

func (x *StepEvent) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

// DecisionEvent records a branching decision point — which path or tool the agent chose.
type DecisionEvent struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DecisionType      string                 `protobuf:"bytes,1,opt,name=decision_type,json=decisionType,proto3" json:"decision_type,omitempty"`                // "tool_selection" | "path_choice" | "escalation_check"
	OptionsConsidered string                 `protobuf:"bytes,2,opt,name=options_considered,json=optionsConsidered,proto3" json:"options_considered,omitempty"` // JSON or natural-language summary of alternatives
	ChosenOption      string                 `protobuf:"bytes,3,opt,name=chosen_option,json=chosenOption,proto3" json:"chosen_option,omitempty"`
	Rationale         string                 `protobuf:"bytes,4,opt,name=rationale,proto3" json:"rationale,omitempty"`
	Confidence        float64                `protobuf:"fixed64,5,opt,name=confidence,proto3" json:"confidence,omitempty"` // 0.0–1.0 model-reported confidence
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DecisionEvent) Reset() {
	*x = DecisionEvent{}
	mi := &file_routeiq_v1_telemetry_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecisionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionEvent) ProtoMessage() {}

func (x *DecisionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_telemetry_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionEvent.ProtoReflect.Descriptor instead.
func (*DecisionEvent) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_telemetry_events_proto_rawDescGZIP(), []int{5}
}

func (x *DecisionEvent) GetDecisionType() string {
	if x != nil {
		return x.DecisionType
	}
	return ""
}

func (x *DecisionEvent) GetOptionsConsidered() string {
	if x != nil {
		return x.OptionsConsidered
	}
	return ""
}

func (x *DecisionEvent) GetChosenOption() string {
	if x != nil {
		return x.ChosenOption
	}
	return ""
}

func (x *DecisionEvent) GetRationale() string {
	if x != nil {
		return x.Rationale
	}
	return ""
}

func (x *DecisionEvent) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

// RetrievalEvent records a RAG, search, or knowledge-base lookup.
type RetrievalEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RetrievalType string                 `protobuf:"bytes,1,opt,name=retrieval_type,json=retrievalType,proto3" json:"retrieval_type,omitempty"` // "vector" | "keyword" | "hybrid" | "graph"
	QuerySummary  string                 `protobuf:"bytes,2,opt,name=query_summary,json=querySummary,proto3" json:"query_summary,omitempty"`    // sanitized query — PII redacted by collector
	ResultsCount  int32                  `protobuf:"varint,3,opt,name=results_count,json=resultsCount,proto3" json:"results_count,omitempty"`
	TopScore      float64                `protobuf:"fixed64,4,opt,name=top_score,json=topScore,proto3" json:"top_score,omitempty"`
	CacheHit      bool                   `protobuf:"varint,5,opt,name=cache_hit,json=cacheHit,proto3" json:"cache_hit,omitempty"` // true if result was served from cache
	LatencyMs     float64                `protobuf:"fixed64,6,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrievalEvent) Reset() {
	*x = RetrievalEvent{}
	mi := &file_routeiq_v1_telemetry_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrievalEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrievalEvent) ProtoMessage() {}

func (x *RetrievalEvent) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_telemetry_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrievalEvent.ProtoReflect.Descriptor instead.
func (*RetrievalEvent) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_telemetry_events_proto_rawDescGZIP(), []int{6}
}

func (x *RetrievalEvent) GetRetrievalType() string {
	if x != nil {
		return x.RetrievalType
	}
	return ""
}

func (x *RetrievalEvent) GetQuerySummary() string {
	if x != nil {
		return x.QuerySummary
	}
	return ""
}

func (x *RetrievalEvent) GetResultsCount() int32 {
	if x != nil {
		return x.ResultsCount
	}
	return 0
}

func (x *RetrievalEvent) GetTopScore() float64 {
	if x != nil {
		return x.TopScore
	}
	return 0
}

func (x *RetrievalEvent) GetCacheHit() bool {
	if x != nil {
		return x.CacheHit
	}
	return false
}

func (x *RetrievalEvent) GetLatencyMs() float64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

// MemoryEvent records a read or write to the agent's memory store.
type MemoryEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MemoryType      string                 `protobuf:"bytes,1,opt,name=memory_type,json=memoryType,proto3" json:"memory_type,omitempty"` // "short_term" | "long_term" | "episodic" | "semantic"
	Operation       string                 `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`                     // "read" | "write" | "delete" | "search"
	KeySummary      string                 `protobuf:"bytes,3,opt,name=key_summary,json=keySummary,proto3" json:"key_summary,omitempty"` // sanitized key/description — PII redacted by collector
	EntriesAffected int32                  `protobuf:"varint,4,opt,name=entries_affected,json=entriesAffected,proto3" json:"entries_affected,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MemoryEvent) Reset() {
	*x = MemoryEvent{}
	mi := &file_routeiq_v1_telemetry_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryEvent) ProtoMessage() {}

func (x *MemoryEvent) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_telemetry_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryEvent.ProtoReflect.Descriptor instead.
func (*MemoryEvent) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_telemetry_events_proto_rawDescGZIP(), []int{7}
}

func (x *MemoryEvent) GetMemoryType() string {
	if x != nil {
		return x.MemoryType
	}
	return ""
}

func (x *MemoryEvent) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *MemoryEvent) GetKeySummary() string {
	if x != nil {
		return x.KeySummary
	}
	return ""
}

func (x *MemoryEvent) GetEntriesAffected() int32 {
	if x != nil {
		return x.EntriesAffected
	}
	return 0
}

// HandoffEvent records an agent-to-agent delegation of a task or sub-task.
type HandoffEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FromAgentId    string                 `protobuf:"bytes,1,opt,name=from_agent_id,json=fromAgentId,proto3" json:"from_agent_id,omitempty"`
	ToAgentId      string                 `protobuf:"bytes,2,opt,name=to_agent_id,json=toAgentId,proto3" json:"to_agent_id,omitempty"`
	HandoffReason  string                 `protobuf:"bytes,3,opt,name=handoff_reason,json=handoffReason,proto3" json:"handoff_reason,omitempty"`
	Status         CompletionStatus       `protobuf:"varint,4,opt,name=status,proto3,enum=routeiq.v1.telemetry.CompletionStatus" json:"status,omitempty"` // COMPLETED = handoff accepted; FAILURE = rejected
	ContextSummary string                 `protobuf:"bytes,5,opt,name=context_summary,json=contextSummary,proto3" json:"context_summary,omitempty"`       // sanitized summary of context passed to receiving agent
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HandoffEvent) Reset() {
	*x = HandoffEvent{}
	mi := &file_routeiq_v1_telemetry_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandoffEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandoffEvent) ProtoMessage() {}

func (x *HandoffEvent) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_telemetry_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandoffEvent.ProtoReflect.Descriptor instead.
func (*HandoffEvent) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_telemetry_events_proto_rawDescGZIP(), []int{8}
}

func (x *HandoffEvent) GetFromAgentId() string {
	if x != nil {
		return x.FromAgentId
	}
	return ""
}

func (x *HandoffEvent) GetToAgentId() string {
	if x != nil {
		return x.ToAgentId
	}
	return ""
}

func (x *HandoffEvent) GetHandoffReason() string {
	if x != nil {
		return x.HandoffReason
	}
	return ""
}

func (x *HandoffEvent) GetStatus() CompletionStatus {
	if x != nil {
		return x.Status
	}
	return CompletionStatus_COMPLETION_STATUS_UNSPECIFIED
}

func (x *HandoffEvent) GetContextSummary() string {
	if x != nil {
		return x.ContextSummary
	}
	return ""
}

// PolicyEvent records the evaluation of a policy bundle against a proposed action.
type PolicyEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PolicyId        string                 `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	BundleVersion   string                 `protobuf:"bytes,2,opt,name=bundle_version,json=bundleVersion,proto3" json:"bundle_version,omitempty"`
	ActionEvaluated string                 `protobuf:"bytes,3,opt,name=action_evaluated,json=actionEvaluated,proto3" json:"action_evaluated,omitempty"`
	Verdict         string                 `protobuf:"bytes,4,opt,name=verdict,proto3" json:"verdict,omitempty"`                                     // "allow" | "block" | "require_approval"
	RulesTriggered  []string               `protobuf:"bytes,5,rep,name=rules_triggered,json=rulesTriggered,proto3" json:"rules_triggered,omitempty"` // IDs of individual rules that fired
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PolicyEvent) Reset() {
	*x = PolicyEvent{}
	mi := &file_routeiq_v1_telemetry_events_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyEvent) ProtoMessage() {}

func (x *PolicyEvent) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_telemetry_events_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyEvent.ProtoReflect.Descriptor instead.
func (*PolicyEvent) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_telemetry_events_proto_rawDescGZIP(), []int{9}
}

func (x *PolicyEvent) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *PolicyEvent) GetBundleVersion() string {
	if x != nil {
		return x.BundleVersion
	}
	return ""
}

func (x *PolicyEvent) GetActionEvaluated() string {
	if x != nil {
		return x.ActionEvaluated
	}
	return ""
}

func (x *PolicyEvent) GetVerdict() string {
	if x != nil {
		return x.Verdict
	}
	return ""
}

func (x *PolicyEvent) GetRulesTriggered() []string {
	if x != nil {
		return x.RulesTriggered
	}
	return nil
}

// InterventionEvent records a system or human intervention that interrupted normal agent flow.
type InterventionEvent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	InterventionType string                 `protobuf:"bytes,1,opt,name=intervention_type,json=interventionType,proto3" json:"intervention_type,omitempty"` // "circuit_break" | "rollback" | "escalate_human" | "model_swap" | "autonomy_downgrade"
	TriggerReason    string                 `protobuf:"bytes,2,opt,name=trigger_reason,json=triggerReason,proto3" json:"trigger_reason,omitempty"`
	TriggerMetricId  string                 `protobuf:"bytes,3,opt,name=trigger_metric_id,json=triggerMetricId,proto3" json:"trigger_metric_id,omitempty"` // metric that breached threshold, if system-triggered
	Automated        bool                   `protobuf:"varint,4,opt,name=automated,proto3" json:"automated,omitempty"`                                     // true = system-triggered; false = human-triggered
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *InterventionEvent) Reset() {
	*x = InterventionEvent{}
	mi := &file_routeiq_v1_telemetry_events_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterventionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterventionEvent) ProtoMessage() {}

func (x *InterventionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_telemetry_events_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterventionEvent.ProtoReflect.Descriptor instead.
func (*InterventionEvent) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_telemetry_events_proto_rawDescGZIP(), []int{10}
}

func (x *InterventionEvent) GetInterventionType() string {
	if x != nil {
		return x.InterventionType
	}
	return ""
}

func (x *InterventionEvent) GetTriggerReason() string {
	if x != nil {
		return x.TriggerReason
	}
	return ""
}

func (x *InterventionEvent) GetTriggerMetricId() string {
	if x != nil {
		return x.TriggerMetricId
	}
	return ""
}

func (x *InterventionEvent) GetAutomated() bool {
	if x != nil {
		return x.Automated
	}
	return false
}

// RecoveryEvent records a recovery attempt following a failure or intervention.
type RecoveryEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecoveryType  string                 `protobuf:"bytes,1,opt,name=recovery_type,json=recoveryType,proto3" json:"recovery_type,omitempty"` // "retry" | "fallback" | "rollback" | "restart"
	FromError     string                 `protobuf:"bytes,2,opt,name=from_error,json=fromError,proto3" json:"from_error,omitempty"`          // error code or short description of what failed
	Succeeded     bool                   `protobuf:"varint,3,opt,name=succeeded,proto3" json:"succeeded,omitempty"`
	AttemptNumber int32                  `protobuf:"varint,4,opt,name=attempt_number,json=attemptNumber,proto3" json:"attempt_number,omitempty"` // 1-indexed; >1 means this is a retry
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecoveryEvent) Reset() {
	*x = RecoveryEvent{}
	mi := &file_routeiq_v1_telemetry_events_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecoveryEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoveryEvent) ProtoMessage() {}

func (x *RecoveryEvent) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_telemetry_events_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoveryEvent.ProtoReflect.Descriptor instead.
func (*RecoveryEvent) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_telemetry_events_proto_rawDescGZIP(), []int{11}
}

func (x *RecoveryEvent) GetRecoveryType() string {
	if x != nil {
		return x.RecoveryType
	}
	return ""
}

func (x *RecoveryEvent) GetFromError() string {
	if x != nil {
		return x.FromError
	}
	return ""
}

func (x *RecoveryEvent) GetSucceeded() bool {
	if x != nil {
		return x.Succeeded
	}
	return false
}

func (x *RecoveryEvent) GetAttemptNumber() int32 {
	if x != nil {
		return x.AttemptNumber
	}
	return 0
}

// StateSnapshotEvent records a point-in-time capture of agent working state.
type StateSnapshotEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SnapshotType   string                 `protobuf:"bytes,1,opt,name=snapshot_type,json=snapshotType,proto3" json:"snapshot_type,omitempty"` // "checkpoint" | "pre_tool" | "post_tool" | "on_error"
	StateSizeBytes int64                  `protobuf:"varint,2,opt,name=state_size_bytes,json=stateSizeBytes,proto3" json:"state_size_bytes,omitempty"`
	SnapshotId     string                 `protobuf:"bytes,3,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StateSnapshotEvent) Reset() {
	*x = StateSnapshotEvent{}
	mi := &file_routeiq_v1_telemetry_events_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateSnapshotEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateSnapshotEvent) ProtoMessage() {}

func (x *StateSnapshotEvent) ProtoReflect() protoreflect.Message {
	mi := &file_routeiq_v1_telemetry_events_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateSnapshotEvent.ProtoReflect.Descriptor instead.
func (*StateSnapshotEvent) Descriptor() ([]byte, []int) {
	return file_routeiq_v1_telemetry_events_proto_rawDescGZIP(), []int{12}
}

func (x *StateSnapshotEvent) GetSnapshotType() string {
	if x != nil {
		return x.SnapshotType
	}
	return ""
}

func (x *StateSnapshotEvent) GetStateSizeBytes() int64 {
	if x != nil {
		return x.StateSizeBytes
	}
	return 0
}

func (x *StateSnapshotEvent) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

var File_routeiq_v1_telemetry_events_proto protoreflect.FileDescriptor

const file_routeiq_v1_telemetry_events_proto_rawDesc = "" +
	"\n" +
	"!routeiq/v1/telemetry/events.proto\x12\x14routeiq.v1.telemetry\x1a\x1fgoogle/protobuf/timestamp.proto\x1a#routeiq/v1/telemetry/entities.proto\"\xd5\x02\n" +
	"\x0eVersionLineage\x12#\n" +
	"\ragent_version\x18\x01 \x01(\tR\fagentVersion\x12\x1d\n" +
	"\n" +
	"model_name\x18\x02 \x01(\tR\tmodelName\x12#\n" +
	"\rmodel_version\x18\x03 \x01(\tR\fmodelVersion\x12%\n" +
	"\x0eprompt_version\x18\x04 \x01(\tR\rpromptVersion\x12+\n" +
	"\x11toolchain_version\x18\x05 \x01(\tR\x10toolchainVersion\x12%\n" +
	"\x0ememory_version\x18\x06 \x01(\tR\rmemoryVersion\x12+\n" +
	"\x11retrieval_version\x18\a \x01(\tR\x10retrievalVersion\x122\n" +
	"\x15policy_bundle_version\x18\b \x01(\tR\x13policyBundleVersion\"\x8f\v\n" +
	"\n" +
	"AgentEvent\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\fR\atraceId\x12\x17\n" +
	"\aspan_id\x18\x02 \x01(\fR\x06spanId\x12$\n" +
	"\x0eparent_span_id\x18\x03 \x01(\fR\fparentSpanId\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12>\n" +
	"\n" +
	"event_type\x18\x05 \x01(\x0e2\x1f.routeiq.v1.telemetry.EventTypeR\teventType\x12\x1b\n" +
	"\ttenant_id\x18\x06 \x01(\tR\btenantId\x12 \n" +
	"\venvironment\x18\a \x01(\tR\venvironment\x12\x17\n" +
	"\atask_id\x18\b \x01(\tR\x06taskId\x12\x15\n" +
	"\x06run_id\x18\t \x01(\tR\x05runId\x12\x17\n" +
	"\astep_id\x18\n" +
	" \x01(\tR\x06stepId\x12\x19\n" +
	"\bagent_id\x18\v \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"agent_role\x18\f \x01(\tR\tagentRole\x12\x1f\n" +
	"\vworkflow_id\x18\r \x01(\tR\n" +
	"workflowId\x12@\n" +
	"\bversions\x18\x0e \x01(\v2$.routeiq.v1.telemetry.VersionLineageR\bversions\x12G\n" +
	"\rautonomy_mode\x18\x0f \x01(\x0e2\".routeiq.v1.telemetry.AutonomyModeR\fautonomyMode\x12;\n" +
	"\trisk_tier\x18\x10 \x01(\x0e2\x1e.routeiq.v1.telemetry.RiskTierR\briskTier\x12\x1d\n" +
	"\n" +
	"session_id\x18\x11 \x01(\tR\tsessionId\x125\n" +
	"\x04task\x18d \x01(\v2\x1f.routeiq.v1.telemetry.TaskEventH\x00R\x04task\x125\n" +
	"\x04step\x18e \x01(\v2\x1f.routeiq.v1.telemetry.StepEventH\x00R\x04step\x12A\n" +
	"\bdecision\x18f \x01(\v2#.routeiq.v1.telemetry.DecisionEventH\x00R\bdecision\x12B\n" +
	"\ttool_call\x18g \x01(\v2#.routeiq.v1.telemetry.ToolCallEventH\x00R\btoolCall\x12D\n" +
	"\tretrieval\x18h \x01(\v2$.routeiq.v1.telemetry.RetrievalEventH\x00R\tretrieval\x12;\n" +
	"\x06memory\x18i \x01(\v2!.routeiq.v1.telemetry.MemoryEventH\x00R\x06memory\x12>\n" +
	"\ahandoff\x18j \x01(\v2\".routeiq.v1.telemetry.HandoffEventH\x00R\ahandoff\x12;\n" +
	"\x06policy\x18k \x01(\v2!.routeiq.v1.telemetry.PolicyEventH\x00R\x06policy\x12M\n" +
	"\fintervention\x18l \x01(\v2'.routeiq.v1.telemetry.InterventionEventH\x00R\fintervention\x12A\n" +
	"\brecovery\x18m \x01(\v2#.routeiq.v1.telemetry.RecoveryEventH\x00R\brecovery\x12Q\n" +
	"\x0estate_snapshot\x18n \x01(\v2(.routeiq.v1.telemetry.StateSnapshotEventH\x00R\rstateSnapshotB\t\n" +
	"\apayload\"\x84\x04\n" +
	"\tTaskEvent\x12!\n" +
	"\finput_intent\x18\x01 \x01(\tR\vinputIntent\x120\n" +
	"\x14normalized_task_type\x18\x02 \x01(\tR\x12normalizedTaskType\x12)\n" +
	"\x10expected_outcome\x18\x03 \x01(\tR\x0fexpectedOutcome\x12%\n" +
	"\x0eactual_outcome\x18\x04 \x01(\tR\ractualOutcome\x12S\n" +
	"\x11completion_status\x18\x05 \x01(\x0e2&.routeiq.v1.telemetry.CompletionStatusR\x10completionStatus\x12P\n" +
	"\x10failure_category\x18\x06 \x01(\x0e2%.routeiq.v1.telemetry.FailureCategoryR\x0ffailureCategory\x12$\n" +
	"\x0etotal_cost_usd\x18\a \x01(\x01R\ftotalCostUsd\x12!\n" +
	"\ftotal_tokens\x18\b \x01(\x03R\vtotalTokens\x12'\n" +
	"\x0fhuman_escalated\x18\t \x01(\bR\x0ehumanEscalated\x12\x1f\n" +
	"\vrolled_back\x18\n" +
	" \x01(\bR\n" +
	"rolledBack\x12\x16\n" +
	"\x06cohort\x18\v \x01(\tR\x06cohort\"\xcb\x04\n" +
	"\rToolCallEvent\x12\x1b\n" +
	"\ttool_name\x18\x01 \x01(\tR\btoolName\x12!\n" +
	"\ftool_version\x18\x02 \x01(\tR\vtoolVersion\x12%\n" +
	"\x0earguments_hash\x18\x03 \x01(\tR\rargumentsHash\x12+\n" +
	"\x11arguments_summary\x18\x04 \x01(\tR\x10argumentsSummary\x12P\n" +
	"\x10permission_level\x18\x05 \x01(\x0e2%.routeiq.v1.telemetry.PermissionLevelR\x0fpermissionLevel\x129\n" +
	"\n" +
	"start_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\b \x01(\x01R\tlatencyMs\x12K\n" +
	"\rresult_status\x18\t \x01(\x0e2&.routeiq.v1.telemetry.ToolResultStatusR\fresultStatus\x12\x1d\n" +
	"\n" +
	"error_code\x18\n" +
	" \x01(\tR\terrorCode\x12%\n" +
	"\x0eresult_summary\x18\v \x01(\tR\rresultSummary\x120\n" +
	"\x14result_quality_flags\x18\f \x03(\tR\x12resultQualityFlags\"\xc6\x02\n" +
	"\tStepEvent\x12'\n" +
	"\x0fselected_action\x18\x01 \x01(\tR\x0eselectedAction\x12)\n" +
	"\x10action_rationale\x18\x02 \x01(\tR\x0factionRationale\x12S\n" +
	"\x11completion_status\x18\x03 \x01(\x0e2&.routeiq.v1.telemetry.CompletionStatusR\x10completionStatus\x12P\n" +
	"\x10failure_category\x18\x04 \x01(\x0e2%.routeiq.v1.telemetry.FailureCategoryR\x0ffailureCategory\x12\x1d\n" +
	"\n" +
	"step_index\x18\x05 \x01(\x05R\tstepIndex\x12\x1f\n" +
	"\vretry_count\x18\x06 \x01(\x05R\n" +
	"retryCount\"\xc6\x01\n" +
	"\rDecisionEvent\x12#\n" +
	"\rdecision_type\x18\x01 \x01(\tR\fdecisionType\x12-\n" +
	"\x12options_considered\x18\x02 \x01(\tR\x11optionsConsidered\x12#\n" +
	"\rchosen_option\x18\x03 \x01(\tR\fchosenOption\x12\x1c\n" +
	"\trationale\x18\x04 \x01(\tR\trationale\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x01R\n" +
	"confidence\"\xda\x01\n" +
	"\x0eRetrievalEvent\x12%\n" +
	"\x0eretrieval_type\x18\x01 \x01(\tR\rretrievalType\x12#\n" +
	"\rquery_summary\x18\x02 \x01(\tR\fquerySummary\x12#\n" +
	"\rresults_count\x18\x03 \x01(\x05R\fresultsCount\x12\x1b\n" +
	"\ttop_score\x18\x04 \x01(\x01R\btopScore\x12\x1b\n" +
	"\tcache_hit\x18\x05 \x01(\bR\bcacheHit\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x06 \x01(\x01R\tlatencyMs\"\x98\x01\n" +
	"\vMemoryEvent\x12\x1f\n" +
	"\vmemory_type\x18\x01 \x01(\tR\n" +
	"memoryType\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\x12\x1f\n" +
	"\vkey_summary\x18\x03 \x01(\tR\n" +
	"keySummary\x12)\n" +
	"\x10entries_affected\x18\x04 \x01(\x05R\x0fentriesAffected\"\xe2\x01\n" +
	"\fHandoffEvent\x12\"\n" +
	"\rfrom_agent_id\x18\x01 \x01(\tR\vfromAgentId\x12\x1e\n" +
	"\vto_agent_id\x18\x02 \x01(\tR\ttoAgentId\x12%\n" +
	"\x0ehandoff_reason\x18\x03 \x01(\tR\rhandoffReason\x12>\n" +
	"\x06status\x18\x04 \x01(\x0e2&.routeiq.v1.telemetry.CompletionStatusR\x06status\x12'\n" +
	"\x0fcontext_summary\x18\x05 \x01(\tR\x0econtextSummary\"\xbf\x01\n" +
	"\vPolicyEvent\x12\x1b\n" +
	"\tpolicy_id\x18\x01 \x01(\tR\bpolicyId\x12%\n" +
	"\x0ebundle_version\x18\x02 \x01(\tR\rbundleVersion\x12)\n" +
	"\x10action_evaluated\x18\x03 \x01(\tR\x0factionEvaluated\x12\x18\n" +
	"\averdict\x18\x04 \x01(\tR\averdict\x12'\n" +
	"\x0frules_triggered\x18\x05 \x03(\tR\x0erulesTriggered\"\xb1\x01\n" +
	"\x11InterventionEvent\x12+\n" +
	"\x11intervention_type\x18\x01 \x01(\tR\x10interventionType\x12%\n" +
	"\x0etrigger_reason\x18\x02 \x01(\tR\rtriggerReason\x12*\n" +
	"\x11trigger_metric_id\x18\x03 \x01(\tR\x0ftriggerMetricId\x12\x1c\n" +
	"\tautomated\x18\x04 \x01(\bR\tautomated\"\x98\x01\n" +
	"\rRecoveryEvent\x12#\n" +
	"\rrecovery_type\x18\x01 \x01(\tR\frecoveryType\x12\x1d\n" +
	"\n" +
	"from_error\x18\x02 \x01(\tR\tfromError\x12\x1c\n" +
	"\tsucceeded\x18\x03 \x01(\bR\tsucceeded\x12%\n" +
	"\x0eattempt_number\x18\x04 \x01(\x05R\rattemptNumber\"\x84\x01\n" +
	"\x12StateSnapshotEvent\x12#\n" +
	"\rsnapshot_type\x18\x01 \x01(\tR\fsnapshotType\x12(\n" +
	"\x10state_size_bytes\x18\x02 \x01(\x03R\x0estateSizeBytes\x12\x1f\n" +
	"\vsnapshot_id\x18\x03 \x01(\tR\n" +
	"snapshotId*\x8d\x03\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fTASK_STARTED\x10\x01\x12\x12\n" +
	"\x0eTASK_COMPLETED\x10\x02\x12\x0f\n" +
	"\vTASK_FAILED\x10\x03\x12\x10\n" +
	"\fSTEP_STARTED\x10\x04\x12\x12\n" +
	"\x0eSTEP_COMPLETED\x10\x05\x12\x11\n" +
	"\rDECISION_MADE\x10\x06\x12\x0f\n" +
	"\vTOOL_CALLED\x10\a\x12\x11\n" +
	"\rTOOL_RETURNED\x10\b\x12\x17\n" +
	"\x13RETRIEVAL_PERFORMED\x10\t\x12\x0f\n" +
	"\vMEMORY_READ\x10\n" +
	"\x12\x12\n" +
	"\x0eMEMORY_WRITTEN\x10\v\x12\x15\n" +
	"\x11HANDOFF_INITIATED\x10\f\x12\x14\n" +
	"\x10HANDOFF_ACCEPTED\x10\r\x12\x14\n" +
	"\x10POLICY_EVALUATED\x10\x0e\x12\x1a\n" +
	"\x16INTERVENTION_TRIGGERED\x10\x0f\x12\x16\n" +
	"\x12RECOVERY_ATTEMPTED\x10\x10\x12\x1b\n" +
	"\x17STATE_SNAPSHOT_CAPTURED\x10\x11B\x97\x01\n" +
	"2build.buf.gen.ssforge.routeiq.routeiq.v1.telemetryB\vEventsProtoZTbuf.build/gen/go/ssforge/routeiq/protocolbuffers/go/routeiq/v1/telemetry;telemetryv1b\x06proto3"

var (
	file_routeiq_v1_telemetry_events_proto_rawDescOnce sync.Once
	file_routeiq_v1_telemetry_events_proto_rawDescData []byte
)

func file_routeiq_v1_telemetry_events_proto_rawDescGZIP() []byte {
	file_routeiq_v1_telemetry_events_proto_rawDescOnce.Do(func() {
		file_routeiq_v1_telemetry_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_routeiq_v1_telemetry_events_proto_rawDesc), len(file_routeiq_v1_telemetry_events_proto_rawDesc)))
	})
	return file_routeiq_v1_telemetry_events_proto_rawDescData
}

var file_routeiq_v1_telemetry_events_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_routeiq_v1_telemetry_events_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_routeiq_v1_telemetry_events_proto_goTypes = []any{
	(EventType)(0),                // 0: routeiq.v1.telemetry.EventType
	(*VersionLineage)(nil),        // 1: routeiq.v1.telemetry.VersionLineage
	(*AgentEvent)(nil),            // 2: routeiq.v1.telemetry.AgentEvent
	(*TaskEvent)(nil),             // 3: routeiq.v1.telemetry.TaskEvent
	(*ToolCallEvent)(nil),         // 4: routeiq.v1.telemetry.ToolCallEvent
	(*StepEvent)(nil),             // 5: routeiq.v1.telemetry.StepEvent
	(*DecisionEvent)(nil),         // 6: routeiq.v1.telemetry.DecisionEvent
	(*RetrievalEvent)(nil),        // 7: routeiq.v1.telemetry.RetrievalEvent
	(*MemoryEvent)(nil),           // 8: routeiq.v1.telemetry.MemoryEvent
	(*HandoffEvent)(nil),          // 9: routeiq.v1.telemetry.HandoffEvent
	(*PolicyEvent)(nil),           // 10: routeiq.v1.telemetry.PolicyEvent
	(*InterventionEvent)(nil),     // 11: routeiq.v1.telemetry.InterventionEvent
	(*RecoveryEvent)(nil),         // 12: routeiq.v1.telemetry.RecoveryEvent
	(*StateSnapshotEvent)(nil),    // 13: routeiq.v1.telemetry.StateSnapshotEvent
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
	(AutonomyMode)(0),             // 15: routeiq.v1.telemetry.AutonomyMode
	(RiskTier)(0),                 // 16: routeiq.v1.telemetry.RiskTier
	(CompletionStatus)(0),         // 17: routeiq.v1.telemetry.CompletionStatus
	(FailureCategory)(0),          // 18: routeiq.v1.telemetry.FailureCategory
	(PermissionLevel)(0),          // 19: routeiq.v1.telemetry.PermissionLevel
	(ToolResultStatus)(0),         // 20: routeiq.v1.telemetry.ToolResultStatus
}
var file_routeiq_v1_telemetry_events_proto_depIdxs = []int32{
	14, // 0: routeiq.v1.telemetry.AgentEvent.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 1: routeiq.v1.telemetry.AgentEvent.event_type:type_name -> routeiq.v1.telemetry.EventType
	1,  // 2: routeiq.v1.telemetry.AgentEvent.versions:type_name -> routeiq.v1.telemetry.VersionLineage
	15, // 3: routeiq.v1.telemetry.AgentEvent.autonomy_mode:type_name -> routeiq.v1.telemetry.AutonomyMode
	16, // 4: routeiq.v1.telemetry.AgentEvent.risk_tier:type_name -> routeiq.v1.telemetry.RiskTier
	3,  // 5: routeiq.v1.telemetry.AgentEvent.task:type_name -> routeiq.v1.telemetry.TaskEvent
	5,  // 6: routeiq.v1.telemetry.AgentEvent.step:type_name -> routeiq.v1.telemetry.StepEvent
	6,  // 7: routeiq.v1.telemetry.AgentEvent.decision:type_name -> routeiq.v1.telemetry.DecisionEvent
	4,  // 8: routeiq.v1.telemetry.AgentEvent.tool_call:type_name -> routeiq.v1.telemetry.ToolCallEvent
	7,  // 9: routeiq.v1.telemetry.AgentEvent.retrieval:type_name -> routeiq.v1.telemetry.RetrievalEvent
	8,  // 10: routeiq.v1.telemetry.AgentEvent.memory:type_name -> routeiq.v1.telemetry.MemoryEvent
	9,  // 11: routeiq.v1.telemetry.AgentEvent.handoff:type_name -> routeiq.v1.telemetry.HandoffEvent
	10, // 12: routeiq.v1.telemetry.AgentEvent.policy:type_name -> routeiq.v1.telemetry.PolicyEvent
	11, // 13: routeiq.v1.telemetry.AgentEvent.intervention:type_name -> routeiq.v1.telemetry.InterventionEvent
	12, // 14: routeiq.v1.telemetry.AgentEvent.recovery:type_name -> routeiq.v1.telemetry.RecoveryEvent
	13, // 15: routeiq.v1.telemetry.AgentEvent.state_snapshot:type_name -> routeiq.v1.telemetry.StateSnapshotEvent
	17, // 16: routeiq.v1.telemetry.TaskEvent.completion_status:type_name -> routeiq.v1.telemetry.CompletionStatus
	18, // 17: routeiq.v1.telemetry.TaskEvent.failure_category:type_name -> routeiq.v1.telemetry.FailureCategory
	19, // 18: routeiq.v1.telemetry.ToolCallEvent.permission_level:type_name -> routeiq.v1.telemetry.PermissionLevel
	14, // 19: routeiq.v1.telemetry.ToolCallEvent.start_time:type_name -> google.protobuf.Timestamp
	14, // 20: routeiq.v1.telemetry.ToolCallEvent.end_time:type_name -> google.protobuf.Timestamp
	20, // 21: routeiq.v1.telemetry.ToolCallEvent.result_status:type_name -> routeiq.v1.telemetry.ToolResultStatus
	17, // 22: routeiq.v1.telemetry.StepEvent.completion_status:type_name -> routeiq.v1.telemetry.CompletionStatus
	18, // 23: routeiq.v1.telemetry.StepEvent.failure_category:type_name -> routeiq.v1.telemetry.FailureCategory
	17, // 24: routeiq.v1.telemetry.HandoffEvent.status:type_name -> routeiq.v1.telemetry.CompletionStatus
	25, // [25:25] is the sub-list for method output_type
	25, // [25:25] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_routeiq_v1_telemetry_events_proto_init() }
func file_routeiq_v1_telemetry_events_proto_init() {
	if File_routeiq_v1_telemetry_events_proto != nil {
		return
	}
	file_routeiq_v1_telemetry_entities_proto_init()
	file_routeiq_v1_telemetry_events_proto_msgTypes[1].OneofWrappers = []any{
		(*AgentEvent_Task)(nil),
		(*AgentEvent_Step)(nil),
		(*AgentEvent_Decision)(nil),
		(*AgentEvent_ToolCall)(nil),
		(*AgentEvent_Retrieval)(nil),
		(*AgentEvent_Memory)(nil),
		(*AgentEvent_Handoff)(nil),
		(*AgentEvent_Policy)(nil),
		(*AgentEvent_Intervention)(nil),
		(*AgentEvent_Recovery)(nil),
		(*AgentEvent_StateSnapshot)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_routeiq_v1_telemetry_events_proto_rawDesc), len(file_routeiq_v1_telemetry_events_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_routeiq_v1_telemetry_events_proto_goTypes,
		DependencyIndexes: file_routeiq_v1_telemetry_events_proto_depIdxs,
		EnumInfos:         file_routeiq_v1_telemetry_events_proto_enumTypes,
		MessageInfos:      file_routeiq_v1_telemetry_events_proto_msgTypes,
	}.Build()
	File_routeiq_v1_telemetry_events_proto = out.File
	file_routeiq_v1_telemetry_events_proto_goTypes = nil
	file_routeiq_v1_telemetry_events_proto_depIdxs = nil
}
